fix:Utility classes should not have public constructors
alibaba/nacos pull request #10019
Opened 2023-02-28 09:36 UTC by 4yDX3906

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Utility classes should not have public constructors.

## Brief changelog

To com/alibaba/nacos/common/utils package under the utility class and a private constructor.

## Associated issue
#10018

2023-03-01 01:39 UTC, KomachiSion requested changes
when you add the private constructor, how to do unit test the constructor?

I have no idea for this `rule`, the public constructor has no effect.

2023-03-02 03:46 UTC, 4yDX3906 commented
> when you add the private constructor, how to do unit test the constructor?
> 
> I have no idea for this `rule`, the public constructor has no effect.



> when you add the private constructor, how to do unit test the constructor?
> 
> I have no idea for this `rule`, the public constructor has no effect.

A utility class is a class that is just a namespace for functions.  No instances of it can exist,   and all its members are static. I don't think I need to unit test its constructor. Just make sure the static methods  are available. For example,  `java.lang.Math` and `java.util.Collections` are well known utility classes. Their constructor is private.

2023-03-06 01:38 UTC, KomachiSion commented
It seems auto ignore private constructor after jacoco 0.8.0.

https://github.com/jacoco/jacoco/wiki/FilteringOptions

we use 0.8.7.

2023-03-06 01:39 UTC, KomachiSion approved these changes

2023-03-06 01:39 UTC, merged