Fix fs char
alibaba/nacos pull request #10101
Opened 2023-03-14 16:39 UTC by Daydreamer-ia

Please do not create a Pull Request without creating an issue first.
#10067
## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-03-14 16:40 UTC, Daydreamer-ia commented
Proposal: https://www.yuque.com/nacos/fh5oxd/gl7y6957xdnkqqmi

2023-03-17 03:31 UTC, Daydreamer-ia commented
link to #10119

2023-03-24 03:33 UTC, KomachiSion requested changes

2023-03-24 03:33 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/pathencoder/PathEncoderManager.java
> +public class PathEncoderManager {
Manager换成单例实现会不会比较好。

全静态方法感觉是个`Utils`

2023-03-24 14:09 UTC, Daydreamer-ia commented on common/src/main/java/com/alibaba/nacos/common/pathencoder/PathEncoderManager.java
> +public class PathEncoderManager {
done

2023-03-27 07:04 UTC, merged