[ISSUE #10128]fix bug
alibaba/nacos pull request #10129
Opened 2023-03-17 12:46 UTC by varyuan

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-03-20 01:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=10129) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=10129) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=10129) it.</sub>

2023-03-20 07:22 UTC, KomachiSion requested changes

2023-03-20 07:22 UTC, KomachiSion commented on core/src/main/java/com/alibaba/nacos/core/distributed/raft/NacosStateMachine.java
> +                                && Arrays.stream(results).allMatch(Boolean.TRUE::equals) ? Status.OK()
From the idea hint

I think `Arrays.stream(results).noneMatch(Boolean.FALSE::equals)` is better.`

2023-03-20 07:28 UTC, varyuan commented on core/src/main/java/com/alibaba/nacos/core/distributed/raft/NacosStateMachine.java
> +                                && Arrays.stream(results).allMatch(Boolean.TRUE::equals) ? Status.OK()
boolean[] 改为Boolean[] 是必须的改变, Boolean[]元素的默认值是null, Boolean.FALSE::equals 和null比较还是false, 而且allMatch是短路的方法, noneMatch必须比较完全部元素, 所以我觉得`allMatch(Boolean.TRUE::equals)`是最好得

2023-03-21 05:49 UTC, KomachiSion commented on core/src/main/java/com/alibaba/nacos/core/distributed/raft/NacosStateMachine.java
> +                                && Arrays.stream(results).allMatch(Boolean.TRUE::equals) ? Status.OK()
ok

2023-03-21 07:28 UTC, KomachiSion approved these changes

2023-03-21 07:29 UTC, merged