[ISSUE #10159]修改mapperProxy单例
alibaba/nacos pull request #10162
Opened 2023-03-22 05:20 UTC by 985492783

fix #10159

2023-03-22 06:52 UTC, 985492783 commented
> 为什么不用ConcurrentHashMap, 而是用hashmap+lock

用ConcurrentHashMap读写确实没问题，但是在实例对象前一样要对ConcurrentHashMap加锁才能保证实例对象的原子性，所以采用读写锁，但我更想饿汉式加载，就不会存在线程安全的问题了

2023-03-24 01:39 UTC, KomachiSion requested changes
写锁可以理解， 读锁是不是没有必要？

2023-03-24 02:02 UTC, 985492783 commented
> 写锁可以理解， 读锁是不是没有必要？

在用spi加载mapper的时候同时创建mapperProxy可以吗，因为预热完就全是读操作了，加锁还是会影响性能，读锁是因为并发读写hashmap如果发生扩容可能会出现读空的情况
![image](https://user-images.githubusercontent.com/73023513/227405175-056e1eda-c476-43cc-b7d3-9d3d8cc98b71.png)

2023-03-27 07:03 UTC, KomachiSion commented
你的意思是，在loadInitial的时候加载完缓存？ 也可以， 目前这个开关是动态的吗？ 需要重启吗？

2023-03-27 07:10 UTC, 985492783 commented
> 你的意思是，在loadInitial的时候加载完缓存？ 也可以， 目前这个开关是动态的吗？ 需要重启吗？

开关依赖于配置nacos.plugin.datasource.log.enabled，改变需要重启，那我改成在loadInitial的中把代理对象放入MAPPER_SPI_MAP

2023-03-28 01:41 UTC, KomachiSion approved these changes

2023-03-28 01:41 UTC, merged