clean code
alibaba/nacos pull request #10180
Opened 2023-03-24 01:48 UTC by varyuan

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-03-27 06:56 UTC, KomachiSion requested changes

2023-03-27 06:56 UTC, KomachiSion commented on core/src/main/java/com/alibaba/nacos/core/control/TpsControlConfig.java
> +    public static boolean isTpsControlEnabled() {
Why remove final

2023-03-27 06:56 UTC, KomachiSion commented on plugin/control/src/main/java/com/alibaba/nacos/plugin/control/ruleactivator/RuleStorageProxy.java
> +    public static RuleStorageProxy getInstance() {
Why remove final

2023-03-27 06:56 UTC, KomachiSion commented on plugin/control/src/main/java/com/alibaba/nacos/plugin/control/tps/nacos/LocalSimpleCountBarrierCreator.java
> +    public static LocalSimpleCountBarrierCreator getInstance() {
Why remove final

2023-03-28 01:28 UTC, varyuan commented on plugin/control/src/main/java/com/alibaba/nacos/plugin/control/tps/nacos/LocalSimpleCountBarrierCreator.java
> +    public static LocalSimpleCountBarrierCreator getInstance() {
final防止子类重写方法, 静态方法不能被@Override, 加上也没错,但是应该也不会写出子类声明相同的方法签名的静态方法吧, 改了

2023-03-28 01:38 UTC, KomachiSion requested changes

2023-03-28 01:38 UTC, KomachiSion commented on plugin/control/src/main/java/com/alibaba/nacos/plugin/control/ruleactivator/RuleStorageProxy.java
> +
Why remove indent?

Please use nacos code style to reformat.

2023-03-28 01:38 UTC, KomachiSion commented on plugin/control/src/main/java/com/alibaba/nacos/plugin/control/tps/nacos/LocalSimpleCountBarrierCreator.java
> +
Why remove indent?

2023-03-29 06:25 UTC, KomachiSion approved these changes

2023-03-29 06:25 UTC, merged