[ISSUE #10254]Allow the naming module to run independently.
alibaba/nacos pull request #10255
Opened 2023-04-02 14:30 UTC by yuyijq

Allow the naming module to run independently.

1. import nacos-auth dependency in naming
2. methodCache
3. auth config

2023-04-03 01:55 UTC, KomachiSion requested changes

2023-04-03 01:55 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/web/NamingConfig.java
> -    @Bean
Why remove bean annontation

2023-04-04 04:44 UTC, yuyijq commented on naming/src/main/java/com/alibaba/nacos/naming/web/NamingConfig.java
> -    @Bean
这个Filter上的几个@Bean其实是没有必要的，因为我们是以FilterRegistrationBean的方式注入，二选一。如果Filter上也加@Bean相当于重复注册。

2023-04-06 07:09 UTC, KomachiSion requested changes

2023-04-06 07:09 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/web/NamingConfig.java
> -    @Bean
是说会创建2个filter， 一个被注入了，一个被spring beanFactory管理起来了？

这个有验证过吗？比如dump内存后看一下。

2023-04-06 16:33 UTC, yuyijq commented on naming/src/main/java/com/alibaba/nacos/naming/web/NamingConfig.java
> -    @Bean
实际上从代码的写法就能看出来：
```
    @Bean
    public FilterRegistrationBean distroFilterRegistration() {
        FilterRegistrationBean<DistroFilter> registration = new FilterRegistrationBean<>();
        registration.setFilter(distroFilter());
        registration.addUrlPatterns(UTL_PATTERNS);
        registration.setName(DISTRO_FILTER);
        registration.setOrder(6);
        return registration;
    }
```
这是这个FilterRegistrationBean的定义方式，这个里面直接调用了distroFilter()方法，根本就没走Spring的注入，如果走Spring的注入也应该是这样写：
```
    @Bean
    public FilterRegistrationBean distroFilterRegistration(DistroFilter distroFilter) {
        FilterRegistrationBean<DistroFilter> registration = new FilterRegistrationBean<>();
        registration.setFilter(distroFilter);
        registration.addUrlPatterns(UTL_PATTERNS);
        registration.setName(DISTRO_FILTER);
        registration.setOrder(6);
        return registration;
    }
```
所以下面代码上的@Bean是没有必要的
```
    @Bean
    public DistroFilter distroFilter() {
        return new DistroFilter();
    }
```

另外，我的IDE其实对上面的代码是有warning的，就是说写错了

2023-04-10 02:43 UTC, KomachiSion submitted a review, later dismissed

2023-04-10 03:51 UTC, KomachiSion commented
Some problem in committed files which lose the copyright.

Please do `ci.yaml` action list in local before submit PR.

2023-04-17 08:28 UTC, KomachiSion commented
IT seems can't pass, please fix them.

2023-04-21 08:27 UTC, closed without merging