add configModuleState/raftModuleState/distroModuleState
alibaba/nacos pull request #10288
Opened 2023-04-07 16:56 UTC by 985492783

add configModuleState/raftModuleState/distroModuleState and test

2023-04-08 04:45 UTC, 985492783 commented
linked #10197

2023-04-13 11:19 UTC, KomachiSion requested changes

2023-04-13 11:19 UTC, KomachiSion commented on sys/src/main/java/com/alibaba/nacos/sys/env/EnvModuleStateBuilder.java
> +        state.newState(Constants.NACOS_SERVER_IP_STATE, System.getProperty(Constants.NACOS_SERVER_IP));
IP 会不会算是数据，暴露出去会不会有安全风险？

2023-05-08 10:05 UTC, KomachiSion approved these changes

2023-05-08 10:05 UTC, KomachiSion approved these changes

2023-05-08 10:05 UTC, merged