Report deregister event if read snapshot file
alibaba/nacos pull request #10468
Opened 2023-05-11 06:21 UTC by Daydreamer-ia

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX
#10406
## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-05-12 03:13 UTC, Lin-1997 commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
> +        oldClients.forEach((clientId, client) -> client.release());
似乎有问题，调用链是：
PersistentInstanceSnapshotOperation#loadSnapshot----snapshotClient.init();
-->
clientManager.loadFromSnapshot(snapshot);
-->
oldClients.forEach((clientId, client) -> client.release());

上面的snapshotClient.init();如果是clientBeat的形式，会调：
HealthCheckReactor#scheduleCheck----futureMap.computeIfAbsent(task.taskKey(), xxx)
这task还没有释放，所以不会再加进去

但是后面oldClients.forEach((clientId, client) -> client.release());会释放掉，导致没有了clientBeat的task

2023-05-12 04:50 UTC, Daydreamer-ia commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
> +        oldClients.forEach((clientId, client) -> client.release());
i get it

2023-05-16 03:22 UTC, JianweiWang commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> +                        Loggers.RAFT.info("[SNAPSHOT-DATA-ADD] service={}, instance={}", service, newInstanceInfo);
日志这里最好能区分下ADD 和 UPDATE

2023-05-16 03:33 UTC, JianweiWang commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> +                    Loggers.RAFT.info("[SNAPSHOT-DATA-REMOVE] service={}, instance={}", service, client.getInstancePublishInfo(service));
日志放到操作完成之后，和ADD、UPDATE保持一致

2023-05-16 04:31 UTC, Daydreamer-ia commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> +                        Loggers.RAFT.info("[SNAPSHOT-DATA-ADD] service={}, instance={}", service, newInstanceInfo);
i get it

2023-05-16 04:32 UTC, Daydreamer-ia commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> +                    Loggers.RAFT.info("[SNAPSHOT-DATA-REMOVE] service={}, instance={}", service, client.getInstancePublishInfo(service));
i get it

2023-05-16 08:05 UTC, pixystone requested changes
Be aware of the performance.

2023-05-17 03:12 UTC, Daydreamer-ia commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
> +     * add client directlt.
i get it

2023-05-17 03:17 UTC, Daydreamer-ia commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> +                        client.addServiceInstance(singleton, newInstanceInfo);
i get it

2023-05-17 03:17 UTC, Daydreamer-ia commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> +                        Loggers.RAFT.info("[SNAPSHOT-DATA-ADD] service={}, instance={}", service, newInstanceInfo);
i get it

2023-05-17 03:22 UTC, Daydreamer-ia commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> +                if (oldClientIds.contains(entry.getKey())) {
i get it

2023-05-19 04:03 UTC, Lin-1997 commented
can we just throw away the old data and load the new data? I think this is more suitable for the semantics of installing snapshot.
i.e., disconnect all old clients, and then publish all clients from snapshot, instead of updating/deleting existing data

2023-05-19 04:37 UTC, Daydreamer-ia commented
> can we just throw away the old data and load the new data? I think this is more suitable for the semantics of installing snapshot. i.e., disconnect all old clients, and then publish all clients from snapshot, instead of updating/deleting existing data

@KomachiSion He thinks the old way to load snapshot is better. How can i do to solve it?

2023-05-19 06:14 UTC, Lin-1997 commented
> > can we just throw away the old data and load the new data? I think this is more suitable for the semantics of installing snapshot. i.e., disconnect all old clients, and then publish all clients from snapshot, instead of updating/deleting existing data
> 
> @KomachiSion He thinks the old way to load snapshot is better. How can i do to solve it?

My idea is not suitable in some cases. If the follower is just disconnected to the leader right before the leader saves snapshot, and recovers soon. Throw away all the old data also seems to be unreasonable.

2023-05-19 08:53 UTC, Lin-1997 commented
how about this:

we construct snapshot data in `PersistentClientOperationServiceImpl` and handle it in `PersistentIpPortClientManager`.

first, `PersistentClientOperationServiceImpl` only constructs `ConcurrentHashMap<String, IpPortBasedClient> snapshot` and doesn't modify data in other `manager` or `index`, i.e., remove L368-369.

https://github.com/alibaba/nacos/blob/51903edd82a3f244a5e21f173f011485298f348f/naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java#L357-L371

Also we doesn't need to init snapshotClient in L350, because we are going to regenerate the client in `PersistentIpPortClientManager`.

https://github.com/alibaba/nacos/blob/51903edd82a3f244a5e21f173f011485298f348f/naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java#L344-L355

then, we handle the snapshot in `PersistentIpPortClientManager` in the follow function:

https://github.com/alibaba/nacos/blob/51903edd82a3f244a5e21f173f011485298f348f/naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java#L131-L135

like this:

```
public void loadSnapshot(ConcurrentMap<String, IpPortBasedClient> snapshot) {
    // disconnect expired clients
    Set<String> shouldDelete = new HashSet<>(clients.keySet());
    shouldDelete.removeAll(snapshot.keySet());
    shouldDelete.forEach(this::clientDisconnected); // TODO should be enough, needed to be confirmed

    // load snapshot clients
    snapshot.forEach((clientId, snapshotClient) -> {
        Client existingClient;
        if (contains(clientId)) {
            existingClient = getClient(clientId);
            removeExpiredInstances(existingClient, snapshotClient);
        } else {
            clientConnected(clientId, snapshotClient.getClientAttributes()); // TODO deep copy of clientAttributes
            existingClient = getClient(clientId);
            ((IpPortBasedClient) existingClient).init();
        }

        loadSnapshotInstances(existingClient, snapshotClient);
    });
    snapshot.clear();
}

private void removeExpiredInstances(Client existingClient, Client snapshotClient) {
    Set<Service> shouldDelete = new HashSet<>(existingClient.getAllPublishedService());
    shouldDelete.removeAll(snapshotClient.getAllPublishedService());
    shouldDelete.forEach(service -> {
        Service singleton = ServiceManager.getInstance().getSingleton(service);
        existingClient.removeServiceInstance(singleton);
        NotifyCenter.publishEvent(new ClientOperationEvent
                .ClientDeregisterServiceEvent(singleton, existingClient.getClientId()));
    });
}

private void loadSnapshotInstances(Client existingClient, Client snapshotClient) {
    snapshotClient.getAllPublishedService().forEach(service -> {
        Service singleton = ServiceManager.getInstance().getSingleton(service);
        existingClient.addServiceInstance(singleton, snapshotClient.getInstancePublishInfo(singleton));
        NotifyCenter.publishEvent(new ClientOperationEvent
                .ClientRegisterServiceEvent(singleton, existingClient.getClientId()));
    });
}
```

2023-05-21 13:10 UTC, pixystone commented
There is only a single thread applying the raft log of every group in sequence. So I think the in-place modifying method is suitable here in order that we don't need to consider the thread-safe problem.

2023-05-21 15:28 UTC, Daydreamer-ia commented
> There is only a single thread applying the raft log of every group in sequence. So I think the in-place modifying method is suitable here in order that we don't need to consider the thread-safe problem.

Yes, I have done in place instead of replacing them in full

2023-06-14 01:54 UTC, Daydreamer-ia commented
> https://github.com/alibaba/nacos/blob/8cd5a5ea0bfb7014523eb19ca72e28282a9155a2/naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java#L193-L211
> 
> may lose the true Service singleton, since it is load from snapshot, while the singleton in menory doesn't change. Also have not clean the expried ones.
> 
> may also has to call ServiceStorage#removeData of those expried services. But we can not call this function in MetadataManager, my idea is make a new type of event, and publish in ServiceManager#removeSingleton.

i see. You mean that there are some outdated service index in ServiceStorage#serviceDataIndexes without clean? The empty service will be clean by EmptyServiceAutoCleanerV2 actually, so there is unnecessary to make a new type of event to clean.

2023-06-19 05:36 UTC, pixystone commented
LGTM

2023-06-26 01:41 UTC, KomachiSion approved these changes

2023-06-26 01:41 UTC, merged