Update MapperProxy.java
alibaba/nacos pull request #10487
Opened 2023-05-15 04:29 UTC by scwlkq

fix:代理类打印日志错误

#10486

2023-05-15 04:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=10487) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=10487) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=10487) it.</sub>

2023-05-15 04:50 UTC, 985492783 requested changes

2023-05-15 04:50 UTC, 985492783 commented on plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/proxy/MapperProxy.java
> +        String sql = ((MapperResult)invoke).getSql();
有MapperResult和String两种类型，需要判断一下

2023-05-16 02:20 UTC, KomachiSion submitted a review, later dismissed

2023-05-16 02:38 UTC, KomachiSion commented
It seems ci can't pass, please fix them.

2023-05-16 10:56 UTC, KomachiSion requested changes

2023-05-16 10:56 UTC, KomachiSion commented on plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/proxy/MapperProxy.java
> +
The indent changed, please use nacos code style to reformat code.

2023-05-17 01:27 UTC, KomachiSion approved these changes

2023-05-17 01:28 UTC, KomachiSion commented
> Sorry, due to the first submission, I did not carefully read the nacos pr specification, which wasted the review time

No problem, PR keeping enhance and fix will be merged.

2023-05-17 08:57 UTC, merged