Add the validation for namespace name
alibaba/nacos pull request #10520
Opened 2023-05-19 10:31 UTC by Daydreamer-ia

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX
#10517
## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-05-22 02:16 UTC, KomachiSion commented
我觉得issue的意思是， ui上校验了namespaceid的唯一性， 但是如果我不通过ui创建，而是通过openAPI创建， 就可以绕过这个限制添加重复的id（虽然数据库那边大概会DPKE）。 应该是希望在openAPI上校验一下重复性。不是校验名字的规范。

2023-05-22 03:56 UTC, Daydreamer-ia commented
> 我觉得issue的意思是， ui上校验了namespaceid的唯一性， 但是如果我不通过ui创建，而是通过openAPI创建， 就可以绕过这个限制添加重复的id（虽然数据库那边大概会DPKE）。 应该是希望在openAPI上校验一下重复性。不是校验名字的规范。

他的描述有提到说@和#非法字符可以直接通过接口创建

2023-05-22 03:58 UTC, Daydreamer-ia commented
> 我觉得issue的意思是， ui上校验了namespaceid的唯一性， 但是如果我不通过ui创建，而是通过openAPI创建， 就可以绕过这个限制添加重复的id（虽然数据库那边大概会DPKE）。 应该是希望在openAPI上校验一下重复性。不是校验名字的规范。

接口上确实也缺失了校验唯一性，我再补充一下

2023-05-22 05:45 UTC, KomachiSion commented
展示名应该是可以用任意字符的，前端代码里有这些字符的校验吗？

2023-05-22 06:13 UTC, Daydreamer-ia commented
> 展示名应该是可以用任意字符的，前端代码里有这些字符的校验吗？

有的，我在前端代码找到这个校验使用的正则，我也在后台接口加了这个校验
![截屏2023-05-22 14 11 49](https://github.com/alibaba/nacos/assets/83362909/8bab65a6-6da6-4819-8fb3-6727c492d451)
![截屏2023-05-22 14 13 29](https://github.com/alibaba/nacos/assets/83362909/c5dbead4-237c-4aed-b23e-f3825daaa1e2)

2023-05-22 08:41 UTC, KomachiSion requested changes
UT 好像没有验证到这个逻辑， 加一下吧。

2023-05-22 16:02 UTC, Daydreamer-ia commented
> UT 好像没有验证到这个逻辑， 加一下吧。

添加完成

2023-05-23 02:23 UTC, KomachiSion approved these changes

2023-05-23 02:23 UTC, merged