[ISSUE #10598] Fix nacos-client get the wrong index of the nacos server list when use nacos-address endpoint
alibaba/nacos pull request #10599
Opened 2023-06-03 05:08 UTC by 1em0n9527

## What is the purpose of the change
fix nacos client get the wrong index of nacos server list  when use nacos-address endpoint
fix #10598 
## Brief changelog
fix an index value which did not initialized

## Verifying this change
XXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-06-03 05:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=10599) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=10599) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=10599) it.</sub>

2023-06-05 03:08 UTC, Daydreamer-ia submitted a review, later dismissed

2023-06-05 08:56 UTC, KomachiSion requested changes

2023-06-05 08:56 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
> +        if (getServerList().isEmpty()) {
判断条件需要改一下, 需要判断endpoint是否为空

2023-06-07 05:30 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
> +        if (getServerList().isEmpty()) {
serversFromEndpoint 如果 地址服务器异常或者网络异常， 这里判空可能会抛出异常，这里应该异常的情况是endpoint未配置且serverlist为空。即保持原有的判断。

2023-06-13 03:13 UTC, KomachiSion approved these changes

2023-06-14 02:56 UTC, merged