fix(#10831): When using the deregisterInstance method to remove one o…
alibaba/nacos pull request #10836
Opened 2023-07-21 10:23 UTC by Bo-Qiu

## What is the purpose of the change

fix(#10831  ) When using the deregisterInstance method to remove one of multiple instances registered by batchRegisterInstance, all instances registered by batchRegisterInstance will be removed. 

## Brief changelog

fix(#10831  ) When using the deregisterInstance method to remove one of multiple instances registered by batchRegisterInstance, all instances registered by batchRegisterInstance will be removed. 

## Verifying this change

fix(#10831  ) When using the deregisterInstance method to remove one of multiple instances registered by batchRegisterInstance, all instances registered by batchRegisterInstance will be removed.

2023-07-25 01:29 UTC, KomachiSion requested changes
Is it thread safe?

2023-07-25 03:25 UTC, Bo-Qiu commented
To ensure the thread safety of this method, we just need to maintain the thread safety of batchDeregisterService. Is the thread safety issue around batchDeregisterService fixed within this PR, or should we propose a new PR for it?

2023-07-25 03:36 UTC, Bo-Qiu commented
@KomachiSion  
By the way, I've noticed that there are many places where unnecessary 'synchronized' locks have been added. Since registeredInstances and subscribes are instances of ConcurrentHashMap, which is inherently thread-safe, there's no need to add extra locks for its atomic operations. Do you think it's necessary to open an issue to optimize this? 
e.g.
```
synchronized (subscribes) {
            subscribes.put(key, redoData);
        }
```
synchronized should be removed.

```
synchronized (subscribes) {
            SubscriberRedoData redoData = subscribes.get(key);
            if (null != redoData) {
                redoData.setRegistered(true);
            }
        }
```
It can be replaced by the computeIfPresent method

2023-07-26 07:11 UTC, Bo-Qiu commented
I have directly placed the implementation of batchDeregisterService within a synchronized block to ensure thread safety. Should I use a better way to ensure thread safety?

2023-07-28 01:47 UTC, KomachiSion approved these changes

2023-07-28 01:47 UTC, merged