feat(#10891): Provide a configuration item for the maximum number of p…
alibaba/nacos pull request #10895
Opened 2023-08-01 07:42 UTC by Bo-Qiu

## What is the purpose of the change

feat(#10891 ): Provide a configuration item for the maximum number of push retries, instead of directly hardcoding it to 50 times in the code.

## Brief changelog

feat(#10891 ): Provide a configuration item for the maximum number of push retries, instead of directly hardcoding it to 50 times in the code.

2023-08-01 07:50 UTC, KomachiSion commented
Please see issue.

2023-08-01 08:57 UTC, KomachiSion requested changes
use com.alibaba.nacos.core.config.AbstractDynamicConfig

2023-08-01 11:17 UTC, Bo-Qiu commented
> use com.alibaba.nacos.core.config.AbstractDynamicConfig

Thanks for your information, I changed it, please review it again.

2023-08-04 04:03 UTC, KomachiSion approved these changes

2023-08-04 04:03 UTC, merged