Remove UDP Receiver
alibaba/nacos pull request #10903
Opened 2023-08-02 08:02 UTC by ZhangShenao

## What is the purpose of the change

Remove `UdpReceiver` for client-v2.

## Brief changelog

1. Remove `UdpConnector.UdpReceiver` task to release udp port on client.
2. Remove udp request param in instance query api.

2023-08-02 08:02 UTC, ZhangShenao commented
#10824

2023-08-04 04:00 UTC, KomachiSion requested changes

2023-08-04 04:00 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> -        params.put(UDP_PORT_PARAM, String.valueOf(udpPort));
Http client request this port, if you need remove, please remove whole implementation, or keep this parameter.

2023-08-04 04:00 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java
Why not remove the class derectly.

2023-08-04 06:17 UTC, ZhangShenao commented on naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java
`UdpConnector` is still used by `UdpPushService`, and `PushExecutorUdpImpl` is an alternative implementation of `PushExecutorDelegate`. Will it cause significant impact if remove `UdpConnector` directly?

2023-08-04 07:16 UTC, KomachiSion commented
OK.

2023-08-04 07:16 UTC, KomachiSion approved these changes

2023-08-04 07:18 UTC, KomachiSion requested changes
I see again this PR. I found that this UdpConnector is used by server part.

I think the Udpreceiver can't delete. because some 1.X client need it.

2023-08-04 07:26 UTC, closed without merging