[ISSUE #10374] Define selectors and related components
alibaba/nacos pull request #10954
Opened 2023-08-12 10:05 UTC by ldyedu

## What is the purpose of the change

For [#10374](https://github.com/alibaba/nacos/issues/10374), Define selectors and related components.

## Brief changelog

* **nacos-api :** Add `Selector`、`NamingSelector` and `NamingContext`.
* **nacos-client:** Add `DefaultNamingSelector`、 `ListenerInvoker`、`NamingListenerInvoker`、`AbstractSelectorWrapper`、`NamingSelectorWrapper`、`SelectorManager` and `SelectorFactory`。
* Add unit tests.
* Update `InstanceDiff`.

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-08-14 07:04 UTC, KomachiSion requested changes

2023-08-14 07:04 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/selector/NamingSelectorWrapper.java
> +    private boolean isChanged(NamingEvent namingEvent) {
这个逻辑只判断的ip端口吗？ 不考虑元数据变更？

2023-08-14 07:14 UTC, ldyedu commented on client/src/main/java/com/alibaba/nacos/client/naming/selector/NamingSelectorWrapper.java
> +    private boolean isChanged(NamingEvent namingEvent) {
比较实例是否变更是用了 `toString()` 方法，所以元数据也包含在内。但是测试用例里没有测试元数据变更的情况，这里需要再完善测试用例。

2023-08-17 02:48 UTC, KomachiSion approved these changes

2023-08-17 02:48 UTC, merged