[#11035] (PR-2/4) add two String methods...
alibaba/nacos pull request #11065
Opened 2023-08-31 12:27 UTC by IJiaPu

1、移除冗余构建数组操作，其调用的方法为可变参数，例如：void info(String var1, Object... var2);

2、部分常量名下划线分割，语法调整...

3、部分单个参数的Arrays.asList调用修改为Collections.singletonList，减少底层判断

4、避免空指针问题，例如：
	a) TransactionTemplate.execute方法返回值可能为空，添加Boolean.TRUE.equals判断
	b) 数据库查询后结果对象未经判空直接set属性，添加判空处理

5、冗余异常捕捉行为，例如EmptyResultDataAccessException继承IncorrectResultSizeDataAccessException，拦截父类即可

6、移除冗余拆箱，例如Integet.intValue()...

7、Common模块StringUtils添加两个待使用方法

2023-08-31 13:33 UTC, IJiaPu commented
[ISSUE#10908]:
测试用例代码修改

2023-09-01 06:16 UTC, IJiaPu commented
@KomachiSion  夺命无情催！！！！

2023-09-04 05:52 UTC, IJiaPu commented
@KomachiSion 
催！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

2023-09-04 11:53 UTC, IJiaPu commented
翊哥，辛苦Review一下
@KomachiSion

2023-09-05 14:11 UTC, IJiaPu commented
翊哥翊哥你在哪

2023-09-06 09:07 UTC, KomachiSion requested changes

2023-09-06 09:07 UTC, KomachiSion commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
> +            List<ConfigInfo> configInfoList = findConfigInfoByIds(idsStr);
这个没必要改吧

2023-09-06 09:07 UTC, KomachiSion commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java
> +    List<ConfigInfo> findConfigInfoByIds(final String ids);
同上，我理解没必要改

2023-09-06 09:13 UTC, IJiaPu commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
> +            List<ConfigInfo> configInfoList = findConfigInfoByIds(idsStr);
下手的时候我也有些犹豫，缘由是看到id已经是s了。我马上改回来，您别跑啊！！！！很快，马上

2023-09-06 09:34 UTC, KomachiSion requested changes

2023-09-06 09:34 UTC, KomachiSion commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
> -        } catch (EmptyResultDataAccessException e) {
这个异常为什么删掉了

2023-09-06 09:36 UTC, IJiaPu commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
> -        } catch (EmptyResultDataAccessException e) {
删掉的那个和保留的这个是父子关系

2023-09-06 09:36 UTC, IJiaPu commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
> -        } catch (EmptyResultDataAccessException e) {
EmptyResultDataAccessException继承IncorrectResultSizeDataAccessException

2023-09-06 09:39 UTC, IJiaPu commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
> -        } catch (EmptyResultDataAccessException e) {
哥，有说明：
[ISSUE#11035]:
1、移除冗余构建数组操作，其调用的方法为可变参数，例如：void info(String var1, Object... var2);
2、部分常量名下划线分割，语法调整
3、部分单个参数的Arrays.asList调用修改为Collections.singletonList，减少底层判断
4、避免空指针问题，例如：
a) TransactionTemplate.execute方法返回值可能为空，添加Boolean.TRUE.equals判断
b) 数据库查询后结果对象未经判空直接set属性，添加判空处理
5、冗余异常捕捉行为，例如EmptyResultDataAccessException继承IncorrectResultSizeDataAccessException，拦截父类即可
6、移除冗余拆箱，例如Integet.intValue()...
7、Common模块StringUtils添加两个待使用方法

2023-09-06 09:42 UTC, IJiaPu commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
> -        } catch (EmptyResultDataAccessException e) {
> 这个异常为什么删掉了

我寻思既然都可以拦截，且没有分别处理异常，都是返回null，就删掉了

2023-09-06 09:44 UTC, IJiaPu commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
> -        } catch (EmptyResultDataAccessException e) {
您觉得呢

2023-09-06 09:59 UTC, IJiaPu commented
![image](https://github.com/alibaba/nacos/assets/110883801/86b8fcc3-e620-4ac1-82f4-711838a82a8b)
@KomachiSion 您看这个

2023-09-06 10:14 UTC, IJiaPu commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
> -        } catch (EmptyResultDataAccessException e) {
![image](https://github.com/alibaba/nacos/assets/110883801/c9c692b4-d7b0-4c9a-830d-3c9209f28fd3)
如果EmptyResultDataAccessException这个异常像CannotGetJdbcConnectionException一样捕获之后有特殊处理，和IncorrectResultSizeDataAccessException处理方式一样返回空的情况下，二者都可以达到拦截他的目的，所以我认为这个拦截在此刻没有什么意义

2023-09-06 11:05 UTC, IJiaPu commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
> -        } catch (EmptyResultDataAccessException e) {
如果您不赞同，或者认为之后可能不同的异常会有其他逻辑处理，我可以修改回去

2023-09-06 13:59 UTC, IJiaPu commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
> -        } catch (EmptyResultDataAccessException e) {
> 如果是因为还有什么是您认为我没考虑周到的，或者认为之后可能不同的异常会有其他逻辑处理，请您指出，我可以修改回去

2023-09-14 01:41 UTC, KomachiSion approved these changes

2023-09-14 01:42 UTC, merged