Optimize MapperManager
alibaba/nacos pull request #11195
Opened 2023-09-27 04:39 UTC by kang-hl

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-09-27 04:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=11195) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=11195) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=11195) it.</sub>

2023-09-28 02:05 UTC, KomachiSion requested changes
Is necessary to change ConcurrentHashMap in MapperManager?  I think there is no need, the MAPPER_SPI_MAP should only put in init step which is single thread. And even plugin implementation use join, the times is not many and frequent. So I think HashMap is enough and join with synchronized.

And other think is indent problem, please use nacos code style to reformat codes.

2023-09-28 03:31 UTC, kang-hl commented
> Is necessary to change ConcurrentHashMap in MapperManager? I think there is no need, the MAPPER_SPI_MAP should only put in init step which is single thread. And even plugin implementation use join, the times is not many and frequent. So I think HashMap is enough and join with synchronized.
> 
> And other think is indent problem, please use nacos code style to reformat codes.

已修改

2023-10-09 03:28 UTC, KomachiSion requested changes

2023-10-09 03:28 UTC, KomachiSion commented on plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/MapperManager.java
> +    public synchronized void loadInitial() {
这方法有必要锁吗？ 只有初始化的时候单线程执行一次

2023-10-09 03:34 UTC, kang-hl commented on plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/MapperManager.java
> +    public synchronized void loadInitial() {
> 这方法有必要锁吗？ 只有初始化的时候单线程执行一次

那就需要修改为private

2023-10-13 01:54 UTC, KomachiSion requested changes
能帮忙加下UT吗

2023-11-06 07:40 UTC, KomachiSion approved these changes

2023-11-06 07:40 UTC, merged