Nacos客户端磁盘降级需求  issues:11053
alibaba/nacos pull request #11207
Opened 2023-09-28 10:04 UTC by guozongkang

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

https://github.com/alibaba/nacos/issues/11053

## Brief changelog

1.使用磁盘来实现Nacos客户端降级方案
2.可以修改机器上的文件，开启或关闭降级，并且指定需要降级的服务
3.查询机器列表时，优先走降级逻辑

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-09-28 10:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=11207) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=11207) before we can accept your contribution.<br/><hr/>**zongkang.guo1** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=11207) it.</sub>

2023-09-30 15:44 UTC, nkorange requested changes

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +                failoverSwitchEnable = Boolean.TRUE;
直接failoverSwitchEnable=true即可

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +                Map<String, FailoverData> failoverData = failoverDataSource.getFailoverData();
这里似乎只需要将serviceMap和serviceInfoHolder.getServiceInfoMap()就行了？

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +    class FailoverDataWriter extends TimerTask {
根据 @KomachiSion 的建议，把这个writer任务去掉

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverDataSource.java
> +    void saveFailoverData(Map<String, FailoverData> failoverDataMap);
根据 @KomachiSion 的建议，把这个方法去掉

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
> +        if (serviceInfoHolder.isFailoverSwitch()) {
除了getAllInstances，其他的查询实例的方法例如selectInstances也需要保护容灾逻辑

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
> +        if (serviceInfoHolder.isFailoverSwitch()) {
这里还要判断当前查询的服务名是否在容灾开关里

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
> +                serviceInfo.getHosts();
这一行啥意思？

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
> +                    serviceInfo = serviceInfoHolder.getServiceInfo(serviceName, groupName, clusterString);
serviceInfoHolder.getServiceInfo方法里也有判断容灾的逻辑，是否应该移除？

2023-09-30 15:44 UTC, nkorange commented on client/pom.xml
> +        <dependency>
运行mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U 不成功

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
> +                }
这里少了subscribe=false时的处理

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
>          executorService.schedule(() -> {
这个任务也去掉吧

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +        failoverDataSource = new DiskFailoverDataSource(serviceInfoHolder, cacheDir);
这里需要通过反射来获取当前实现类

2023-09-30 15:44 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
>          this.failoverDir = cacheDir + FAILOVER_DIR;
failoverDir不是FailoverReactor的必须字段了

2023-10-07 10:57 UTC, guozongkang commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
> +                serviceInfo.getHosts();
判断，当前服务的服务列表是否在容灾开关里

2023-10-09 01:36 UTC, KomachiSion requested changes

2023-10-09 01:36 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
大量无效改动，请使用nacos code style进行reformat

2023-10-09 01:36 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
同 NacosNamingService.java

2023-10-19 10:07 UTC, nkorange submitted a review, later dismissed

2023-10-23 07:44 UTC, KomachiSion requested changes

2023-10-23 07:44 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
> -        PreInitUtils.asyncPreLoadCostComponent();
为什么删除这个？

2023-10-23 07:44 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
> +    private ServiceInfo getServiceInfo(String serviceName, String groupName, List<String> clusters, boolean subscribe)
能否再优化一下这段逻辑， 看着乱，实在不行把从failover获取的逻辑和普通获取的逻辑分到两个方法里。

2023-10-23 07:44 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +                    if (changed) {
FailOver加了通知机制， 是否会导致在和服务端来回抢通知？

另外，当failover被关闭的时候，是否要触发一次通知，让订阅者感知到服务端推送的数据。

2023-10-23 08:22 UTC, nkorange commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +                    if (changed) {
@KomachiSion 这个地方就是当failover关闭时触发通知，你看125行的if语句

2023-11-15 08:35 UTC, KomachiSion approved these changes
Will be merged after 2.3.0 released.

2023-12-05 02:21 UTC, merged