Optimize ThreadPoolManager
alibaba/nacos pull request #11206
Opened 2023-09-28 08:29 UTC by kang-hl

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-10-09 01:30 UTC, KomachiSion requested changes
建议保持现状

2023-10-09 01:30 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java
> +        Map<String, Set<ExecutorService>> map = resourcesManager.get(namespace);
此优化会导致在并发register和deregister时出现问题。

2023-10-09 03:33 UTC, kang-hl commented on common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java
> +        Map<String, Set<ExecutorService>> map = resourcesManager.get(namespace);
> 此优化会导致在并发register和deregister时出现问题。

已修改

2023-10-13 01:51 UTC, KomachiSion approved these changes

2023-10-13 02:31 UTC, merged