Fix npe when setup ack response in GrpcClient
alibaba/nacos pull request #11210
Opened 2023-09-29 04:40 UTC by Daydreamer-ia

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX
#11209
## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-10-07 07:19 UTC, stone-98 commented
大佬，我有一个疑问哈，目前的逻辑：
- sdk发起连接注册请求
- nacos服务端响应sdk，顺带将能力相关信息响应给sdk
- sdk再发送SetupAckRequest给服务端

第三步，这个ack是否没有必要了？因为对于sdk来说一定要接收到nacos服务端的响应才能认为连接注册成功了，否则应该是需要重新注册，所以这个ack是否有些多余呢？

2023-10-07 10:14 UTC, Daydreamer-ia commented
> 大佬，我有一个疑问哈，目前的逻辑：
> 
> * sdk发起连接注册请求
> * nacos服务端响应sdk，顺带将能力相关信息响应给sdk
> * sdk再发送SetupAckRequest给服务端
> 
> 第三步，这个ack是否没有必要了？因为对于sdk来说一定要接收到nacos服务端的响应才能认为连接注册成功了，否则应该是需要重新注册，所以这个ack是否有些多余呢？

能力表是服务端推送的，按照它的协议模型，是需要一个响应的

2023-10-08 09:48 UTC, stone-98 commented
因为我理解ack的作用就是确保信息传达到接收方，但是目前这个能力表一定是可以发送到接收方的，如果没有那么就是没有连接成功需要重新连接，所以我个人认为sdk -> nacos server的ack就没有必要了。

2023-10-09 01:43 UTC, KomachiSion submitted a review, later dismissed

2023-10-09 01:46 UTC, KomachiSion commented
> 大佬，我有一个疑问哈，目前的逻辑：
> 
> * sdk发起连接注册请求
> * nacos服务端响应sdk，顺带将能力相关信息响应给sdk
> * sdk再发送SetupAckRequest给服务端
> 
> 第三步，这个ack是否没有必要了？因为对于sdk来说一定要接收到nacos服务端的响应才能认为连接注册成功了，否则应该是需要重新注册，所以这个ack是否有些多余呢？

注册连接用的不是rpc方式而是双向流，grpc 双向流是没有ack的， 所以其实sdk并不知道是否注册成功了。

你说的ack是否是sdk收到了能力表的ackRequest之后，再回复给服务端的response？

2023-10-09 01:54 UTC, stone-98 commented
> > 大佬，我有一个疑问哈，目前的逻辑：
> > 
> > * sdk发起连接注册请求
> > * nacos服务端响应sdk，顺带将能力相关信息响应给sdk
> > * sdk再发送SetupAckRequest给服务端
> > 
> > 第三步，这个ack是否没有必要了？因为对于sdk来说一定要接收到nacos服务端的响应才能认为连接注册成功了，否则应该是需要重新注册，所以这个ack是否有些多余呢？
> 
> 注册连接用的不是rpc方式而是双向流，grpc 双向流是没有ack的， 所以其实sdk并不知道是否注册成功了。
> 
> 你说的ack是否是sdk收到了能力表的ackRequest之后，再回复给服务端的response？

对，是这个意思。

2023-10-09 02:09 UTC, KomachiSion commented
如果ack不返回， 服务端默认是成功的话，会导致什么问题吗？

我看PR中 服务端好像已经改成不再等待ack了 @Daydreamer-ia 。

2023-10-09 02:13 UTC, Daydreamer-ia commented
> 如果ack不返回， 服务端默认是成功的话，会导致什么问题吗？
> 
> 我看PR中 服务端好像已经改成不再等待ack了 @Daydreamer-ia 。

那客户端就把服务端当做不支持能力协商处理了

2023-10-09 02:20 UTC, stone-98 commented
@Daydreamer-ia 没太理解，目前能力表和连接注册的响应是当作一个响应返回的，只要是连接注册成功了那么就一定获取到能力表，那么客户端应该知道服务端相关的能力信息了，如果说没获取到能力表那么就等同于连接没有成功建立，那么客户端应该重新进行注册。还是我理解有误嘛。

> > 如果ack不返回， 服务端默认是成功的话，会导致什么问题吗？
> > 我看PR中 服务端好像已经改成不再等待ack了 @Daydreamer-ia 。
> 
> 那客户端就把服务端当做不支持能力协商处理了

2023-10-09 02:23 UTC, Daydreamer-ia commented
> 如果ack不返回， 服务端默认是成功的话，会导致什么问题吗？
> 
> 我看PR中 服务端好像已经改成不再等待ack了 @Daydreamer-ia 。



> > 如果ack不返回， 服务端默认是成功的话，会导致什么问题吗？
> > 我看PR中 服务端好像已经改成不再等待ack了 @Daydreamer-ia 。
> 
> 那客户端就把服务端当做不支持能力协商处理了


> @Daydreamer-ia 没太理解，目前能力表和连接注册的响应是当作一个响应返回的，只要是连接注册成功了那么就一定获取到能力表，那么客户端应该知道服务端相关的能力信息了，如果说没获取到能力表那么就等同于连接没有成功建立，那么客户端应该重新进行注册。还是我理解有误嘛。
> 
> > > 如果ack不返回， 服务端默认是成功的话，会导致什么问题吗？
> > > 我看PR中 服务端好像已经改成不再等待ack了 @Daydreamer-ia 。
> > 
> > 
> > 那客户端就把服务端当做不支持能力协商处

> @Daydreamer-ia 没太理解，目前能力表和连接注册的响应是当作一个响应返回的，只要是连接注册成功了那么就一定获取到能力表，那么客户端应该知道服务端相关的能力信息了，如果说没获取到能力表那么就等同于连接没有成功建立，那么客户端应该重新进行注册。还是我理解有误嘛。
> 
> > > 如果ack不返回， 服务端默认是成功的话，会导致什么问题吗？
> > > 我看PR中 服务端好像已经改成不再等待ack了 @Daydreamer-ia 。
> > 
> > 
> > 那客户端就把服务端当做不支持能力协商处理了

对的。你的理解没错，目前客户端并没有做接收不到的reset处理，只是做简单的类似降级的逻辑，当做不支持能力协商而已，有需要的话，再具体和 @KomachiSion 讨论一下处理方案。

2023-10-09 02:30 UTC, Daydreamer-ia commented
> @Daydreamer-ia 没太理解，目前能力表和连接注册的响应是当作一个响应返回的，只要是连接注册成功了那么就一定获取到能力表，那么客户端应该知道服务端相关的能力信息了，如果说没获取到能力表那么就等同于连接没有成功建立，那么客户端应该重新进行注册。还是我理解有误嘛。
> 
> > > 如果ack不返回， 服务端默认是成功的话，会导致什么问题吗？
> > > 我看PR中 服务端好像已经改成不再等待ack了 @Daydreamer-ia 。
> > 
> > 
> > 那客户端就把服务端当做不支持能力协商处理了

或者就是在connectToServer明确知道支持能力协商情况下，超时没收到能力表时，方法返回null。让他去重连一次

2023-10-09 02:58 UTC, stone-98 commented
如果说connectToServer超时，超时没收到能力表，那么如果它去重连一次，这样的话就如果没有sdk -> nacos的ack，那也没有影响是嘛。

> > @Daydreamer-ia 没太理解，目前能力表和连接注册的响应是当作一个响应返回的，只要是连接注册成功了那么就一定获取到能力表，那么客户端应该知道服务端相关的能力信息了，如果说没获取到能力表那么就等同于连接没有成功建立，那么客户端应该重新进行注册。还是我理解有误嘛。
> > > > 如果ack不返回， 服务端默认是成功的话，会导致什么问题吗？
> > > > 我看PR中 服务端好像已经改成不再等待ack了 @Daydreamer-ia 。
> > > 
> > > 
> > > 那客户端就把服务端当做不支持能力协商处理了
> 
> 或者就是在connectToServer明确知道支持能力协商情况下，超时没收到能力表时，方法返回null。让他去重连一次

2023-10-09 03:16 UTC, KomachiSion commented
其实我觉得有道理， 因为这个能力表的request可以认为是setup的response， 只是带着能力表内容。

没收到就说明setup有问题（连接未成功，服务端有问题未返回，网络问题未返回）直接触发重连。

如果收到了能力表，说明已经注册成功了， 服务端现在也改成用future的方式，不再等wait了，所以其实没什么必要再ack一次。

2023-10-09 03:19 UTC, Daydreamer-ia commented
> 其实我觉得有道理， 因为这个能力表的request可以认为是setup的response， 只是带着能力表内容。
> 
> 没收到就说明setup有问题（连接未成功，服务端有问题未返回，网络问题未返回）直接触发重连。
> 
> 如果收到了能力表，说明已经注册成功了， 服务端现在也改成用future的方式，不再等wait了，所以其实没什么必要再ack一次。

ok，那我晚点把客户端的response移除掉

2023-10-11 01:27 UTC, KomachiSion requested changes

2023-10-11 01:27 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
> +                if (!grpcConn.isAbilitiesSet()) {
这段逻辑可以封装到recAbilityContext里，保持内聚和GrpcClient的逻辑清晰

2023-10-11 16:10 UTC, Daydreamer-ia commented on common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
> +                if (!grpcConn.isAbilitiesSet()) {
done

2023-10-12 01:30 UTC, stone-98 commented
nice~~

2023-10-12 07:37 UTC, KomachiSion requested changes
Only the indent problem need to solved.

2023-10-12 16:29 UTC, Daydreamer-ia commented
> Only the indent problem need to solved.

done

2023-10-13 01:48 UTC, KomachiSion approved these changes

2023-10-13 01:48 UTC, merged