https://github.com/alibaba/nacos/issues/11250
alibaba/nacos pull request #11251
Opened 2023-10-16 10:23 UTC by llm163520

参考Log4J2NacosLogging处理，当location不存在时则不加载

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-10-16 10:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=11251) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=11251) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=11251) it.</sub>

2023-10-16 10:51 UTC, llm163520 commented
![image](https://github.com/alibaba/nacos/assets/22343834/3c99e1a3-f0d5-44e9-9aff-a2ca756aae77)

2023-10-18 06:35 UTC, KomachiSion commented
我没理解这么修改的原因。

2023-10-18 06:51 UTC, llm163520 commented
本地已经有自己日志配置了，不需要加载nacos-logback.xml配置文件呢

2023-10-18 07:25 UTC, llm163520 commented
我理解也并有没强制调整这块，但是从代码的健壮性上来说；指定这个肯定不存在，没必要去执行这块逻辑呢
该处代码有三个问题；
1、存在越界的情况，get(0)？，建议增加判断
2、地址不存在还执行加载，建议增加判断空或不存在则不执行
3、日志版本的设定与获取的判断方式存在问题；这块建议查看下逻辑，应该是使用判断方式有误

2023-10-23 07:17 UTC, KomachiSion commented
所以你的意思是你只是做了重构，没有修改逻辑是吗？

2023-10-23 07:18 UTC, KomachiSion requested changes

2023-10-23 07:18 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java
> +                                throw new RuntimeException(e);
不需要包装异常，要包装至少包装成NacosException

2023-10-23 07:18 UTC, llm163520 commented
可以这么理解的

2023-10-23 07:24 UTC, llm163520 commented on client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java
> +                                throw new RuntimeException(e);
这块异常要往外抛的话；需要抛运行时异常(RuntimeException)，要不就内部输出wran日志

2023-10-23 07:26 UTC, llm163520 commented on client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java
> +                                throw new RuntimeException(e);
已参考之前的异常调整异常抛出内容；
throw new IllegalStateException("Could not initialize Logback Nacos logging from " + location, e);

2023-10-23 08:35 UTC, llm163520 commented
当我本地不存在nacos-logback.xml配置文件时，会触发
`WARN  2023-10-23 10:27:36.933 [-main][*][c.a.n.c.l.NacosLogging]: Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml`
![image](https://github.com/alibaba/nacos/assets/22343834/6b52e381-0fa8-499d-927a-f7cf6cd19307)

2023-10-30 08:27 UTC, KomachiSion commented
> 当我本地不存在nacos-logback.xml配置文件时，会触发 `WARN 2023-10-23 10:27:36.933 [-main][*][c.a.n.c.l.NacosLogging]: Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml` ![image](https://user-images.githubusercontent.com/22343834/277276443-6b52e381-0fa8-499d-927a-f7cf6cd19307.png)

为什么会不存在， nacos-client的jar包里封装了这个文件的

2023-11-02 02:04 UTC, KomachiSion requested changes

2023-11-02 02:04 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java
> +                            //throw new NacosException(NacosException.RESOURCE_NOT_FOUND, e);
不需要的代码无特殊情况直接删除，不需要注视掉

2023-11-02 02:05 UTC, KomachiSion commented
> > > 当我本地不存在nacos-logback.xml配置文件时，会触发 `WARN 2023-10-23 10:27:36.933 [-main][*][c.a.n.c.l.NacosLogging]: Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml` ![image](https://user-images.githubusercontent.com/22343834/277276443-6b52e381-0fa8-499d-927a-f7cf6cd19307.png)
> > 
> > 
> > 为什么会不存在， nacos-client的jar包里封装了这个文件的
> 
> 估摸着读取的方式不对，通过日志可以看出实际并未加载到

有空可以研究下，为什么没读取到，感觉不太应该。

2023-11-02 02:08 UTC, llm163520 commented on client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java
> +                            //throw new NacosException(NacosException.RESOURCE_NOT_FOUND, e);
好的，已处理并提交

2023-11-15 08:24 UTC, KomachiSion requested changes

2023-11-15 08:24 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java
> +
Please don't change the indent, please use nacos code style to reformat code.

2023-11-20 06:40 UTC, KomachiSion commented
@llm163520 , Your PR change the indents which is not need change and no relative with the issue, Please fix it. 

I see other problem all has been fixed. Only the indents problem need fix.

2023-11-20 16:23 UTC, llm163520 commented
> @llm163520 , Your PR change the indents which is not need change and no relative with the issue, Please fix it.
> 
> I see other problem all has been fixed. Only the indents problem need fix.

咱们代码格式化模板是用的？

2023-11-20 16:29 UTC, llm163520 commented
> > @llm163520 , Your PR change the indents which is not need change and no relative with the issue, Please fix it.
> > I see other problem all has been fixed. Only the indents problem need fix.
> 
> 咱们代码格式化模板是用的？

忽略，已按模板格式化并重新提交

2023-11-24 09:01 UTC, KomachiSion approved these changes

2023-11-24 09:01 UTC, merged