add startup conditions
alibaba/nacos pull request #11305
Opened 2023-10-30 07:24 UTC by huangkemingyyds

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change
https://github.com/alibaba/nacos/issues/11304
XXXXX

2023-10-30 08:06 UTC, KomachiSion requested changes
UT should not start spring context.

2023-10-30 08:42 UTC, KomachiSion commented
我看了一下错误， 可能是UT顺序问题导致的， 解决方法应该是mockEnv，而不是去启动spring context。

可以参考DistroModuleStateBuilderTest等也依赖Env的UT是如何做的。

另外，为了保证不影响其他的UT，最好在After中清理掉这个TlsConfig的instance

2023-10-30 08:49 UTC, huangkemingyyds commented
好，&nbsp; 那后面我参考DistroModuleStateBuilderTest&nbsp; 做出一些响应的修改， 多谢大佬将问题指出。&nbsp;


。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2023年10月30日(星期一) 下午4:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] add startup conditions (PR #11305)





 
我看了一下错误， 可能是UT顺序问题导致的， 解决方法应该是mockEnv，而不是去启动spring context。
 
可以参考DistroModuleStateBuilderTest等也依赖Env的UT是如何做的。
 
另外，为了保证不影响其他的UT，最好在After中清理掉这个TlsConfig的instance
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-11-01 03:20 UTC, KomachiSion approved these changes

2023-11-01 03:20 UTC, merged