Strip group name prefix of instance service name before sending register or deregister request
alibaba/nacos pull request #11342
Opened 2023-11-07 08:18 UTC by zrlw

## What is the purpose of the change
fix #11298

## Brief changelog
* check and strip group name prefix of instance service name at register and deregister functions of NacosNamingService.java
* only compare ip and port at getRetainInstance function of NamingGrpcClientProxy.java

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-11-09 07:45 UTC, KomachiSion requested changes
看着像是两件事，是不是应该提交2个PR。

另外UT覆盖率变低了， 看下是否给新的修改补下单测。

2023-11-09 13:58 UTC, zrlw commented
> 看着像是两件事，是不是应该提交2个PR。
> 
> 另外UT覆盖率变低了， 看下是否给新的修改补下单测。

ok，客户端比较redotask缓存里的实例是否为解除注册实例的处理逻辑也有问题，我另外单独提一个PR。

2023-11-10 02:22 UTC, zrlw commented
单元测试coverage结果显示修订内容已100%覆盖（绿色行表示单元测试已覆盖），不清楚Codecov统计的diff coverage为什么会少，是把修改的注释行也算进去了么。
![image](https://github.com/alibaba/nacos/assets/40652892/16857df7-31bd-4fcf-9919-525135c1518b)

2023-11-11 04:15 UTC, zrlw commented
看来仅仅增加单元测试代码并不会改变Codecov Report结果，还要去改一下执行代码，能借鉴dubbo社区的做法么，提交测试代码时同样触发代码检查。 @KomachiSion

2023-11-15 08:20 UTC, KomachiSion reviewed
关于这个PR，其实我有个内容想讨论一下， 就是是否只比较ip和port。

因为元数据内容也是很关键的。是否需要比较元数据内容。

或者有两个模式，严格模式和简略模式，一个要完全一致，一个只需要ip port一致。

2023-11-15 10:29 UTC, zrlw commented
getRetainInstance方法用于判定redoTask缓存的实例对象是不是批量注销请求的临时实例，仅用于批量删除临时实例。
假设判定条件加上元数据比较，万一注销某个ip和port的服务实例时，发现redoTask缓存的服务实例虽然ip和port匹配注销请求，但是元数据不一致，从而注销不了，这样的结果也不能令人满意吧，毕竟注册中心控制台有实例元数据的编辑按钮，万一有人修改了就麻烦了，但ip和port不会变化，同一个ip和port也不应该注册两个实例。

2023-11-17 06:10 UTC, KomachiSion commented
如果只是针对批量注册的实例的话， 是不是更应该用准确匹配， 因为batchRegister接口是没有注册ip port的，是需要传入Instance的

2023-11-17 08:24 UTC, zrlw commented
批量接口我们主要是给nacos-sync跨nacos集群同步实例用的（PR已提交），批量同步到目标集群时，批量注册请求的instance对象在构建时都有设置ip和port，需要下线目标集群里指定源集群指定的服务实例时，nacos-sync要从目标集群查询获取该服务名所有instance，从里面根据instance元数据里的源集群标识（nacos-sync注册到目标集群时添加的标识）选出来自源集群的所有实例，然后调用批量注销接口，查询获得的这些instance对象的元数据可能和当初批量注册请求时的instance元数据不一致，注册成功之后在nacos控制台上可以手工修改服务实例的元数据。

2023-11-20 06:28 UTC, KomachiSion commented
> 批量接口我们主要是给nacos-sync跨nacos集群同步实例用的（PR已提交），批量同步到目标集群时，批量注册请求的instance对象在构建时都有设置ip和port，需要下线目标集群里指定源集群指定的服务实例时，nacos-sync要从目标集群查询获取该服务名所有instance，从里面根据instance元数据里的源集群标识（nacos-sync注册到目标集群时添加的标识）选出来自源集群的所有实例，然后调用批量注销接口，查询获得的这些instance对象的元数据可能和当初批量注册请求时的instance元数据不一致，注册成功之后在nacos控制台上可以手工修改服务实例的元数据。

dubbo3 也会使用批量注册的功能，可能需要问一下这种场景会不会有问题，dubbo3可能会使用元数据来区分协议类型（但端口多协议功能）如果只使用ip port，担心会一下把所有ip port一致，但元数据不一致的都删掉。

2023-11-20 06:28 UTC, KomachiSion commented
> > 批量接口我们主要是给nacos-sync跨nacos集群同步实例用的（PR已提交），批量同步到目标集群时，批量注册请求的instance对象在构建时都有设置ip和port，需要下线目标集群里指定源集群指定的服务实例时，nacos-sync要从目标集群查询获取该服务名所有instance，从里面根据instance元数据里的源集群标识（nacos-sync注册到目标集群时添加的标识）选出来自源集群的所有实例，然后调用批量注销接口，查询获得的这些instance对象的元数据可能和当初批量注册请求时的instance元数据不一致，注册成功之后在nacos控制台上可以手工修改服务实例的元数据。
> 
> dubbo3 也会使用批量注册的功能，可能需要问一下这种场景会不会有问题，dubbo3可能会使用元数据来区分协议类型（单端口多协议功能）如果只使用ip port，担心会一下把所有ip port一致，但元数据不一致的都删掉。

2023-11-20 07:20 UTC, zrlw commented
![image](https://github.com/alibaba/nacos/assets/40652892/72e80357-2945-4fee-8a69-fc3d86ee1692)
dubbo3单端口多协议应该只是一个服务实例提供多个服务协议，我们同一端口上配了triple和dubbo两种协议，nacos注册中心每个ip和port也是只有一个实例，只是元数据包含了两个协议，如果增减协议，应该要修改应用配置文件重启dubbo3应用才行。

2023-11-24 08:25 UTC, KomachiSion approved these changes

2023-11-24 08:25 UTC, merged