[ISSUE #11343] Simplified validation logic
alibaba/nacos pull request #11345
Opened 2023-11-07 14:29 UTC by 985492783

Simplified validation logic and fix bug.
优化点
1. Manger和多个filter过度设计。
2. 通过拼接url+method+module，设计繁琐，且是有问题的。
3. 通过Extractor中注册url来定位需要参数校验的请求，不合理。

修改点
1. 定义`@ParamChecker.Checker`注解。将控制权转给controller，类似`@Secured`注解定义资源类型。
2. 去除Manger和多个filter过度设计，用一个filter代替。
3. filter通过ControllerMethodsCache和request定位类和方法，从方法中找Checker注解，找不到再去类中找，找不到不需要校验参数，找到了根据具体的Checker属性取出对应的Extractor并做后续处理。

---
Optimisation points
1. Manger and multiple filters are overdesigned.
2. by splicing url+method+module, the design is cumbersome and is problematic.
3. By registering url in Extractor to locate the request that needs parameter checking, it is unreasonable.

Modification points
1. Define `@ParamChecker.Checker` annotation. Transfer control to controller, similar to `@Secured` annotation to define resource type.
2. remove Manger and multiple filter overdesign, replace with one filter.
3. filter through the ControllerMethodsCache and request to locate the class and method, from the method to find Checker annotations, can not find and then go to the class to find , can not find the parameters do not need to check , found according to the specific Checker attributes to take out the corresponding Extractor and do the subsequent processing.

2023-11-07 14:41 UTC, 985492783 commented
link #11343

2023-11-09 07:42 UTC, KomachiSion requested changes
一个问题

注解里的参数为checker，但是指定的是参数提取用的extractor， 是不是改下名字。

2023-11-09 09:49 UTC, 985492783 commented
> 一个问题
> 
> 注解里的参数为checker，但是指定的是参数提取用的extractor， 是不是改下名字。

done

2023-11-15 07:24 UTC, KomachiSion approved these changes

2023-11-15 07:25 UTC, merged