Fix NPE
alibaba/nacos pull request #11385
Opened 2023-11-16 06:31 UTC by 985492783

fix NPE

2023-11-16 06:33 UTC, 985492783 commented
linked #11343

2023-11-17 06:01 UTC, KomachiSion requested changes

2023-11-17 06:01 UTC, KomachiSion commented on core/src/main/java/com/alibaba/nacos/core/paramcheck/ParamCheckerFilter.java
> +        } catch (Exception e) {
这会不会导致check被绕过？ 后续升级之后不再兼容。

2023-11-17 07:28 UTC, 985492783 commented on core/src/main/java/com/alibaba/nacos/core/paramcheck/ParamCheckerFilter.java
> +        } catch (Exception e) {
> 这会不会导致check被绕过？ 后续升级之后不再兼容。

解决了，暂时还是把别的异常抛出去

2023-11-17 09:11 UTC, KomachiSion approved these changes

2023-11-17 09:11 UTC, merged