support metric for grpc server request
alibaba/nacos pull request #11427
Opened 2023-11-24 09:01 UTC by Daydreamer-ia

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change
#10846 
XXXXX
```
# HELP grpc_server_requests_seconds_max  
# TYPE grpc_server_requests_seconds_max gauge
grpc_server_requests_seconds_max{errorCode="0",module="config",requestClass="ConfigPublishRequest",success="true",throwableClass="None",} 0.136027
grpc_server_requests_seconds_max{errorCode="0",module="config",requestClass="ConfigRemoveRequest",success="true",throwableClass="None",} 0.0671147
grpc_server_requests_seconds_max{errorCode="0",module="naming",requestClass="SubscribeServiceRequest",success="true",throwableClass="None",} 0.0139512
grpc_server_requests_seconds_max{errorCode="0",module="config",requestClass="ConfigQueryRequest",success="true",throwableClass="None",} 0.0061379
grpc_server_requests_seconds_max{errorCode="0",module="naming",requestClass="InstanceRequest",success="true",throwableClass="None",} 0.0185975
grpc_server_requests_seconds_max{errorCode="0",module="internal",requestClass="HealthCheckRequest",success="true",throwableClass="None",} 0.0014617
grpc_server_requests_seconds_max{errorCode="300",module="config",requestClass="ConfigQueryRequest",success="true",throwableClass="None",} 0.0552467
grpc_server_requests_seconds_max{errorCode="0",module="config",requestClass="ConfigBatchListenRequest",success="true",throwableClass="None",} 0.0155547
grpc_server_requests_seconds_max{errorCode="0",module="unknown",requestClass="ServerCheckRequest",success="true",throwableClass="None",} 0.1011771
# HELP grpc_server_requests_seconds  
# TYPE grpc_server_requests_seconds summary
grpc_server_requests_seconds_count{errorCode="0",module="config",requestClass="ConfigPublishRequest",success="true",throwableClass="None",} 1.0
grpc_server_requests_seconds_sum{errorCode="0",module="config",requestClass="ConfigPublishRequest",success="true",throwableClass="None",} 0.136027
grpc_server_requests_seconds_count{errorCode="0",module="config",requestClass="ConfigRemoveRequest",success="true",throwableClass="None",} 1.0
grpc_server_requests_seconds_sum{errorCode="0",module="config",requestClass="ConfigRemoveRequest",success="true",throwableClass="None",} 0.0671147
grpc_server_requests_seconds_count{errorCode="0",module="naming",requestClass="SubscribeServiceRequest",success="true",throwableClass="None",} 1.0
grpc_server_requests_seconds_sum{errorCode="0",module="naming",requestClass="SubscribeServiceRequest",success="true",throwableClass="None",} 0.0139512
grpc_server_requests_seconds_count{errorCode="0",module="config",requestClass="ConfigQueryRequest",success="true",throwableClass="None",} 2.0
grpc_server_requests_seconds_sum{errorCode="0",module="config",requestClass="ConfigQueryRequest",success="true",throwableClass="None",} 0.0096706
grpc_server_requests_seconds_count{errorCode="0",module="naming",requestClass="InstanceRequest",success="true",throwableClass="None",} 2.0
grpc_server_requests_seconds_sum{errorCode="0",module="naming",requestClass="InstanceRequest",success="true",throwableClass="None",} 0.0247077
grpc_server_requests_seconds_count{errorCode="0",module="internal",requestClass="HealthCheckRequest",success="true",throwableClass="None",} 10.0
grpc_server_requests_seconds_sum{errorCode="0",module="internal",requestClass="HealthCheckRequest",success="true",throwableClass="None",} 0.0065304
grpc_server_requests_seconds_count{errorCode="300",module="config",requestClass="ConfigQueryRequest",success="true",throwableClass="None",} 3.0
grpc_server_requests_seconds_sum{errorCode="300",module="config",requestClass="ConfigQueryRequest",success="true",throwableClass="None",} 0.058394
grpc_server_requests_seconds_count{errorCode="0",module="config",requestClass="ConfigBatchListenRequest",success="true",throwableClass="None",} 5.0
grpc_server_requests_seconds_sum{errorCode="0",module="config",requestClass="ConfigBatchListenRequest",success="true",throwableClass="None",} 0.0218914
grpc_server_requests_seconds_count{errorCode="0",module="unknown",requestClass="ServerCheckRequest",success="true",throwableClass="None",} 2.0
grpc_server_requests_seconds_sum{errorCode="0",module="unknown",requestClass="ServerCheckRequest",success="true",throwableClass="None",} 0.1015446
```
## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-12-15 07:44 UTC, KomachiSion approved these changes

2023-12-15 07:48 UTC, KomachiSion requested changes

2023-12-15 07:48 UTC, KomachiSion commented on core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
> +                MetricsMonitor.recordGrpcRequestEvent(type, false,
198-199 和 204-205 是否能提取到if elae外面？看起来内容是一致的

2023-12-19 06:38 UTC, Daydreamer-ia commented on core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
> +                MetricsMonitor.recordGrpcRequestEvent(type, false,
198 - 199是 OVER_THRESHOLD 的情况，请求处理是失败的，而 204 - 205是正常的。两个的参数有一个不一样

2023-12-26 03:00 UTC, KomachiSion requested changes

2023-12-27 06:07 UTC, Daydreamer-ia commented on core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
> +                MetricsMonitor.recordGrpcRequestEvent(type, false,
done

2023-12-29 06:08 UTC, KomachiSion approved these changes

2023-12-29 06:08 UTC, merged