feat(#11393): support register or deregister persistent instance by grpc
alibaba/nacos pull request #11430
Opened 2023-11-24 21:13 UTC by Bo-Qiu

## What is the purpose of the change

Support register or deregister persistent instance by grpc.

## Brief changelog

1. Add PersistentInstanceRequest in 2.3.0 server and client.

2. Add ability tag like supportPersistentInstanceByGrpc in AbilityTables of 2.3.0 server and client.

3. when using 2.3.0 client and later version, it can judge whether use grpc request to register persistent instance, if server supported, use grpc request, otherwise use old way to adapt it.

2023-11-25 04:41 UTC, Daydreamer-ia commented on api/src/main/java/com/alibaba/nacos/api/ability/constant/AbilityKey.java
> +    SUPPORT_PERSISTENT_INSTANCE_BY_GRPC("supportPersistentInstanceByGrpc",
`key` 的命名上最好可以看出是哪个端的，类似里面给出的那三个例子。带 `SERER_` 前缀

2023-11-25 05:22 UTC, Bo-Qiu commented on api/src/main/java/com/alibaba/nacos/api/ability/constant/AbilityKey.java
> +    SUPPORT_PERSISTENT_INSTANCE_BY_GRPC("supportPersistentInstanceByGrpc",
> 枚举 `key` 的命名上最好可以看出是哪个端的，类似里面给出的那三个例子。带 `SERVER_` 前缀

稳妥，我调整下，感谢老哥

2023-11-27 01:30 UTC, KomachiSion requested changes

2023-11-27 01:30 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/ability/constant/AbilityKey.java
> +
indent don't need to change

2023-11-27 01:30 UTC, KomachiSion commented on api/src/test/java/com/alibaba/nacos/api/ability/register/impl/ServerAbilitiesTest.java
> +
indent don't need to change

2023-11-27 01:30 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java
> +    boolean isAbilitySupportedByServer(AbilityKey abilityKey);
I think the method not need define in interface. It's a gprc client proxy special method.

2023-11-27 01:30 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/PersistentInstanceRequestHandler.java
> +        clientOperationService.registerInstance(service, request.getInstance(), meta.getConnectionId());
clientId should same with register persistent by http. like ip:port#false

2023-11-27 11:47 UTC, KomachiSion approved these changes

2023-11-27 11:47 UTC, merged