[ISSUE #11612] Unified use of `NameThreadFactory` to create thread pools
alibaba/nacos pull request #11613
Opened 2024-01-09 02:57 UTC by zhongqishang

## What is the purpose of the change

Fix #11612

## Brief changelog

Unified use of `NameThreadFactory` to create thread pools.

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-01-09 02:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=11613) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=11613) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=11613) it.</sub>

2024-01-09 06:15 UTC, karsonto commented
LGTM

2024-01-09 06:16 UTC, karsonto approved these changes

2024-01-11 07:46 UTC, KomachiSion requested changes
this thread is fixed size and only one thread for each client.
your pr fix can't fix this problem, the NameThreadFactory id generator from 0 for each new NameThreadFactory.

2024-01-11 08:53 UTC, zhongqishang commented
> this thread is fixed size and only one thread for each client. your pr fix can't fix this problem, the NameThreadFactory id generator from 0 for each new NameThreadFactory.

@KomachiSion Thanks for your feeback.

Main fix is for `com.alibaba.nacos.client.Worker`, it is not only one thread.
Others fix is to used unified style.

```
        int count = ThreadUtils.getSuitableThreadCount(THREAD_MULTIPLE);
        ScheduledExecutorService executorService = Executors.newScheduledThreadPool(Math.max(count, MIN_THREAD_NUM),
                r -> {
                    Thread t = new Thread(r);
                    t.setName("com.alibaba.nacos.client.Worker");
                    t.setDaemon(true);
                    return t;
                });
```

2024-01-11 09:08 UTC, zhongqishang commented
BTW, Only one thead with id is aslo make sense.
1. If I create mutiple client, I will see the mutiple the name of `xxxx.[0]` thread.
2. Unified coding style. :D

2024-01-11 09:09 UTC, KomachiSion commented
> BTW, Only one thead with id is aslo make sense.
> 
> 1. If I create mutiple client, I will see the mutiple the name of `xxxx.[0]` thread. You can know that there are multiple thread pools without looking at the source code.
> 2. Unified coding style. :D

OK

2024-01-17 07:47 UTC, KomachiSion approved these changes

2024-01-17 07:47 UTC, merged