feat(#11752): The contentPath of AddressServerUrl is not flexible.
alibaba/nacos pull request #11754
Opened 2024-02-19 11:44 UTC by Bo-Qiu

## What is the purpose of the change

feat(#11752 ): The contentPath of AddressServerUrl is not flexible.

## Brief changelog

feat(#11752 ): The contentPath of AddressServerUrl is not flexible.

## Verifying this change

feat(#11752 ): The contentPath of AddressServerUrl is not flexible.

2024-02-20 02:41 UTC, KomachiSion requested changes

2024-02-20 02:41 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
> +        Properties properties = new Properties();
这个移下来不合理， endpoint有可能并非通过参数直接传入，可能通过环境变量等传入。需要保留原来的逻辑。

2024-02-21 02:40 UTC, Bo-Qiu commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
> +        Properties properties = new Properties();
原代码是判断的方法入参endpoint是否为空，所以调整顺序没影响。 我理解你是期望这儿判断this.endpoint是否为空吗？
<img width="875" alt="image" src="https://github.com/alibaba/nacos/assets/46370663/6e323a20-67c1-42fd-aa04-1829c5a3fce1">

2024-02-22 03:27 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
> +        Properties properties = new Properties();
OK

2024-02-27 01:25 UTC, KomachiSion requested changes
How about the ServerListManager in client/naming/package?

2024-02-29 02:51 UTC, Bo-Qiu commented
> How about the ServerListManager in client/naming/package?

I changed it, please review it again, thx!

2024-03-07 03:39 UTC, KomachiSion approved these changes

2024-03-07 03:39 UTC, merged