fix: CVE-2024-22243 Upgrade Spring Web to 5.3.32
alibaba/nacos pull request #11833
Opened 2024-03-15 01:01 UTC by cxhello

## What is the purpose of the change

Closes #11811

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-03-15 05:59 UTC, KomachiSion requested changes
这样的修复方式是否正确？ 

我理解spring-web应该是基于spring-boot引入的，看下是否能通过升级spring-boot版本来解决？

2024-03-20 02:52 UTC, KomachiSion commented
> 是由 Spring Boot 引入，目前我看使用的版本是2.7.18，是Spring Boot 2 的最后一个版本。如果升级只能升级为3.0，改动应该比较大。所以我在依赖管理中重新定义了 Spring Web 的版本。
> 
> https://docs.spring.io/spring-boot/docs/2.7.18/reference/html/dependency-versions.html#appendix.dependency-versions
> 
> 我理解没声明 spring-web 版本时会使用 Spring Boot 依赖的版本，如果声明了版本会使用自己声明的。

可以用mvn dependency:tree 看一下修改的是否生效，如果生效的话就这么修改一下。

2024-03-20 03:31 UTC, cxhello commented
@KomachiSion 

<img width="551" alt="image" src="https://github.com/alibaba/nacos/assets/49056040/ec96cbbd-3ee5-4a5a-a34f-7f6671ece346">

2024-03-25 09:31 UTC, KomachiSion approved these changes

2024-04-01 08:48 UTC, merged

2024-04-01 13:21 UTC, cxhello commented
@ICE-GB 恩，确实存在这种现象。不过这也是没法避免的。需要开发人员仔细一点。就像https://github.com/alibaba/nacos/issues/11904 也存在漏洞，不升级 SpringBoot 的话也是要单独升级 Spring Security。

2024-04-08 03:10 UTC, cxhello commented
@ICE-GB 已采用你说的方式提了PR，代码已被社区合并。https://github.com/alibaba/nacos/pull/11914