[ISSUE #11957] Remove default password
alibaba/nacos pull request #11991
Opened 2024-04-21 05:15 UTC by godhth

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

https://github.com/alibaba/nacos/issues/11957

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-04-22 02:32 UTC, KomachiSion requested changes
1. 好像测试有大规模的失败，建议排查一下原因
2. 关于如果没有GLOBAL_ADMIN_ROLE用户的时候， 应该在更前面的地方判断，并且直接弹出，权限校验部分应该维持现状，就是没有user或没有权限的报错。

2024-04-23 02:30 UTC, KomachiSion commented
测试用例已修复， 请同步develop分支后重新提交

2024-04-23 12:43 UTC, godhth commented
done

2024-04-24 07:51 UTC, KomachiSion requested changes
整体的方案我觉得可以重新考虑一下。

我觉得只需要判断一下是否数据库中有admin用户即可， 并且记录这个状态，然后暴露状态；

此时应该有以下几个行为：
1. 控制台通过读取这个状态，当没有初始化admin用户时， 转跳到一个单独的页面，来创建admin用户（具体可以讨论，是用户密码都自定义，还是用户名是nacos，密码让用户自定义）。
2. 提供一个新API，对于不方便使用控制台的用户，通过调用这个API来设置nacos用户的密码；该接口只能不带任何身份信息调用一次，如果已经存在admin级别的用户，这个接口应该拒绝访问。
3. 其他的正常接口访问，不需要额外判断逻辑， 走正常鉴权的时候因为没有用户信息，正常报错即可。

2024-04-24 07:51 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/common/Constants.java
> +    public static final String GLOBAL_TMP_ADMIN = "globalTmpAdmin";
这个tmp admin 是什么作用？

2024-04-24 08:50 UTC, godhth commented on api/src/main/java/com/alibaba/nacos/api/common/Constants.java
> +    public static final String GLOBAL_TMP_ADMIN = "globalTmpAdmin";
临时用户，目前这个方案是有个临时用户的中间状态。用户可以通过这个临时管理员用户去初始化admin用户，或者直接使用。
可能是有点多余了，这个临时用户，我再考虑下。

2024-04-29 02:03 UTC, KomachiSion approved these changes

2024-04-29 02:03 UTC, KomachiSion approved these changes

2024-04-29 02:04 UTC, merged