[ISSUE #11967] Can not aquire the specific config
alibaba/nacos pull request #12025
Opened 2024-04-25 06:16 UTC by syshenyao

BUG：https://github.com/alibaba/nacos/issues/11967%EF%BC%8C details refer： https://github.com/alibaba/nacos/issues/10119 & https://github.com/alibaba/nacos/pull/10101

2024-04-29 01:52 UTC, KomachiSion commented
Error:  Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project nacos-config: Too many files with unapproved license: 1 See RAT report in: /home/runner/work/nacos/nacos/config/target/rat.txt -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project nacos-config: Too many files with unapproved license: 1 See RAT report in: /home/runner/work/nacos/nacos/config/target/rat.txt

One file new has no copyright, please add copyright to file header.

2024-04-29 06:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=12025) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=12025) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: syshenyao<br/>:x: yao.shen@hstong.com<br/><hr/>**yao.shen@hstong.com** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=12025) it.</sub>

2024-04-29 06:25 UTC, syshenyao commented
> Error: Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project nacos-config: Too many files with unapproved license: 1 See RAT report in: /home/runner/work/nacos/nacos/config/target/rat.txt -> [Help 1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project nacos-config: Too many files with unapproved license: 1 See RAT report in: /home/runner/work/nacos/nacos/config/target/rat.txt
> 
> One file new has no copyright, please add copyright to file header.

Okay

2024-05-06 02:42 UTC, KomachiSion approved these changes

2024-05-06 03:48 UTC, KomachiSion requested changes
The test case seems not pass

before start run test with encoder, might set the os system as window to triggle encoder and reset the os system after case finished.

2024-05-08 01:52 UTC, syshenyao commented
> The test case seems not pass
> 
> before start run test with encoder, might set the os system as window to triggle encoder and reset the os system after case finished.

I tried modifying it, but it had no effect.

2024-05-10 06:37 UTC, KomachiSion commented
> > The test case seems not pass
> > before start run test with encoder, might set the os system as window to triggle encoder and reset the os system after case finished.
> 
> I tried modifying it, but it had no effect.

I think you should find out the problem, why it is not effect and fix it.

2024-05-11 11:55 UTC, syshenyao commented
> > > The test case seems not pass
> > > before start run test with encoder, might set the os system as window to triggle encoder and reset the os system after case finished.
> > 
> > 
> > I tried modifying it, but it had no effect.
> 
> I think you should find out the problem, why it is not effect and fix it.

done

2024-05-15 03:04 UTC, KomachiSion approved these changes

2024-05-15 03:04 UTC, merged