[ISSUE#12022] Fix nacos datasource plugin ClassCastException bug (#12…
alibaba/nacos pull request #12031
Opened 2024-04-25 15:50 UTC by mikolls

## What is the purpose of the change

Fix nacos datasource plugin ClassCastException bug [https://github.com/alibaba/nacos/issues/12022](url)

## Brief changelog

Modify the clazz.getInterfaces() method in com.alibaba.nacos.plugin.datasource.proxy.MapperProxy#createProxy so that clazz can obtain the correct Class<?>[] interface

## Verifying this change

After repair, nacos can run normally without ClassCastException and does not affect the original mysql mapper.

postgersql：
![image](https://github.com/alibaba/nacos/assets/41845795/cbcaa1ba-f609-48a0-992a-c4a31ed2004e)

mysql：
![image](https://github.com/alibaba/nacos/assets/41845795/6308d757-2b34-47a6-903c-2162ee6265d9)

2024-04-29 01:48 UTC, KomachiSion requested changes

2024-04-29 01:48 UTC, KomachiSion commented on plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/proxy/MapperProxy.java
> +        while (clazz.getInterfaces().length == 0) {
这个逻辑是否也有风险？ 现在这个实现的逻辑是找到第一个interfaces不为0的类/或父类， 如果插件实现的时候自己定义了一个接口，然后那个接口也不是Mapper的子类或接口，应该也会出现ClassCase异常。

看下是否把所有的这个传入的mapper的所有interface都获取出来，然后让Proxy代理上？

如果没必要的话， 只需要找到实现了Mapper的对应class，然后再获取这个类的interfaces来动态代理。

2024-04-30 10:11 UTC, mikolls commented on plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/proxy/MapperProxy.java
> +        while (clazz.getInterfaces().length == 0) {
确实，这点是我考虑不周了，如果插件在实现的时候有自己的接口，这里也会报错。

拿实现了Mapper的对应class的interfaces，目前看来足够使用了，nacos中调用findMapper()也用不到插件自己实现的接口。

2024-05-06 02:39 UTC, KomachiSion submitted a review, later dismissed

2024-05-06 02:41 UTC, KomachiSion commented
CI seems can't pass， please check and fix them

2024-05-15 02:56 UTC, KomachiSion approved these changes

2024-05-15 02:56 UTC, merged