[issue ##12043] Feat junit5 refact client
alibaba/nacos pull request #12044
Opened 2024-04-29 03:26 UTC by shalk

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

#12043 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-05-06 02:38 UTC, KomachiSion requested changes
测试用例方法命名需要以test开头。

2024-05-06 02:38 UTC, KomachiSion commented on client/src/test/java/com/alibaba/nacos/client/ability/AbilityTest.java
> +    void receive() throws Exception {
测试用例需要以test开头

2024-05-06 02:40 UTC, KomachiSion commented
另外 问一下改成junit5之后， 使用方法必须改成现在这样吗？

2024-05-06 07:55 UTC, shalk commented
> 另外 问一下改成junit5之后， 使用方法必须改成现在这样吗？

When i use some plugins to massive refactor, it remove prefix `test` from test method automatic. Because this is best pratise.

the reason can ref [this]( https://thejavaguy.org/posts/011-dont-prefix-junit-tests-with-the-word-test/

The convention prefix with `test` is `must be` for junit3,  the prefix is not need any more,  from junit4 and junit5 ,we don't neccessaly write it. maybe some early developers follow these junit3 rule.

When we use IDEA to generate test class,when we chose junit3, the prefix will be added, when chose junit4/junit5, the prefix will be not added.

2024-05-06 08:00 UTC, shalk commented on client/src/test/java/com/alibaba/nacos/client/ability/AbilityTest.java
> +    void receive() throws Exception {
`prefix` is only need for junit3

2024-05-10 06:35 UTC, KomachiSion requested changes

2024-05-10 06:35 UTC, KomachiSion commented on client/src/test/java/com/alibaba/nacos/client/ability/AbilityTest.java
> +    void receive() throws Exception {
是的， 我的意思是nacos的测试用例希望以test开头，来更准确的表达测试方法的语意，你可以认为是一个规范。

2024-05-10 10:00 UTC, shalk commented
@KomachiSion  ok, i  try to keep the method name not change this time.

2024-05-11 02:22 UTC, shalk commented on client/src/test/java/com/alibaba/nacos/client/ability/AbilityTest.java
> +    void receive() throws Exception {
done

2024-05-15 02:56 UTC, KomachiSion requested changes

2024-05-15 02:56 UTC, KomachiSion commented on client/src/test/java/com/alibaba/nacos/client/ability/AbilityTest.java
> +
和另外一个pr相似的问题， 不要修改空行缩进， nacos-code-style里面有设置。

2024-05-15 03:26 UTC, shalk commented on client/src/test/java/com/alibaba/nacos/client/ability/AbilityTest.java
> +
It look like mvn checkstyle:check pass.   IDEA  can not format it  back...

2024-05-15 03:27 UTC, shalk commented on client/src/test/java/com/alibaba/nacos/client/ability/AbilityTest.java
> +
Is there some way to fast formt it  back ?

2024-05-15 03:33 UTC, shalk commented on client/src/test/java/com/alibaba/nacos/client/ability/AbilityTest.java
> +
done

2024-05-16 02:54 UTC, KomachiSion approved these changes

2024-05-24 02:15 UTC, KomachiSion approved these changes

2024-05-24 02:15 UTC, merged