[ISSUE #11957] AuthModule add admin exist
alibaba/nacos pull request #12066
Opened 2024-05-07 11:05 UTC by godhth

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

https://github.com/alibaba/nacos/issues/11957

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-05-10 06:32 UTC, KomachiSion requested changes

2024-05-10 06:32 UTC, KomachiSion commented on auth/src/main/java/com/alibaba/nacos/auth/config/AuthModuleStateBuilder.java
> +        result.newState(AUTH_ADMIN_EXIST, authConfigs.isHasGlobalAdminRole());
建议改一下名字， 比如改成auth_admin_request, 或者auth_need_admin 因为插件实现不一定需要admin

2024-05-10 06:32 UTC, KomachiSion commented on auth/src/main/java/com/alibaba/nacos/auth/config/AuthConfigs.java
> +    private boolean hasGlobalAdminRole = false;
这个默认值是不是不需要制定，本身就是false？

2024-05-15 02:41 UTC, KomachiSion requested changes

2024-05-15 02:41 UTC, KomachiSion commented on auth/src/main/java/com/alibaba/nacos/auth/AuthService.java
> +public interface AuthService {
不需要单独添加interface， 参考 isLoginPageEnabled，把方法定义在插件中，在interface中提供default实现（false）即可

2024-05-15 02:55 UTC, KomachiSion requested changes

2024-05-15 02:55 UTC, KomachiSion commented on auth/src/main/java/com/alibaba/nacos/auth/config/AuthModuleStateBuilder.java
> +        return false;
这里最好是可变的， 如果adminRequest是true的时候，就不能缓存，如果是已经是false，那说明：
1. 插件不需要admin
2. admin已存在
此时就不需要再重新生成了，可以缓存了

2024-05-17 02:32 UTC, godhth commented on auth/src/main/java/com/alibaba/nacos/auth/AuthService.java
> +public interface AuthService {
done

2024-05-17 02:32 UTC, godhth commented on auth/src/main/java/com/alibaba/nacos/auth/config/AuthModuleStateBuilder.java
> +        return false;
done

2024-05-20 03:17 UTC, KomachiSion approved these changes

2024-05-20 03:17 UTC, KomachiSion commented
There is some conflict with test file.

2024-05-24 02:14 UTC, KomachiSion approved these changes

2024-05-24 02:14 UTC, merged