[issue #12081]  module api upgrade  junit4 to junit5
alibaba/nacos pull request #12082
Opened 2024-05-10 12:46 UTC by shalk

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #12081

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-05-15 02:38 UTC, KomachiSion requested changes

2024-05-15 02:38 UTC, KomachiSion commented on api/src/test/java/com/alibaba/nacos/api/ability/ClientAbilitiesTest.java
> -
dont change the indent.

2024-05-15 03:31 UTC, shalk commented on api/src/test/java/com/alibaba/nacos/api/ability/ClientAbilitiesTest.java
> -
done

2024-05-16 02:26 UTC, KomachiSion submitted a review, later dismissed

2024-05-16 02:26 UTC, KomachiSion commented
There is one class conflict, simple fix it will be ready to merged.

2024-05-16 11:46 UTC, shalk commented
It is strange for IT test fail only for JDK8 latest. But JDK8.0.192 is pass.
It maybe effect by  5169f06654a57db4f01cde83406bbc1ba07d4a29

2024-05-20 03:13 UTC, KomachiSion approved these changes

2024-05-20 03:14 UTC, KomachiSion commented
> It is strange for IT test fail only for JDK8 latest. But JDK8.0.192 is pass. It maybe effect by [5169f06](https://github.com/alibaba/nacos/commit/5169f06654a57db4f01cde83406bbc1ba07d4a29)

TLS is depend os and jdk version. If jdk has some change for tls support or has some bug in jdk. It might effect test and runtime.

2024-05-20 03:14 UTC, merged