[ISSUE #12060]  fix too large ttl when auth disabled
alibaba/nacos pull request #12090
Opened 2024-05-12 14:20 UTC by DemonHugo

## What is the purpose of the change

fix issue #12060

## Brief changelog

> 1. fix too large ttl when auth disabled
> 2. generate a valid token when nacos.core.auth.plugin.nacos.token.secret.key is valid even if auth disabled

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-05-12 14:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=12090) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=12090) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=12090) it.</sub>

2024-05-13 02:32 UTC, DemonHugo commented
晚上提交一下单元测试

2024-05-15 02:37 UTC, KomachiSion requested changes
我的想法是在AUTH_DISABLED_TOKEN的prefix或者suffix添加时间戳，然后在getTTl的时候把prefix或者suffix取出来计算剩余的ttl时间。

2024-05-15 02:37 UTC, KomachiSion commented on plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java
> +        if (!authConfigs.isAuthEnabled() && null == jwtParser) {
应该不用判断jwtParser，如果未开启鉴权，无论是有jwtParser应该都不需要计算jwtparser的

2024-05-15 02:37 UTC, KomachiSion commented on plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java
> +        if (!authConfigs.isAuthEnabled() && null == jwtParser) {
而且下面有校验jwtparser

2024-05-15 15:31 UTC, DemonHugo commented
> 我的想法是在AUTH_DISABLED_TOKEN的prefix或者suffix添加时间戳，然后在getTTl的时候把prefix或者suffix取出来计算剩余的ttl时间。

该提交目的其实是为了nacos服务端在客户端不感知的情况下自由切换鉴权开关。
目前token校验有四种场景：
> 鉴权关闭，盐值未正确配置
> 鉴权开启，盐值未正确配置
> 鉴权关闭，盐值正确配置
> 鉴权开启，盐值正确配置

其中第1条返回AUTH_DISABLED_TOKEN，第2条报错应正确配置key，第4条正常鉴权，与当前实现无殊。
本次提交期望是在第3种场景下，服务端仍能正确返回客户端token，这样服务端能在客户端不感知的情况下开启鉴权，无需使客户端等待9/10ttl后再获取正确token。

因此，我在createToken的方法中返回AUTH_DISABLED_TOKEN时增加校验盐值有效性的条件。同时，将checkParser方法放到else if判断里是为了避免前述改动使服务端login接口频繁报错。

2024-05-16 01:47 UTC, KomachiSion commented
> > 我的想法是在AUTH_DISABLED_TOKEN的prefix或者suffix添加时间戳，然后在getTTl的时候把prefix或者suffix取出来计算剩余的ttl时间。
> 
> 该提交目的其实是为了nacos服务端在客户端不感知的情况下自由切换鉴权开关。 目前token校验有四种场景：
> 
> > 鉴权关闭，盐值未正确配置
> > 鉴权开启，盐值未正确配置
> > 鉴权关闭，盐值正确配置
> > 鉴权开启，盐值正确配置
> 
> 其中第1条返回AUTH_DISABLED_TOKEN，第2条报错应正确配置key，第4条正常鉴权，与当前实现无殊。
> 
> 本次提交期望是在第3种场景下，服务端仍能正确返回客户端token，这样服务端能在新老版本客户端不感知的情况下开启鉴权，无需使客户端等待9/10ttl后再获取正确token。
> 
> 因此，我在createToken的方法中返回AUTH_DISABLED_TOKEN时增加校验盐值有效性的条件。同时，将checkParser方法放到else if判断里是为了避免前述改动使服务端在`鉴权关闭，盐值未正确配置`条件下，login接口频繁报错。

ok

2024-05-16 01:49 UTC, KomachiSion commented
CI can't pass， please fit it

2024-05-20 03:12 UTC, KomachiSion approved these changes

2024-05-20 03:12 UTC, merged