[ISSUE #12133] upgrade module naocs-core from junit4 to junit5
alibaba/nacos pull request #12134
Opened 2024-05-24 11:29 UTC by shalk

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #12133 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-05-29 02:44 UTC, KomachiSion requested changes
不修改grpc-testing的话，是无法改为junit5吗？

2024-05-29 02:44 UTC, KomachiSion commented on core/pom.xml
> +            <artifactId>grpc-test</artifactId>
这个产品的开源协议是什么？

2024-05-29 02:44 UTC, KomachiSion commented on core/pom.xml
> +            <artifactId>grpc-test</artifactId>
另外有没有长期维护的情况？

2024-05-29 09:19 UTC, shalk commented on core/pom.xml
> +            <artifactId>grpc-test</artifactId>
license is [Apache-2.0 license](https://github.com/asarkar/grpc-test#Apache-2.0-1-ov-file)

Yes, the lib looks stable.

grpc-testing can not upgrade to junit4

2024-05-31 05:42 UTC, KomachiSion approved these changes

2024-05-31 05:42 UTC, merged