[ISSUE #12219] 修复nacos-client中config的ServerListManager解析endpoint失败问题
alibaba/nacos pull request #12220
Opened 2024-06-14 06:26 UTC by misakacoder

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #12219 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-06-17 06:23 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
> -            this.endpoint = endpointUrl;
是不是这行改成`endpointTmp=endpointUrl` 即可

2024-06-17 06:36 UTC, misakacoder commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
> -            this.endpoint = endpointUrl;
这样改也可以

2024-06-24 01:40 UTC, KomachiSion requested changes

2024-06-24 01:40 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
> -            this.endpoint = endpointUrl;
那麻烦改一下

2024-06-24 01:58 UTC, misakacoder commented
@KomachiSion 改了

2024-06-26 09:32 UTC, KomachiSion approved these changes

2024-07-01 05:54 UTC, merged