[#12235]Fix the incorrect logging format in the ResponseExceptionHand…
alibaba/nacos pull request #12236
Opened 2024-06-16 05:36 UTC by HMYDK

…ler of the naming module.

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #12235
Fix the incorrect logging format in the ResponseExceptionHandler of the naming module.

2024-06-17 05:49 UTC, KomachiSion requested changes

2024-06-17 05:49 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/exception/ResponseExceptionHandler.java
> -
Please don't change the indents.

2024-06-17 06:45 UTC, HMYDK commented on naming/src/main/java/com/alibaba/nacos/naming/exception/ResponseExceptionHandler.java
> -
我是用项目中的`nacos-code-style-for-idea.xml`重新格式化了代码。

2024-06-24 01:41 UTC, KomachiSion approved these changes

2024-06-24 01:41 UTC, merged