refactor: Unified Nacos Client address module code
alibaba/nacos pull request #12274
Opened 2024-06-23 12:12 UTC by totalo

for #12189 

## What is the purpose of the change

Unified Nacos Client address module code, and provide custom expansion capabilities.

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-06-23 12:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=12274) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=12274) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=12274) it.</sub>

2024-06-26 09:46 UTC, KomachiSion commented
暂时还没有进行细节review，目前有一个问题可能需要考虑一下：

https://github.com/alibaba/nacos/issues/12218 根据这个issue的信息， 目前配置中心和注册中心的ServerListManager 寻址的优先级顺序有一定的区别， 建议在设计时考虑进去。

2024-06-26 11:00 UTC, totalo commented
> 暂时还没有进行细节review，目前有一个问题可能需要考虑一下：
> 
> 
> 
> https://github.com/alibaba/nacos/issues/12218 根据这个issue的信息， 目前配置中心和注册中心的ServerListManager 寻址的优先级顺序有一定的区别， 建议在设计时考虑进去。
> 
> 
> 
> 

ok.

2024-07-02 07:44 UTC, KomachiSion commented
> > 暂时还没有进行细节review，目前有一个问题可能需要考虑一下：
> > #12218 根据这个issue的信息， 目前配置中心和注册中心的ServerListManager 寻址的优先级顺序有一定的区别， 建议在设计时考虑进去。
> 
> ok.

issue中已经有结论回复了， 可以考虑略微进行一下修改，并解决一下出现的冲突。

2024-07-03 00:48 UTC, totalo commented
> > > 暂时还没有进行细节review，目前有一个问题可能需要考虑一下：
> 
> > > #12218 根据这个issue的信息， 目前配置中心和注册中心的ServerListManager 寻址的优先级顺序有一定的区别， 建议在设计时考虑进去。
> 
> > 
> 
> > ok.
> 
> 
> 
> issue中已经有结论回复了， 可以考虑略微进行一下修改，并解决一下出现的冲突。

好，感谢大佬(🙏ˊᗜˋ*)

2024-07-05 06:01 UTC, totalo commented
> > > 暂时还没有进行细节review，目前有一个问题可能需要考虑一下：
> > > #12218 根据这个issue的信息， 目前配置中心和注册中心的ServerListManager 寻址的优先级顺序有一定的区别， 建议在设计时考虑进去。
> > 
> > 
> > ok.
> 
> issue中已经有结论回复了， 可以考虑略微进行一下修改，并解决一下出现的冲突。

已经调整

2024-07-08 02:51 UTC, KomachiSion commented
> > > > 暂时还没有进行细节review，目前有一个问题可能需要考虑一下：
> > > > #12218 根据这个issue的信息， 目前配置中心和注册中心的ServerListManager 寻址的优先级顺序有一定的区别， 建议在设计时考虑进去。
> > > 
> > > 
> > > ok.
> > 
> > 
> > issue中已经有结论回复了， 可以考虑略微进行一下修改，并解决一下出现的冲突。
> 
> 已经调整

好的，近期我会详细review一下，然后提出修改意见。

2024-07-09 04:29 UTC, totalo commented
> > > > > 暂时还没有进行细节review，目前有一个问题可能需要考虑一下：
> 
> > > > > #12218 根据这个issue的信息， 目前配置中心和注册中心的ServerListManager 寻址的优先级顺序有一定的区别， 建议在设计时考虑进去。
> 
> > > > 
> 
> > > > 
> 
> > > > ok.
> 
> > > 
> 
> > > 
> 
> > > issue中已经有结论回复了， 可以考虑略微进行一下修改，并解决一下出现的冲突。
> 
> > 
> 
> > 已经调整
> 
> 
> 
> 好的，近期我会详细review一下，然后提出修改意见。

感谢

2024-07-15 05:41 UTC, KomachiSion reviewed
给予了一些review的评价：
1. 事件是否也统一抽象出去？
2. 异步从地址服务器更新地址列表的逻辑是否也可以抽象出去复用？
3. 梳理一下ServerListManager的构造器，去除一些不使用的，减少复杂度
4. 是否遗漏了IS_USE_CLOUD_NAMESPACE_PARSING相关逻辑？

2024-07-15 05:41 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigServerListChangeEvent.java
> +public class ConfigServerListChangeEvent extends SlowEvent {
事件是否也能统一一下？

2024-07-15 05:41 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/event/NamingServerListChangeEvent.java
> +public class NamingServerListChangeEvent extends SlowEvent {
同配置中心事件，也可以考虑统一一下。

2024-07-15 05:41 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/core/NamingServerListManager.java
>              refreshServerListExecutor
异步从地址服务器更新server地址的逻辑，是否也能一并抽象出去？

2024-07-15 14:12 UTC, totalo commented
> 给予了一些review的评价：
> 
> 1. 事件是否也统一抽象出去？
> 
> 2. 异步从地址服务器更新地址列表的逻辑是否也可以抽象出去复用？
> 
> 3. 梳理一下ServerListManager的构造器，去除一些不使用的，减少复杂度
> 
> 4. 是否遗漏了IS_USE_CLOUD_NAMESPACE_PARSING相关逻辑？

好的，谢谢大佬，我这边详细看看考虑一下

2024-07-17 16:50 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +        String namespace = properties.getProperty(PropertyKeyConst.NAMESPACE);
这个原逻辑就没有，是否需要加上呢？

2024-07-17 16:50 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigServerListChangeEvent.java
> +public class ConfigServerListChangeEvent extends SlowEvent {
done.

2024-07-17 16:50 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/naming/event/NamingServerListChangeEvent.java
> +public class NamingServerListChangeEvent extends SlowEvent {
done.

2024-07-17 16:51 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +            break;
目前是加了一个类型字段，在配置中添加类型获取

2024-07-17 16:56 UTC, totalo commented
@KomachiSion  大佬，我调整了一个版本，辛苦有空 review。主要的问题点如下：

- load 是通过属性中添加类型与 provider 类型名称匹配，就使用这个配置，这种方式可行吗？

- IS_USE_CLOUD_NAMESPACE_PARSING 的逻辑原来就没有，这次需要加上吗?

2024-07-19 09:18 UTC, KomachiSion requested changes

2024-07-19 09:18 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +    {
这种static代码块的方式，需要确保不能失败，否则的话建议下沉到方法内，否则出错时会出现ClassNotDef的错误，而且容易吞实际的错误，很难排查。

2024-07-19 09:18 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +        String namespace = properties.getProperty(PropertyKeyConst.NAMESPACE);
没事了，我看了下命名空间的解析在创建Service的时候， 只要确保新的地址服务器在解析命名空间之后即可。

2024-07-19 09:18 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/ServerListHttpClientManager.java
> +public class ServerListHttpClientManager implements Closeable {
这个类我没有看懂，目的是什么？

2024-07-19 09:25 UTC, KomachiSion commented
> @KomachiSion 大佬，我调整了一个版本，辛苦有空 review。主要的问题点如下：
> 
> * load 是通过属性中添加类型与 provider 类型名称匹配，就使用这个配置，这种方式可行吗？
> * IS_USE_CLOUD_NAMESPACE_PARSING 的逻辑原来就没有，这次需要加上吗?

关于问题1， 其实这么来思考：
1. 现有的地址服务器形式的和serverAddr参数形式的算不算是ServerListProvider的一种？如果算的话，为什么他们是在ServerListProvider之外的AddressServerListManager中实现；如果不算的话，那他们和ServerListProvider是什么关系？
2. 如果同时配置了ServerListProvider的type和endpoint或serverAddr， 他们的优先级是怎样的， 是否互斥？

我个人的拙见：我认为地址服务器也好，配置的serverAddr也好，应该算是provider的一种，和其他用户自定义的Provider一起进行选择；另外，我认为寻址应该是互斥的，而不是互补，因此我赞同使用类似type的方式来指定，不过我觉得可以优化一下方式，比如能解析到有endpoint（无论是properties里有还是环境变量），那就用地址服务器，没有endpoint就用serverAddr，再没有就用用户自定义的Provider（这是个例子，你可以考虑一下是否先用户自定义，再endpoint和serverAddr，但是要保证先endpoint再serverAddr即可）

2024-07-19 09:43 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +    {
嗯嗯

2024-07-19 09:45 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/ServerListHttpClientManager.java
> +public class ServerListHttpClientManager implements Closeable {
原来config 和 naming 都是使用的自己的 NacosTemplate，防止耦合以及后续对于寻址模块特使的 http 的配置，所以也单独抽离出来了。

2024-07-19 09:45 UTC, totalo commented
> > @KomachiSion 大佬，我调整了一个版本，辛苦有空 review。主要的问题点如下：
> > 
> > * load 是通过属性中添加类型与 provider 类型名称匹配，就使用这个配置，这种方式可行吗？
> > * IS_USE_CLOUD_NAMESPACE_PARSING 的逻辑原来就没有，这次需要加上吗?
> 
> 关于问题1， 其实这么来思考：
> 
> 1. 现有的地址服务器形式的和serverAddr参数形式的算不算是ServerListProvider的一种？如果算的话，为什么他们是在ServerListProvider之外的AddressServerListManager中实现；如果不算的话，那他们和ServerListProvider是什么关系？
> 2. 如果同时配置了ServerListProvider的type和endpoint或serverAddr， 他们的优先级是怎样的， 是否互斥？
> 
> 我个人的拙见：我认为地址服务器也好，配置的serverAddr也好，应该算是provider的一种，和其他用户自定义的Provider一起进行选择；另外，我认为寻址应该是互斥的，而不是互补，因此我赞同使用类似type的方式来指定，不过我觉得可以优化一下方式，比如能解析到有endpoint（无论是properties里有还是环境变量），那就用地址服务器，没有endpoint就用serverAddr，再没有就用用户自定义的Provider（这是个例子，你可以考虑一下是否先用户自定义，再endpoint和serverAddr，但是要保证先endpoint再serverAddr即可）



> > @KomachiSion 大佬，我调整了一个版本，辛苦有空 review。主要的问题点如下：
> > 
> > * load 是通过属性中添加类型与 provider 类型名称匹配，就使用这个配置，这种方式可行吗？
> > * IS_USE_CLOUD_NAMESPACE_PARSING 的逻辑原来就没有，这次需要加上吗?
> 
> 关于问题1， 其实这么来思考：
> 
> 1. 现有的地址服务器形式的和serverAddr参数形式的算不算是ServerListProvider的一种？如果算的话，为什么他们是在ServerListProvider之外的AddressServerListManager中实现；如果不算的话，那他们和ServerListProvider是什么关系？
> 2. 如果同时配置了ServerListProvider的type和endpoint或serverAddr， 他们的优先级是怎样的， 是否互斥？
> 
> 我个人的拙见：我认为地址服务器也好，配置的serverAddr也好，应该算是provider的一种，和其他用户自定义的Provider一起进行选择；另外，我认为寻址应该是互斥的，而不是互补，因此我赞同使用类似type的方式来指定，不过我觉得可以优化一下方式，比如能解析到有endpoint（无论是properties里有还是环境变量），那就用地址服务器，没有endpoint就用serverAddr，再没有就用用户自定义的Provider（这是个例子，你可以考虑一下是否先用户自定义，再endpoint和serverAddr，但是要保证先endpoint再serverAddr即可）

嗯嗯，理解

2024-07-20 14:23 UTC, totalo commented
@KomachiSion 大佬，我又调整了一版。有时间辛苦 review，整体思路如下：

- 抽出公共的寻址模块，默认分为 AddressServerListProvider 和 EndpointServerListProvider
- 寻址模块的 SPI 通过order 进行降序排列，这样用户自定义实现的寻址可以通过定义 order 选择合适的位置

2024-07-23 08:02 UTC, KomachiSion requested changes

2024-07-23 08:02 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> +        Random random = new Random();
重试的逻辑被移除了？

2024-07-24 11:20 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/ServerListHttpClientManager.java
> +public class ServerListHttpClientManager implements Closeable {
目前公用的一个。

2024-07-24 11:21 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +            if (CollectionUtils.isNotEmpty(getServerList())) {
是的，原来的代码就是确定使用 endpoint 或者 address 即使使用的获取的为空也返回空了。

2024-07-24 11:22 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/EndpointServerListProvider.java
> +            HttpRestResult<String> httpResult = nacosRestTemplate.get(addressServerUrl, HttpUtils.builderHeader(MODULE_NAME),
原来配置中心的 header 是空的，注册中心是有 Naming 的标识

2024-07-24 11:23 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> +        Random random = new Random();
理解有误，忽略，我把代码恢复一下。

2024-07-29 03:27 UTC, KomachiSion requested changes
目前还有几个遗留问题未解决：
1. 请求地址服务器时的Header还未添加
2. Provider建议在实际init之前，判断一下当前配置是否选择当前privder进行，比如properties中有endpoint，或parsing=true&环境变量中有ALIBABA_ENDPOINT；如果有的话，就不需要去init serverAddr；或者都init，但是选择的时候不已serverList是否为empty决定。
3. 地址服务器对象的名称，由于之前不同地址服务器寻址的Manager不同，所以不需要区分名字， 现在复用了相同的父类对象了， 命名上是否需要区分一下。
4. 配置中心ClientWoker和注册中心获取地址逻辑上有问题，需要修改

待确认问题：
1. Http template共有的话， 连接池，limiter是否会互相干扰？

目前可以被采纳的部分：
1. Manager和Provider解耦。
2. Order被修改成通过接口获取
3. 保留了旧的大多数Manager接口，使用Manager的地方基本没有修改。

2024-07-29 03:27 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/ServerListHttpClientManager.java
> +public class ServerListHttpClientManager implements Closeable {
公用一个的话， 连接池和Limiter的配置会不会互相干扰？

2024-07-29 03:27 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
> +        if (provider instanceof EndpointServerListProvider) {
这里其实不太合理， 已经抽象成Provider了， 按理来说使用处不应该还感知是endpint还是serverAddr

可以通过provider抽象接口来实现。

2024-07-29 03:27 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
> +        metric.put("isFixedServer", provider instanceof AddressServerListProvider);
同上， 比如抽象1～2个接口

isFixed（isDynamic）
getAddressSource
等具有抽象语意的接口

2024-07-29 03:27 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> +        Random random = new Random();
似乎还没有恢复

2024-07-29 14:22 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/AddressServerListProvider.java
> +                : "") + getFixedNameSuffix(serverList.toArray(new String[0]));
已经添加了 moduleName 进行区分

2024-07-29 14:24 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/ServerListHttpClientManager.java
> +public class ServerListHttpClientManager implements Closeable {
这个会影响，原来是打算这块共用一下，如果某一个模块已经开启了刷新任务，就不再重复了。现在拆分了。

2024-07-29 14:25 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +            if (CollectionUtils.isNotEmpty(getServerList())) {
done.

2024-07-29 14:25 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/EndpointServerListProvider.java
> +            HttpRestResult<String> httpResult = nacosRestTemplate.get(addressServerUrl, HttpUtils.builderHeader(MODULE_NAME),
已经修正

2024-07-29 14:25 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> +        Random random = new Random();
done.

2024-07-29 14:25 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
> +        metric.put("isFixedServer", provider instanceof AddressServerListProvider);
done.

2024-07-29 14:25 UTC, totalo commented
@KomachiSion 大佬，已经调整，辛苦 review

2024-08-01 06:58 UTC, KomachiSion requested changes

2024-08-01 06:58 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +        Collection<ServerListProvider> serverListProviders = NacosServiceLoader.load(ServerListProvider.class);
这里有办法保证provider的优先级吗？

2024-08-01 06:58 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +        Collection<ServerListProvider> serverListProviders = NacosServiceLoader.load(ServerListProvider.class);
我看虽然有order的方法，但是没有排序

2024-08-01 06:58 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManager.java
> +        nacosRestTemplate.getInterceptors().add(limiterHttpClientRequestInterceptor);
会不会出现重复的Interceptor？

2024-08-01 06:58 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManager.java
> +        nacosRestTemplate.getInterceptors().add(limiterHttpClientRequestInterceptor);
其实我觉得这个类可能没必要改。

2024-08-01 08:04 UTC, totalo commented on client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
> +        Collection<ServerListProvider> serverListProviders = NacosServiceLoader.load(ServerListProvider.class);
我加一下，原始实现是在 load 的时候添加了 cache，然后排序，后面觉得太复杂了，就去掉了，漏掉了😂

2024-08-01 08:26 UTC, totalo commented
@KomachiSion 调整了一下，辛苦大佬再看看～

2024-08-05 03:09 UTC, KomachiSion reviewed
目前初步review似乎没有太大的问题了， 之后会在活动截止前对PR进行整体评判后决定是否合入。

我先跑一下CI，请关注一下结果，避免后续需要合入时由于CI问题被阻塞。

2024-08-05 05:48 UTC, totalo commented
> 目前初步review似乎没有太大的问题了， 之后会在活动截止前对PR进行整体评判后决定是否合入。
> 
> 
> 
> 我先跑一下CI，请关注一下结果，避免后续需要合入时由于CI问题被阻塞。

好的，谢谢

2024-08-27 15:22 UTC, totalo commented
@KomachiSion 大佬，其他的做了一个调整，但是这个不是很理解，"未对SPI的实现做异常处理，可能导致其中一个错误的SPI实现抛出异常影响到其他SPI的加载以及整个Client的初始化。", 这是指 init 的时候么？

2024-10-10 07:34 UTC, KomachiSion commented
> @KomachiSion 大佬，其他的做了一个调整，但是这个不是很理解，"未对SPI的实现做异常处理，可能导致其中一个错误的SPI实现抛出异常影响到其他SPI的加载以及整个Client的初始化。", 这是指 init 的时候么？

比如有3个SPI实现进行了加载， 在第一个SPI初始化的时候（实现的构造方法中）抛出异常，此时没有catch异常，继续初始化后续的动作，而向上抛出异常，这可能导致因为一个无效插件而导致整个客户端都初始化失败。

一般来说， SPI的构造函数应尽量简单，避免异常（无法保证但是需要考虑），同时留出类似init的方法，用于实际进行复杂的初始化操作（这个基于设置考虑，如果插件实现本身比较简单，不预留也可以），当然init的方法也需要考虑抛出异常的情况。

2024-10-10 13:51 UTC, totalo commented
> > @KomachiSion 大佬，其他的做了一个调整，但是这个不是很理解，"未对SPI的实现做异常处理，可能导致其中一个错误的SPI实现抛出异常影响到其他SPI的加载以及整个Client的初始化。", 这是指 init 的时候么？
> 
> 比如有3个SPI实现进行了加载， 在第一个SPI初始化的时候（实现的构造方法中）抛出异常，此时没有catch异常，继续初始化后续的动作，而向上抛出异常，这可能导致因为一个无效插件而导致整个客户端都初始化失败。
> 
> 一般来说， SPI的构造函数应尽量简单，避免异常（无法保证但是需要考虑），同时留出类似init的方法，用于实际进行复杂的初始化操作（这个基于设置考虑，如果插件实现本身比较简单，不预留也可以），当然init的方法也需要考虑抛出异常的情况。

嗯嗯，这个理解。但是目前的实现上面都是调用的无参构造，然后再调用 init方法初始化。所有不太明白是为啥。

2024-10-15 02:08 UTC, KomachiSion commented
> > > @KomachiSion 大佬，其他的做了一个调整，但是这个不是很理解，"未对SPI的实现做异常处理，可能导致其中一个错误的SPI实现抛出异常影响到其他SPI的加载以及整个Client的初始化。", 这是指 init 的时候么？
> > 
> > 
> > 比如有3个SPI实现进行了加载， 在第一个SPI初始化的时候（实现的构造方法中）抛出异常，此时没有catch异常，继续初始化后续的动作，而向上抛出异常，这可能导致因为一个无效插件而导致整个客户端都初始化失败。
> > 一般来说， SPI的构造函数应尽量简单，避免异常（无法保证但是需要考虑），同时留出类似init的方法，用于实际进行复杂的初始化操作（这个基于设置考虑，如果插件实现本身比较简单，不预留也可以），当然init的方法也需要考虑抛出异常的情况。
> 
> 嗯嗯，这个理解。但是目前的实现上面都是调用的无参构造，然后再调用 init方法初始化。所有不太明白是为啥。

那就可以了，等合并之后再修改。

2024-10-15 02:12 UTC, KomachiSion approved these changes

2024-10-15 02:13 UTC, merged