[ISSUE #12301] 相同永久实例在不同nameSpace下面健康检测问题
alibaba/nacos pull request #12310
Opened 2024-07-04 09:06 UTC by chen10038

Please do not create a Pull Request without creating an issue first.

for #12301

## What is the purpose of the change

fix #12301
Beat 对象toString()增加 nameSpace区分
tryStartCheck日志打印增加nameSpace区分

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-07-04 09:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=12310) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=12310) before we can accept your contribution.<br/><hr/>**chenbowen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=12310) it.</sub>

2024-07-08 02:47 UTC, KomachiSion approved these changes

2024-07-08 02:48 UTC, KomachiSion requested changes
Please sign your CLA first,  and help community add unit test for your changes.

2024-07-08 06:47 UTC, chen10038 commented
修改了本地git配置完成CLA。重新修改toString方法，否则超过限制的150的length。麻烦再review一下。

2024-07-15 03:16 UTC, KomachiSion approved these changes

2024-07-15 03:16 UTC, KomachiSion commented
Can you add unit test for this?

2024-07-31 05:48 UTC, merged