[ISSUE #12189] refactor the server list manager code in the client module
alibaba/nacos pull request #12366
Opened 2024-07-17 09:25 UTC by misakacoder

## What is the purpose of the change

#12189

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

## 本改动借助了通义灵码进行辅助编程

![微信截图_20240717155502](https://github.com/user-attachments/assets/054fb46c-d85d-4a54-9911-1b68fcf78c73)
![微信截图_20240717165506](https://github.com/user-attachments/assets/5578a196-2b6c-402a-b317-2fae98cb26bb)
![微信截图_20240717160422](https://github.com/user-attachments/assets/1cfce2bb-ce44-4f20-abdc-48adec494227)
![微信截图_20240717164031](https://github.com/user-attachments/assets/bd52ab06-7e44-41ba-9bce-a59eed782872)
![微信截图_20240717164940](https://github.com/user-attachments/assets/3e21f552-64bb-48dd-b7a0-b9d8cea55564)

2024-07-18 07:55 UTC, KomachiSion commented
已收到PR， 会尽快进行review，请时刻关注

2024-07-19 09:03 UTC, KomachiSion requested changes
方案中可以认可的点：
1. 用SPI进行扩展。
2. 将AddressServer和Properties独立作为两个拓展实现。
3. 将公共逻辑抽象到抽象类中

可能有问题的点：
1. SPI不需要自己实现，我理解jdk自带的足以支持
2. order的排序方式可以写入到AbstractServerListManager，作为方法提供，用注解+反射的方法可能没那么好。
3. 事件不需要修改名称， 旧的名称足以表达意思
4. 地址服务器的实现可能有逻辑遗漏，建议在梳理一下，做好注册和配置中心的区分（命名和调用逻辑上。

2024-07-19 09:24 UTC, misakacoder commented
> 方案中可以认可的点：
> 
> 1. 用SPI进行扩展。
> 2. 将AddressServer和Properties独立作为两个拓展实现。
> 3. 将公共逻辑抽象到抽象类中
> 
> 可能有问题的点：
> 
> 1. SPI不需要自己实现，我理解jdk自带的足以支持
> 2. order的排序方式可以写入到AbstractServerListManager，作为方法提供，用注解+反射的方法可能没那么好。
> 3. 事件不需要修改名称， 旧的名称足以表达意思
> 4. 地址服务器的实现可能有逻辑遗漏，建议在梳理一下，做好注册和配置中心的区分（命名和调用逻辑上。

1. jdk自带的SPI会自动创建全部实现类的实例，因为我的初始化逻辑是写到构造方法里面的，所以我不想一次性全部实例化。当然像上面说的，采用init函数来手动初始化也行，我改下吧
2. 自定义排序我弄成方法，的确能不反射就不反射。
3. 这个我改回去，我是把之前的2个不同事件名称删除了重新建的，命名习惯不一样。
4. 我看过config和naming的ServerListManager逻辑，我理解的地址服务器就是简单的一个web服务，请求指定接口返回nacos服务列表，就如官网的图所示，所以像上面说的Header header = NamingHttpUtil.builderHeader();这个区别，我认为可能是不同的人写的导致的，因为就是请求一个接口，返回nacos服务器地址列表，config和naming不应该有区别才对噻。
![image](https://github.com/user-attachments/assets/c6844b3a-456f-4296-8f7f-6b0d4d7c8418)

2024-07-19 09:26 UTC, misakacoder commented on api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
> +    public static final String SERVER_FILE = "serverFile";
> 这个Server file是什么？

这个是我参考的MemberLookup的实现逻辑，多加了一个，如果觉得暂时没有必要可以去掉

2024-07-19 09:27 UTC, misakacoder commented on client/src/main/java/com/alibaba/nacos/client/address/factory/ServerListManagerFactory.java
> +                AbstractServerListManager serverListManager = constructor.newInstance(clientProperties);
> 如果用SPI的话，最好使用无参数构造器， 然后调用init方法的方式处理，否则需要构建出两次实例。

就是jdk的SPI不支持有参构造，和会自动实例化类，我才手动实现了一个，你看看嘛，你觉得没有必要我就先去掉

2024-07-19 09:40 UTC, misakacoder commented on client/src/main/java/com/alibaba/nacos/client/address/factory/ServerListManagerFactory.java
> +        for (Class<AbstractServerListManager> cls : classes) {
> 这种循环的话，好像和旧的逻辑会有区别。
> 
> 之前的逻辑，如果endpoint不为空，但是从endpoint的地址服务器上获取到空列表的话，会直接报错serverlist是empty。
> 
> 但是这个逻辑似乎会出现去使用serverAddr的值的情况。

我之前考虑的是按顺序搜寻可用的nacos地址，如果最终所有寻址方式都不能搜寻到可用的nacos服务，就抛异常。
如果和之前保持一直的话，我这样实现，如果每种寻址方式的特定配置，比如endpoint，serverAddr配置了，但是没有获取到nacos服务列表，就直接抛出异常，这样怎么样呢

2024-07-19 09:46 UTC, misakacoder commented on client/src/main/java/com/alibaba/nacos/client/address/impl/AddressServerListManager.java
> +            HttpRestResult<String> result = nacosRestTemplate.get(addressServerUrl, Header.EMPTY, Query.EMPTY, String.class);
> 这里会丢失注册中心和配置中心的区别。 注册中心有一个header
> 
> Header header = NamingHttpUtil.builderHeader();

这个具体看下我下面的回复，我理解的是注册中心和配置中心是一样的，就是请求url，获取响应得到nacos服务列表

2024-07-19 09:54 UTC, misakacoder commented
@KomachiSion 幸苦空了看看我的回复和疑惑，我这边好调整调整

2024-07-23 07:18 UTC, KomachiSion commented
> > 方案中可以认可的点：
> > 
> > 1. 用SPI进行扩展。
> > 2. 将AddressServer和Properties独立作为两个拓展实现。
> > 3. 将公共逻辑抽象到抽象类中
> > 
> > 可能有问题的点：
> > 
> > 1. SPI不需要自己实现，我理解jdk自带的足以支持
> > 2. order的排序方式可以写入到AbstractServerListManager，作为方法提供，用注解+反射的方法可能没那么好。
> > 3. 事件不需要修改名称， 旧的名称足以表达意思
> > 4. 地址服务器的实现可能有逻辑遗漏，建议在梳理一下，做好注册和配置中心的区分（命名和调用逻辑上。
> 
> 1. jdk自带的SPI会自动创建全部实现类的实例，因为我的初始化逻辑是写到构造方法里面的，所以我不想一次性全部实例化。当然像上面说的，采用init函数来手动初始化也行，我改下吧
> 2. 自定义排序我弄成方法，的确能不反射就不反射。
> 3. 这个我改回去，我是把之前的2个不同事件名称删除了重新建的，命名习惯不一样。
> 4. 我看过config和naming的ServerListManager逻辑，我理解的地址服务器就是简单的一个web服务，请求指定接口返回nacos服务列表，就如官网的图所示，所以像上面说的Header header = NamingHttpUtil.builderHeader();这个区别，我认为可能是不同的人写的导致的，因为就是请求一个接口，返回nacos服务器地址列表，config和naming不应该有区别才对噻。
>    ![image](https://private-user-images.githubusercontent.com/36252937/350339485-c6844b3a-456f-4296-8f7f-6b0d4d7c8418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTkzMTksIm5iZiI6MTcyMTcxOTAxOSwicGF0aCI6Ii8zNjI1MjkzNy8zNTAzMzk0ODUtYzY4NDRiM2EtNDU2Zi00Mjk2LThmN2YtNmIwZDRkN2M4NDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3MTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNGEzNDBlOWJkMzMyNzdiZDU4NmE4MTRlZjNkZDQxOTAzNDBlYjNjMmNhMjc0Yzg0ZGI2MjU3OTlmNTgxNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YXVV2G5JAT0jdgWi2Wx7E-bEgGVaTtO-3NQnN6zhP1k)

第4点很重要，是用来区分注册中心和配置中心的情况， 如果是用同一个地址服务器，然后注册和配置中心是不同集群的时候，需要通过Header来区分是需要哪个。

2024-07-23 07:22 UTC, KomachiSion requested changes

2024-07-23 07:22 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
> +    public static final String SERVER_FILE = "serverFile";
先去掉吧， 本issue和pr以重构和留出拓展接口为主， 如果想把这个实现贡献到社区， 可以考虑这个PR合并之后，再添加一个issue和PR来支持。

2024-07-23 07:22 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/impl/AddressServerListManager.java
> +    protected String initServerName(NacosClientProperties properties) {
但是重构之后，注册和配置中心都会复用这个name的代码，可能会生成出一样的名字。

2024-07-23 07:22 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/impl/AddressServerListManager.java
> +            HttpRestResult<String> result = nacosRestTemplate.get(addressServerUrl, Header.EMPTY, Query.EMPTY, String.class);
这个Header很重要， 里面会带一个Request-Module的信息，用于区分需要注册中心的地址还是配置中心的。

2024-07-23 07:22 UTC, KomachiSion commented
> @KomachiSion 幸苦空了看看我的回复和疑惑，我这边好调整调整

辛苦再调整一下。

2024-07-29 03:30 UTC, KomachiSion commented
@misakacoder any update？

2024-07-29 09:56 UTC, misakacoder commented
> @misakacoder any update？

不好意思，前几天有点忙，我调整了下，幸苦帮忙review下呢

2024-08-01 06:14 UTC, KomachiSion requested changes
辛苦再看下评论，进行一下修改。

大体上没有问题了。一些细节问题处理一下。

2024-08-01 06:14 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/manager/AbstractServerListManager.java
> +        if (serverList == null || serverList.isEmpty() || serverList.equals(this.serverList)) {
这里我确认一下， this.serverList经过repairServerAddr之后，和原本的list可能会不一致，会不会导致不停的更新的情况。

另外这里注意一下顺序问题， 比如1.1.1.1,2.2.2.2.和 2.2.2.2,1.1.1.1 是否需要更新。

2024-08-01 06:14 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
> +        boolean isFixServer = serverListProvider instanceof PropertiesServerListProvider;
这里也是建议将这个属性抽象成serverListProvider的方法， 比如isFixedServer 或者 isDynamicServer 等能表达类似意思的。

否则这里使用处还要感知具体类型，不是很好。

当然可以从AbstractServerListManager暴露也行，AbstractServerListManager不是有判断是否需要构造线程池来更新地址吗？

2024-08-01 06:14 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
> +        }
同上， 可以配合上面那个接口，一起处理。

2024-08-01 06:14 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> -            }
这段逻辑的移除，会不会导致仅有一个地址的时候不进行重试了？

2024-08-02 10:00 UTC, misakacoder commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
> +        boolean isFixServer = serverListProvider instanceof PropertiesServerListProvider;
@KomachiSion 大佬，我优化了一下，麻烦再review一下呢

2024-08-02 10:01 UTC, misakacoder commented
@KomachiSion 大佬，我优化了一下，麻烦再review一下呢

2024-08-05 02:45 UTC, KomachiSion requested changes
两个建议：
1. 关于ServerHttpAgent文件的改动， 我觉得最好不要进行大改，保持原有逻辑，因为我们是寻址模块的重构，而不是Agent的重构。如果有兴趣，可以在这个PR结束之后，单独提交。
2. Provider的startup其实我建议在valid之后，因为地址服务器以及可能后续的用户自定义Provider， 都可能在startup中有网络或IO操作，这可能导致耗时以及报错异常等，如果放在valid之前，花费时间以及内存进行了多项初始化工作，甚至是IO操作，然后不满足valid条件被忽略， 有点得不偿失。

另外 关于NamingHttpClientProxy丢失的逻辑，依然没有补回。

2024-08-05 02:45 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/address/manager/ConfigServerListManager.java
> +            addressServerUrl = ReflectUtils.getFieldValue(serverListProvider, "addressServerUrl").toString();
用反射是不是不太好？

是不是改为provider提供一个getRemoteProviderUrl方法来获取比较好， 默认这个方法可以返回一个空字符串，或者返回一个Optional.

2024-08-05 09:34 UTC, misakacoder commented
@KomachiSion 已修改，麻烦再review下呢，另外NamingHttpClientProxy只有一个地址就不重试的逻辑我是优化成这样了。

![image](https://github.com/user-attachments/assets/4ae64189-188b-4f73-a29a-8b34bad66947)

2024-08-07 07:09 UTC, KomachiSion reviewed
目前初步review似乎没有太大的问题了， 之后会在活动截止前对PR进行整体评判后决定是否合入。

2024-08-07 07:19 UTC, misakacoder commented
> 目前初步review似乎没有太大的问题了， 之后会在活动截止前对PR进行整体评判后决定是否合入。

好的，感谢

2024-10-15 02:14 UTC, KomachiSion commented
根据最后的评分结果， https://github.com/alibaba/nacos/pull/12274 会被合并入主干分支，

感谢参赛同学的贡献，该PR也有很多可取之处， 欢迎继续贡献此模块内容，将这部分内容优化的更好。

2024-10-15 02:14 UTC, closed without merging