[ISSUE #12017] Add console backend configuration handling
alibaba/nacos pull request #12420
Opened 2024-07-24 09:26 UTC by RickonZhang0929

Add console backend configuration handling with proxy and handler layers

* Add ConfigHandler interface for defining configuration operations

* Add ConfigInnerHandler to handle internal configuration logic

* Add ConfigProxy to delegate configuration tasks based on deployment type

* Add ConfigController to utilize ConfigProxy for configuration operations

* Update ConsoleConfig to get development type

2024-07-24 09:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=12420) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=12420) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: RickonZhang0929<br/>:x: rickonzhang<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=12420) it.</sub>

2024-07-26 09:43 UTC, KomachiSion requested changes

2024-07-26 09:43 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +    @GetMapping("/configs")
configs可以抽到类的Mapping里

2024-07-31 09:20 UTC, KomachiSion requested changes

2024-07-31 09:20 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +@RequestMapping("/v3/console/cs/configs")
uri需要用复数形式吗？

2024-07-31 09:20 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +    public ResponseEntity<?> detailConfigInfo(@RequestParam("dataId") String dataId,
API的返回内容最好使用规范化的RestResult或者com.alibaba.nacos.api.model.v2.Result

2024-08-03 10:20 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +    @GetMapping("/configs")
已解决

2024-08-03 10:20 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +@RequestMapping("/v3/console/cs/configs")
v2使用单数形式，已修改

2024-08-03 10:20 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +    public ResponseEntity<?> detailConfigInfo(@RequestParam("dataId") String dataId,
我参考了原有代码修改返回类型

1.抛出Throwable
2.使用RestResultUtils记录成功和失败
3.使用LOGGER记录失败日志
4.根据名称填写失败信息msg

2024-08-05 02:11 UTC, KomachiSion requested changes
Controller层一般情况下会要做的事：
1. 参数类型的转换和封装
2. 参数有效性的校验
3. 返回内容的转换和封装。

目前提交的Controller基本都没有做到。

可以参考一下前一个同学写的ConfigControllerV2。

因为你是新增了一套新的接口，后面UI控制台会按照你新定的API进行调用， 所以很多参数、规范不必拘泥于旧接口。可以按照标准的方式去设计。

2024-08-05 02:11 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +            @RequestParam(value = "tenant", required = false, defaultValue = "") String tenant,
新接口最好统一用namespaceId替换tenant

2024-08-05 02:11 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +            return RestResultUtils.failed(500, result, "publish configuration information fail");
错误码需要判断是否是已知的问题，比如NacosException或者NacosRuntimeException等。

如果这里不确定的话， 就不要做异常处理， 交给ExceptionHandler来统一处理。

2024-08-07 06:35 UTC, KomachiSion requested changes

2024-08-07 06:35 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +        ConfigForm configForm = new ConfigForm();
为什么不直接在方法上用ConfigForm？

2024-08-07 06:35 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +        }
解密应该算是业务逻辑了，其他的发布配置的时候也是在controller里面吗？

2024-08-15 01:52 UTC, KomachiSion requested changes
proxy和controller的命名看下是否调整一下， 有几个method和api我看着有点难理解。

2024-08-15 01:52 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +    @Secured(action = ActionTypes.READ, signType = SignType.CONFIG)
是不是少了AdminAPI的指定

2024-08-15 01:52 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +    public void getConfig(HttpServletRequest request, HttpServletResponse response,
getConfig却不返回内容吗？ 是不是有错误？

2024-08-15 01:52 UTC, KomachiSion commented on console/src/main/resources/application.properties
> +nacos.auth.server.enabled=false
这个是鉴权的开关？

2024-08-20 04:49 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +            @RequestParam(value = "tenant", required = false, defaultValue = "") String tenant,
新的接口都已替换

2024-08-20 04:50 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +            return RestResultUtils.failed(500, result, "publish configuration information fail");
controller这里就不再异常处理了

2024-08-20 04:50 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +        ConfigForm configForm = new ConfigForm();
已修改

2024-08-20 04:51 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +        }
这部分下放到了handler，已修改

2024-08-20 04:51 UTC, RickonZhang0929 commented
> proxy和controller的命名看下是否调整一下， 有几个method和api我看着有点难理解。

命名已调整

2024-08-20 04:51 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +    @Secured(action = ActionTypes.READ, signType = SignType.CONFIG)
已加上

2024-08-20 04:52 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleConfigController.java
> +    public void getConfig(HttpServletRequest request, HttpServletResponse response,
已解决，这个接口更新了，替换了底层方法，有返回值了

2024-08-20 04:52 UTC, RickonZhang0929 commented on console/src/main/resources/application.properties
> +nacos.auth.server.enabled=false
已删除，这是鉴权的开关，后面放到鉴权PR上提交

2024-08-20 06:18 UTC, KomachiSion requested changes
最后一点小问题调整一下，

然后加一下单元测试。

2024-08-20 06:18 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigController.java
> +    @GetMapping
一般来说， list接口用`$parentPath/list`, 下面的detail接口，及查询配置详情的接口，直接用GET 的`$parentPath` 比较好

2024-08-21 05:52 UTC, KomachiSion approved these changes

2024-08-21 05:53 UTC, merged