[ISSUE #12189] Refactor Client SDK.
alibaba/nacos pull request #12432
Opened 2024-07-27 07:36 UTC by XiaZhouxx

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

client sdk 寻址逻辑重构.

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### 本改动借助了通灵义码进行辅助编程
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/b7ffb453-c9d6-4b85-9a14-7d77064aaff0">
<img width="1340" alt="image" src="https://github.com/user-attachments/assets/be9f2d52-7072-4734-a065-9b3746fd2c46">

2024-07-27 07:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=12432) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=12432) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=12432) it.</sub>

2024-07-27 07:37 UTC, XiaZhouxx commented
第一次尝试提交PR, 希望大佬能够review指点一下, 非常感谢🙏

2024-07-29 02:44 UTC, KomachiSion requested changes
看起来有不少冲突，您的PR基于的基础分支应该比较老旧了， 建议尽快更新一下。

目前相对其他PR比较好的点：
1. 保留了请求地址服务器时Header的语意。
2. 通过ServerListHolder分离了Endpoint和ServerAddr的逻辑。

目前有问题的点：
1. 配置中心ClientWorker和注册中心的HttpProxy的逻辑改动可能导致和以前的逻辑不一致，有风险
2. 有些地址服务器相关参数过旧需要更新
3. 地址服务器逻辑中缺少对queryParameter的支持（可以查看当前的配置中心部分的地址服务器寻址逻辑）

待确认：
1. 同时传入endpoint和serverAddr， 但从endpoint中获取到了返回码200， 但是为空列表时，是否和现在的逻辑不一致

2024-07-29 02:44 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
> -                    serverListMgr.updateCurrentServerAddr(currentServerAddr);
这个逻辑是配置中心为了保持一个访问同一只可访问的server而保持的逻辑， 我看你下面的acquireNextServer并没有保留这个逻辑，但是又移除了， 可能有点问题。

2024-07-29 02:44 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/constant/Constants.java
> +    public static final String ENDPOINT_NAME = "endpoint";
为什么不复用com.alibaba.nacos.api.PropertyKeyConst？

2024-07-29 02:44 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> +        Random random = new Random();
有个问题， 如果这样修改了， 是否会导致如果只输入一个域名或ip的情况下， 客户端失去了失败重试的能力。

2024-07-29 02:44 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/serverlist/holder/impl/CompositeNacosServerListHolder.java
> +            if (CollectionUtils.isNotEmpty(serverList)) {
问个问题， 如果我同时输入endpoint，和serverAddr， 但是endpoint的地址返回的是空列表（内容为空列表，状态码为200）， 是否和原先的寻址逻辑不符合？

2024-07-29 02:44 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/serverlist/holder/impl/EndpointNacosServerListHolder.java
> +            String serverListNameTmp = properties.getProperty(PropertyKeyConst.CLUSTER_NAME);
参数名已在2.3.3版本修改，请更新最新的代码。

2024-07-29 02:44 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/serverlist/holder/impl/EndpointNacosServerListHolder.java
> +            String contentPathTmp = properties.getProperty(PropertyKeyConst.CONTEXT_PATH);
CONTEXT_PATH的逻辑也有修改，请同步

2024-07-29 09:29 UTC, XiaZhouxx commented on client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
> -                    serverListMgr.updateCurrentServerAddr(currentServerAddr);
这里是复用的之前Naming模块的获取Server逻辑, currentIndex在可访问的情况是不变的,应该不会导致Server会变.

2024-07-29 09:35 UTC, XiaZhouxx commented on client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
> -                    serverListMgr.updateCurrentServerAddr(currentServerAddr);
这里是复用Naming模块的nextServer逻辑基于currentIndex, 在失败重试获取的逻辑里面会递增index, 应该不会导致Server下次访问会变动.

2024-07-29 09:37 UTC, XiaZhouxx commented on client/src/main/java/com/alibaba/nacos/client/serverlist/holder/impl/CompositeNacosServerListHolder.java
> +            if (CollectionUtils.isNotEmpty(serverList)) {
> 问个问题， 如果我同时输入endpoint，和serverAddr， 但是endpoint的地址返回的是空列表（内容为空列表，状态码为200）， 是否和原先的寻址逻辑不符合？

确实不符合, 我再优化一下, 只考虑重构没有考虑到兼容版本问题

2024-07-29 09:38 UTC, XiaZhouxx commented on client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
> -                    serverListMgr.updateCurrentServerAddr(currentServerAddr);
> 这个逻辑是配置中心为了保持一个访问同一只可访问的server而保持的逻辑， 我看你下面的acquireNextServer并没有保留这个逻辑，但是又移除了， 可能有点问题。

这里是复用Naming模块的nextServer逻辑基于currentIndex, 在失败重试获取的逻辑里面会递增index, 应该不会导致Server下次访问会变动?

2024-07-29 09:40 UTC, XiaZhouxx commented on client/src/main/java/com/alibaba/nacos/client/serverlist/holder/impl/EndpointNacosServerListHolder.java
> +            String serverListNameTmp = properties.getProperty(PropertyKeyConst.CLUSTER_NAME);
> 参数名已在2.3.3版本修改，请更新最新的代码。

非常抱歉, 没有确认分支就开始开发, 我更新再优化一下

2024-07-29 09:53 UTC, XiaZhouxx commented on client/src/main/java/com/alibaba/nacos/client/constant/Constants.java
> +    public static final String ENDPOINT_NAME = "endpoint";
> 为什么不复用com.alibaba.nacos.api.PropertyKeyConst？

这里是因为觉得有语意问题, 这个常量类都是用作NacosClientProperties在使用的.

2024-07-31 06:22 UTC, XiaZhouxx commented
更新了一下, 也烦请大佬有空review一下

2024-08-01 05:48 UTC, KomachiSion requested changes
感觉上问题已经快收敛完了， 再看下评论进行一次修改。

另外有一个问题可以思考下：

moduleName时通过单独的参数传递进去还是方properties里比较好？
我感觉放properties有一点晦涩，直接传进去是不是明显一点。

2024-08-01 05:48 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
> -                    serverListMgr.updateCurrentServerAddr(currentServerAddr);
配置和服务的一致性协议有所区别， 配置中心应该是尽可能保证访问到同一个节点上，注册中心可以随机分配。

因此这个逻辑之前时放在agent里和proxy里，没有放在地址服务器里。

既然这次是重构地址服务器，就不要改动外层agent和proxy的逻辑。

2024-08-01 05:48 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> -
请使用nacos codestyle来reformat code，  不要修改缩进

2024-08-01 05:48 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/serverlist/ServerListManager.java
> +        NamingHttpClientManager.getInstance().shutdown();
地址服务器应该处于更底层的逻辑，依赖NamingHttpClientManager可能不是很合适。
以及日志也打印在NAMING_LOGGER也不是很合适，

日志可以打印到REMOTE_LOGGER里， http访问可以通过NacosRestTemplate来替代。

2024-08-01 05:48 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/serverlist/holder/NacosServerListHolders.java
> +                throw new NacosLoadException("serverList is empty,please check configuration");
可以将NacosServerListHolder对应的class或name包含在异常中。这样提示信息能看到是目前是哪个类型被应用了，但是没获取到服务列表。

2024-08-01 05:48 UTC, KomachiSion commented on console/src/main/resources/application.properties
> + db.password=118756
本地配置不用一起提交

2024-08-01 07:19 UTC, XiaZhouxx commented on client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
> -                    serverListMgr.updateCurrentServerAddr(currentServerAddr);
> 配置和服务的一致性协议有所区别， 配置中心应该是尽可能保证访问到同一个节点上，注册中心可以随机分配。
> 
> 因此这个逻辑之前时放在agent里和proxy里，没有放在地址服务器里。
> 
> 既然这次是重构地址服务器，就不要改动外层agent和proxy的逻辑。

是的, 这里在重试`genNextServer()`找到可用Server后下标固定还是这个Server, 所以移除了`updateCurrentServerAddr()`, 注册中心则还是沿用以前的逻辑在构建时随机指定了一个下标。

2024-08-01 07:41 UTC, XiaZhouxx commented on client/src/main/java/com/alibaba/nacos/client/serverlist/ServerListManager.java
> +        NamingHttpClientManager.getInstance().shutdown();
> 地址服务器应该处于更底层的逻辑，依赖NamingHttpClientManager可能不是很合适。 以及日志也打印在NAMING_LOGGER也不是很合适，
> 
> 日志可以打印到REMOTE_LOGGER里， http访问可以通过NacosRestTemplate来替代。

是的, 作为底层逻辑不应该依赖上层业务 我更正一下

2024-08-01 08:00 UTC, XiaZhouxx commented
> 感觉上问题已经快收敛完了， 再看下评论进行一次修改。
> 
> 另外有一个问题可以思考下：
> 
> moduleName时通过单独的参数传递进去还是方properties里比较好？ 我感觉放properties有一点晦涩，直接传进去是不是明显一点。

确实, 看一下是有点晦涩，这个属性我觉得应该是必要属性要依赖方感知和设置这个属性,  放properties的话貌似还需要去理解上下文这个属性的作用, 假设另一个模块引用的话可能是不知道这个属性的.

2024-08-01 12:35 UTC, XiaZhouxx commented
更正了一版, 对于`ServerHttpAgent`的改动之前有些问题 这里修复了, 配置中心保持一个访问同一只可访问的server的逻辑是保留了的,在`genNextServer()`内部就已经修改当前服务下标并返回的, 之前是采用的迭代器方式才额外调用了方法修改当前服务. @KomachiSion 也麻烦大佬有空了看一下有什么问题

2024-08-05 01:45 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
> +        metric.put("isFixedServer", FixedConfigNacosServerListHolder.NAME.equals(serverListHolderName));
使用方还需要感知类型不太好。

2024-08-05 01:48 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
> +
请勿修改缩进。

2024-08-05 01:51 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> +
缩进问题请全部检查一下

2024-08-05 01:54 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java
> +    public static String initContextPath(NacosClientProperties properties) {
这个方法名最好叫initEndpointContextPath，不然之后的开发者可能会误解。

2024-08-05 03:01 UTC, KomachiSion commented
@XiaZhouxx 您好， 我收到主办方的消息， 说您的PR没有在活动官网上登记， 这样的话这个PR不算是有效的参赛PR，

方便抽空把报名信息在官网上填写一下。

https://tianchi.aliyun.com/competition/entrance/532215/information?spm=a2c22.12281976.0.0.41ab6c71nLISOm

2024-08-05 04:22 UTC, XiaZhouxx commented
> @XiaZhouxx 您好， 我收到主办方的消息， 说您的PR没有在活动官网上登记， 这样的话这个PR不算是有效的参赛PR，
> 
> 方便抽空把报名信息在官网上填写一下。
> 
> https://tianchi.aliyun.com/competition/entrance/532215/information?spm=a2c22.12281976.0.0.41ab6c71nLISOm
> 
> 对填写有疑问也可以发邮件到 [wb-zbh593637@alibaba-inc.com](mailto:wb-zbh593637@alibaba-inc.com) 询问。

收到， 已经填报PR, 代码也重新格式化排版 @KomachiSion 也烦请大佬抽空看一下

2024-08-07 05:59 UTC, KomachiSion reviewed
目前初步review似乎没有太大的问题了， 之后会在活动截止前对PR进行整体评判后决定是否合入。

我先跑一下CI，请关注一下结果，避免后续需要合入时由于CI问题被阻塞。

2024-08-07 07:35 UTC, XiaZhouxx commented
> 目前初步review似乎没有太大的问题了， 之后会在活动截止前对PR进行整体评判后决定是否合入。
> 
> 我先跑一下CI，请关注一下结果，避免后续需要合入时由于CI问题被阻塞。

好的, 辛苦了

2024-08-07 10:11 UTC, XiaZhouxx commented
@KomachiSion 抱歉大佬有几个文件没有添加`licenses`, 麻烦再跑下呢

2024-10-15 02:14 UTC, KomachiSion commented
根据最后的评分结果， https://github.com/alibaba/nacos/pull/12274 会被合并入主干分支，

感谢参赛同学的贡献，该PR也有很多可取之处， 欢迎继续贡献此模块内容，将这部分内容优化的更好。

2024-10-15 02:14 UTC, closed without merging