[ISSUE #12017] Split console authentication
alibaba/nacos pull request #12474
Opened 2024-08-07 10:13 UTC by RickonZhang0929

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

For #12017

Split console authentication.

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-08-12 02:33 UTC, KomachiSion reviewed
It seems no relative with auth？

2024-08-13 05:17 UTC, RickonZhang0929 commented
> It seems no relative with auth？

This one is for testing commits, I'll fix this change

2024-08-15 01:44 UTC, KomachiSion requested changes

2024-08-15 01:44 UTC, KomachiSion commented on auth/src/main/java/com/alibaba/nacos/auth/AbstractProtocolAuthService.java
> +    public boolean authEnabled(Secured secured) {
和上述的enableAuth区别是什么？

是不是应该放到NacosAuthPluginService的enableAuth里？

2024-08-15 01:44 UTC, KomachiSion commented on auth/src/main/java/com/alibaba/nacos/auth/ProtocolAuthService.java
> +    boolean authEnabled(Secured secured);
和上一个enable auth看起来重复，让插件开发和摸不着头脑

2024-08-15 01:44 UTC, KomachiSion commented on auth/src/main/java/com/alibaba/nacos/auth/enums/ApiType.java
> +    ADMIN_API("ADMIN_API"),
我想了一下， 这里可能改叫CONSOLE_API比较好

2024-08-15 01:44 UTC, KomachiSion commented on auth/src/main/java/com/alibaba/nacos/auth/enums/ApiType.java
> +    ADMIN_API("ADMIN_API"),
因为之后可能会单独出maintainer sdk访问admin api，同时拆分部署后console访问server的api可能才叫ADMIN API

所以我想目前的叫CONSOLE_API

当然之后统一改也可以

2024-08-15 01:44 UTC, KomachiSion commented on core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
> +                if (!protocolAuthService.authEnabled(secured)) {
和前面描述的一样，不再赘述

2024-08-27 07:59 UTC, KomachiSion approved these changes

2024-08-27 07:59 UTC, merged