[ISSUE #12466]  serviceMetadata environment variables config
alibaba/nacos pull request #12477
Opened 2024-08-08 12:58 UTC by fuhouyu

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

resolves #12466
增加serviceMetadata的环境变量配置： NACOS_NAMING_SERVICE_METADATA_LENGTH

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-08-09 06:27 UTC, KomachiSion requested changes
另外麻烦在 

https://github.com/nacos-group/nacos-group.github.io/blob/develop-astro-nacos/src/content/docs/next/zh-cn/manual/user/parameters-check.md

中添加相关说明

2024-08-09 06:27 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/paramcheck/DefaultParamChecker.java
> +
不要修改缩进， 请使用nacos code style进行格式化

2024-08-09 14:16 UTC, fuhouyu commented on common/src/main/java/com/alibaba/nacos/common/paramcheck/DefaultParamChecker.java
> +
好的老师，晚点我修改下，这个没注意。～

2024-08-12 01:59 UTC, KomachiSion approved these changes

2024-08-12 01:59 UTC, merged