[ISSUE #12483] Configuration list adds configuration format
alibaba/nacos pull request #12491
Opened 2024-08-15 08:33 UTC by tonycody

issue: #12483

2024-08-16 05:32 UTC, Nftcollecte requested changes

2024-08-16 05:32 UTC, Nftcollecte commented on common/src/main/java/com/alibaba/nacos/common/constant/Symbols.java
> +/*
Gm

2024-08-17 05:46 UTC, tonycody commented on common/src/main/java/com/alibaba/nacos/common/constant/Symbols.java
> +/*
Not sure what it means? Please explain.

2024-08-19 02:21 UTC, KomachiSion approved these changes

2024-08-19 02:21 UTC, merged