[ISSUE #12017] Add the console backend API for config section
alibaba/nacos pull request #12553
Opened 2024-08-26 10:13 UTC by RickonZhang0929

## What is the purpose of the change

For [12017](https://github.com/alibaba/nacos/issues/12017)

Add the console backend API for config section

## Brief changelog

* Add history handling module

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2024-08-28 11:59 UTC, KomachiSion requested changes
统一检查一下Secured注解是不是都漏了apiType

2024-08-28 11:59 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/auth/ConsolePermissionController.java
> +public class ConsolePermissionController {
Permission, User, Role controller should be in auth plugin module, should not in console module.
Because these api is from optional plugin

2024-08-28 11:59 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleHistoryController.java
> +    @Secured(action = ActionTypes.READ, signType = SignType.CONFIG)
ApiType是不是漏了？

2024-08-28 11:59 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleHistoryController.java
> +    public Result<List<ConfigInfoWrapper>> getConfigsByTenant(@RequestParam("namespaceId") String namespaceId)
这个接口是干什么的？

2024-08-28 11:59 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleClusterController.java
> +    public Result<String> updateCluster(HttpServletRequest request) throws Exception {
这两个接口不是一个类型吧， updateCluster应该是naming模块的，更新服务下cluster元数据的。

前者应该是core模块的，获取nacos节点的信息吧？

2024-08-28 12:00 UTC, KomachiSion commented
另外， 有的接口是Form对象，有的接口是独立RequestParameter列举， 看下是不是能统一一下。

2024-08-30 13:08 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleHistoryController.java
> +    @Secured(action = ActionTypes.READ, signType = SignType.CONFIG)
当时没加，现在均已添加

2024-08-30 13:10 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleHistoryController.java
> +    public Result<List<ConfigInfoWrapper>> getConfigsByTenant(@RequestParam("namespaceId") String namespaceId)
这个是历史查询里，在查询框下拉显示配置列表的接口，可以直接选择对应的配置项

2024-08-30 13:16 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleClusterController.java
> +    public Result<String> updateCluster(HttpServletRequest request) throws Exception {
确实有误， updateCluster应该是naming模块的

2024-08-30 13:29 UTC, RickonZhang0929 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleClusterController.java
> +    public Result<String> updateCluster(HttpServletRequest request) throws Exception {
我将updateCluster放入了ConsoleServiceController中

2024-08-31 02:06 UTC, Dannyss18 approved these changes

2024-08-31 02:06 UTC, Dannyss18 commented on console/src/main/java/com/alibaba/nacos/console/controller/v3/auth/ConsolePermissionController.java
> +    @GetMapping("/list")
Monetizar

2024-09-04 06:41 UTC, KomachiSion approved these changes

2024-09-04 06:42 UTC, merged