upgrade springboot version to 3.4.0
alibaba/nacos pull request #12927
Opened 2024-12-06 02:07 UTC by JianweiWang

支持native image，升级springboot版本为3.4.0

2025-01-06 07:59 UTC, KomachiSion requested changes

2025-01-06 07:59 UTC, KomachiSion commented on client/pom.xml
> +                                    <!-- <filter> -->
这段移除会不会对nacos-client的shaded输出有影响啊？

2025-01-06 10:44 UTC, Dario-s-j commented
Ok

Em seg., 6 de jan. de 2025, 05:00, 杨翊 SionYang ***@***.***>
escreveu:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In client/pom.xml
> <https://github.com/alibaba/nacos/pull/12927#discussion_r1903796181>:
>
> > @@ -149,14 +151,14 @@
>                                              <exclude>**/module-info.class</exclude>
>                                          </excludes>
>                                      </filter>
> -                                    <filter>
> -                                        <artifact>io.grpc:grpc-netty-shaded</artifact>
> -                                        <excludes>
> -                                            <exclude>
> -                                                META-INF/native/*.*
> -                                            </exclude>
> -                                        </excludes>
> -                                    </filter>
> +                                    <!-- <filter> -->
>
> 这段移除会不会对nacos-client的shaded输出有影响啊？
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alibaba/nacos/pull/12927#pullrequestreview-2531554879>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4MT7RGJORVSAQGLUUFDMPD2JIZYNAVCNFSM6AAAAABTDXO35KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMZRGU2TIOBXHE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-01-07 08:23 UTC, closed without merging

2025-01-07 11:15 UTC, Dario-s-j commented
Ok

Em ter., 7 de jan. de 2025, 05:23, 杨翊 SionYang ***@***.***>
escreveu:

> Closed #12927 <https://github.com/alibaba/nacos/pull/12927>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alibaba/nacos/pull/12927#event-15835252723>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4MT7RFKORVBA4MR64YKCUD2JOFI3AVCNFSM6AAAAABTDXO35KVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJVHAZTKMRVGI3TEMY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>