fix: #3617
alibaba/nacos pull request #3678
Opened 2020-08-25 02:16 UTC by KeRan213539

fix: #3617

2020-08-25 02:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=3678) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=3678) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=3678) it.</sub>

2020-09-01 02:29 UTC, chuntaojun requested changes

2020-09-01 02:29 UTC, chuntaojun commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/BaseDatabaseOperate.java
> +    /**
这个方法没有用到就删除吧

2020-09-01 02:29 UTC, chuntaojun commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/BaseDatabaseOperate.java
> +    default Boolean update(TransactionTemplate transactionTemplate, JdbcTemplate jdbcTemplate,
标注下是为了修复哪一个issue而改动的吧

2020-09-01 03:35 UTC, chuntaojun submitted a review, later dismissed

2020-09-01 06:52 UTC, KomachiSion approved these changes

2020-09-03 13:14 UTC, merged