fix #3710
alibaba/nacos pull request #3714
Opened 2020-08-28 06:52 UTC by zzq1314zll

fix #3710

2020-08-28 09:32 UTC, KomachiSion requested changes

2020-08-28 09:32 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java
> +        now = URLEncoder.encode(now, encode);
encode before decode? 
it it right?

2020-08-28 14:12 UTC, zzq1314zll commented on common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java
> +        now = URLEncoder.encode(now, encode);
right

2020-09-14 01:55 UTC, KomachiSion commented
@zzq1314zll I think the implementation is not right. encode before decode will caused the result is error.

![image](https://user-images.githubusercontent.com/37170243/93035733-689b4e00-f670-11ea-8d09-36baf4fb683d.png)

2020-09-17 08:53 UTC, closed without merging