IPv6 support
alibaba/nacos pull request #3773
Opened 2020-09-07 07:40 UTC by KeRan213539

https://www.yuque.com/docs/share/864a401b-e905-4dda-9e6f-72c0c127b811?#（密码：yrol） 《Nacos支持ipv6网络环境的改造》

2020-09-07 08:16 UTC, KomachiSion requested changes

2020-09-07 08:16 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/Instance.java
> +            // not ip:port string
Is the same behavior when provider without port like `11.11.11.11` ?

2020-09-07 08:16 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/IpUtil.java
> +        return splitIpPortStr(address).length == 2;
Can `2` replaced with `SPLIT_IP_PORT_RESULT_LENGTH`

2020-09-07 08:16 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
> +                    if (containedInstanceIpPort.length == IpUtil.SPLIT_IP_PORT_RESULT_LENGTH) {
replaced with `IpUtil.containPort`?

2020-09-07 10:52 UTC, KomachiSion requested changes

2020-09-07 10:52 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/Instance.java
> +        if (NumberUtils.isNumber(providerAddr[1])) {
possible for OutOfIndexException？

2020-09-08 01:50 UTC, KomachiSion submitted a review, later dismissed

2020-09-08 02:11 UTC, KomachiSion requested changes

2020-09-08 02:11 UTC, KomachiSion commented on common/src/test/java/com/alibaba/nacos/common/utils/IpUtilTest.java
> +    public void test111(){
format test method name to describe what situation the method test

2020-09-08 02:11 UTC, KomachiSion commented on common/src/test/java/com/alibaba/nacos/common/utils/IpUtilTest.java
> +                        /* && ip.isSiteLocalAddress() */) {
remove unused codes

2020-09-08 02:19 UTC, KomachiSion approved these changes

2020-09-08 02:27 UTC, chuntaojun commented on address/src/main/java/com/alibaba/nacos/address/controller/AddressServerClusterController.java
> +            if (IpUtil.CHECK_OK.equals(checkResult)) {
IpUtil.checkOK(str) I think is better

2020-09-08 02:27 UTC, chuntaojun commented on common/src/main/java/com/alibaba/nacos/common/tls/SelfHostnameVerifier.java
> +    private static final String[] LOCALHOST_HOSTNAME = new String[] {"localhost", IpUtil.localHostIp()};
Ip => IP

2020-09-08 02:27 UTC, chuntaojun commented on common/src/main/java/com/alibaba/nacos/common/utils/IpUtil.java
> +public class IpUtil {
IpUtil => IPUtil

2020-09-08 03:08 UTC, wangweizZZ commented on client/src/main/java/com/alibaba/nacos/client/config/utils/ParamUtils.java
> +            if (!IpUtil.isIpv4(ip)) {
这种地方现在是不是应该用isIp替换isIpv4了？

2020-11-03 07:35 UTC, KeRan213539 commented on core/src/main/java/com/alibaba/nacos/core/utils/WebUtils.java
> +        } catch (Exception ex) {
解决重复decode的问题

2020-11-04 02:48 UTC, Maijh97 commented on core/src/main/java/com/alibaba/nacos/core/utils/WebUtils.java
> +
Please do not change the code style.

2020-11-04 02:48 UTC, Maijh97 commented on naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
>                          if (StringUtils.equals(instance.getIp() + ":" + instance.getPort(), containedInstance)) {
Here ":" can use IPUtil.IP_PORT_SPLITER.

2020-11-04 02:48 UTC, Maijh97 commented on naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
> +            String url = "http://" + IPUtil.localHostIP() + ":" + ApplicationUtils.getPort() + ApplicationUtils.getContextPath()
Here ":" can use IPUtil.IP_PORT_SPLITER.

2020-11-04 02:48 UTC, Maijh97 commented on sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java
> +
Please do not change the code style.

2020-11-04 02:48 UTC, Maijh97 commented on sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java
> +
Please do not change the code style.

2020-11-04 02:48 UTC, Maijh97 commented on sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java
> +                                    && isPreferredAddress(address)) {
`IPUtil.PREFER_IPV6_ADDRESSES ? address instanceof Inet6Address : address instanceof Inet4Address`  
Here is a separate line, which is more readable.

2020-11-05 12:14 UTC, KomachiSion approved these changes

2020-11-05 12:15 UTC, merged