feature issue #3804
alibaba/nacos pull request #3805
Opened 2020-09-11 07:03 UTC by chuntaojun

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

#3804 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2020-09-11 07:45 UTC, KomachiSion requested changes

2020-09-11 07:45 UTC, KomachiSion commented on sys/src/main/java/com/alibaba/nacos/sys/Main.java
> +public class Main {
What's the reason create this class?

2020-09-11 07:45 UTC, KomachiSion commented on sys/src/main/java/com/alibaba/nacos/sys/env/NacosDefaultPropertySourceEnvironmentPostProcessor.java
> + *  Copyright 1999-2018 Alibaba Group Holding Ltd.
Why change the indentation of lecense?

2020-09-11 07:45 UTC, KomachiSion commented on console/src/main/resources/application.properties
> +spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
Why exclude these classes？

2020-09-11 07:45 UTC, KomachiSion commented on sys/src/main/java/com/alibaba/nacos/sys/env/NacosAutoRefreshPropertySourceLoader.java
> +    static class OriginTrackedPropertiesLoader {
I found this inner class only used in current class line 97. And each time create a new one. Can this inner class refactor to some private method.

If there are other same package class need this class. Whether extract as an single class will be better?

2020-09-11 07:45 UTC, KomachiSion commented on sys/src/main/java/com/alibaba/nacos/sys/env/NacosDefaultPropertySourceEnvironmentPostProcessor.java
> +            ResourcePatternResolver.CLASSPATH_ALL_URL_PREFIX + "META-INF/nacos-default.properties";
This file has been deleted?

2020-09-11 07:45 UTC, chuntaojun commented on sys/src/main/java/com/alibaba/nacos/sys/Main.java
> +public class Main {
already remove, wait next comit

2020-09-11 07:45 UTC, chuntaojun commented on sys/src/main/java/com/alibaba/nacos/sys/env/NacosDefaultPropertySourceEnvironmentPostProcessor.java
> + *  Copyright 1999-2018 Alibaba Group Holding Ltd.
already fix

2020-09-18 08:01 UTC, KomachiSion approved these changes

2020-09-18 08:05 UTC, merged