[ISSUE #3850] ignore socket exception when client destroy already
alibaba/nacos pull request #3906
Opened 2020-09-24 05:39 UTC by horizonzy

## What is the purpose of the change
fix-#3850

2020-09-24 12:48 UTC, KomachiSion requested changes
I think check `updSocket.isClose` before receive or send will be better.

If `updSocket.isClose` is true, directly return;

also check `close` in pushReceiver is ok.

2020-09-24 13:50 UTC, horizonzy commented
> I think check `updSocket.isClose` before receive or send will be better.
> 
> If `updSocket.isClose` is true, directly return;
> 
> also check `close` in pushReceiver is ok.

check updSocket.isClose before receive is unuseful, because it blocked. the judge will not work. before send check is necessary

2020-09-25 01:17 UTC, KomachiSion commented
> > I think check `updSocket.isClose` before receive or send will be better.
> > If `updSocket.isClose` is true, directly return;
> > also check `close` in pushReceiver is ok.
> 
> check `updSocket.isClose` before receive is unuseful most of the time, if `udpSocket.receive(packet);` already execute, the exception will occur still, so the judge logic in catch code block is necessary. if this code exist, it will cover the check situation

You are right, from this point, I think there are is no need to judgement the exception type. Because if closed means the PushReceiver has been shutdown, Any exception can be ignored.

2020-09-25 11:21 UTC, KomachiSion approved these changes

2020-09-30 05:14 UTC, merged