[ISSUE #3904] feature - operate instance's metadata alonely
alibaba/nacos pull request #3912
Opened 2020-09-25 03:35 UTC by horizonzy

## What is the purpose of the change
#3904

2020-09-25 11:29 UTC, KomachiSion commented
@horizonzy I think the API can be move to InstanceController
@chuntaojun What's your think about?

2020-09-26 04:01 UTC, horizonzy commented
> @horizonzy I think the API can be move to InstanceController

it should be move to InstanceController

2020-09-28 02:01 UTC, horizonzy commented
update demo: `curl -X PUT 'http://localhost:8848/nacos/v1/ns/instance/metadata/batch?namespaceId=public' -d 'metadata={"age":"20","name":"cocolan"}&namespace=public&target=[{"serviceName":"xxxx@@xxxx","instances":[{"ip":"127.0.0.1","port": "8080","ephemeral":"true","clusterName":"xxxx-cluster"},{"ip":"2.2.2.2","port":"8888","ephemeral":"true","clusterName":"xxx-cluster"}]},{"serviceName":"yyyy@@yyyy", "all":"ephemeral"}]'`

2020-09-28 02:01 UTC, horizonzy commented
delete demo:`curl -X DELETE 'http://localhost:8848/nacos/v1/ns/instance/metadata/batch?namespaceId=public' -d 'metadata={"age":"20","name":"cocolan"}&namespace=public&target=[{"serviceName":"xxxx@@xxxx","instances":[{"ip":"127.0.0.1","port": "8080","ephemeral":"true","clusterName":"xxxx-cluster"},{"ip":"2.2.2.2","port":"8888","ephemeral":"true","clusterName":"xxx-cluster"}]},{"serviceName":"yyyy@@yyyy", "all":"ephemeral"}]'`

2020-09-28 03:09 UTC, chuntaojun commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +    public static String required(final Map<String, String> param, final String key) {
Map的操作放到MapUtils里面

2020-09-28 03:09 UTC, chuntaojun commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +    public static String optional(final Map<String, String> param, final String key, final String defaultValue) {
Map的操作放到MapUtils里面

2020-09-28 03:09 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +            return JacksonUtils.toObj(instances, new TypeReference<List<Map>>() {
TypeReference<List<Map>>这个变量是不是可以考虑static化

2020-09-28 03:09 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +    private void batchOperate(String namespace, List<Map> services, Consumer<OperationContext> consumer) {
考虑下沉到ServiceManager

2020-09-28 03:09 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/pojo/OperationContext.java
> +public class OperationContext {
建议调整为InstanceOperationContext，不然可能还会有ServiceOperationContext

2020-09-28 04:54 UTC, horizonzy commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +    public static String required(final Map<String, String> param, final String key) {
right.

2020-09-28 04:56 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +    private void batchOperate(String namespace, List<Map> services, Consumer<OperationContext> consumer) {
这个还是不下沉到ServiceManager，ServiceManager只是对内部instances进行操作。但是这个操作的方式具体怎么操作应该在外部定义。serviceManager只提供操作资源的方式，外部进行整合

2020-09-28 04:56 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/pojo/OperationContext.java
> +public class OperationContext {
right

2020-09-28 05:03 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +            return JacksonUtils.toObj(instances, new TypeReference<List<Map>>() {
自我感觉没必要。这个生命周期很短。单独放在外面static还额外占空间，还不好看

2020-09-28 05:57 UTC, Maijh97 commented on naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
> +            locatedInstance = ((Instances) datum.value).getInstanceList();
这里的datum， 需要注意一下为null的情况

2020-09-28 06:05 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
> +            locatedInstance = ((Instances) datum.value).getInstanceList();
对的。有可能，service中存在持久化instances，如果操作的是非持久化的instance，可能会空

2020-09-28 07:11 UTC, chuntaojun requested changes

2020-09-28 07:11 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +            return JacksonUtils.toObj(instances, new TypeReference<List<Map>>() {
不建议使用List<Map>这种Value值不明确的情况，建议单独创建一个Object进行描述，否则可读性是一个问题，也可能容易出现CaseException问题

2020-09-28 07:26 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +    private void batchOperate(String namespace, List<Map> services, Consumer<InstanceOperationContext> consumer) {
后面Controller我希望优化掉现有代码的形式，controller这里出现了太多无关的逻辑，所以建议这个pr遵循一下，非controller层面的逻辑，尽量不要出现

2020-09-28 08:10 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +    private void batchOperate(String namespace, List<Map> services, Consumer<InstanceOperationContext> consumer) {
可以把。那我这一版就重构一下，下沉到manager层。

2020-09-28 08:12 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +            return JacksonUtils.toObj(instances, new TypeReference<List<Map>>() {
这个我考虑过。如果后续操作pojo不能复用的话，pojo就会越来越多了

2020-09-29 01:37 UTC, Maijh97 commented on naming/src/main/java/com/alibaba/nacos/naming/pojo/InstanceOperationInfo.java
> +    private String all;
` private String all;`  建议重新修改一下这个字段的命名，目前这个字段的命名如果单纯通过字段名称很难判断具体代表的含义，我认为是不是为`consistencyType`或者`type` 或者有更好的其它的名称。

2020-09-29 02:38 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +        Consumer<InstanceOperationContext> operateConsumer = instanceOperationContext -> {
如果说batchOperate想利用函数做可自定义的操作，那么Consumer应该换成BiConsumer，传入参数以及实际的操作执行者

2020-09-29 05:12 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +        Consumer<InstanceOperationContext> operateConsumer = instanceOperationContext -> {
BiConsumer<param, Consumer>，第二个参数就是业务Consumer这种？

2020-09-29 06:59 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/pojo/InstanceOperationInfo.java
> +    private String all;
嗯。用consistencyType

2020-09-29 10:25 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/pojo/InstanceOperationInfo.java
> +    private String all;
不过这个和 @HaojunRen 沟通下，昨天给的那一版参数用的是all，他那边应该openApi用的应该是all参数用来集成的。

2020-09-30 04:47 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +    public ObjectNode batchUpdateInstanceMatadata(HttpServletRequest request) throws Exception {
专门一个返回体处理吧，后面将要统一处理掉这种不统一的返回格式

2020-09-30 04:47 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
> +                        operatedInstances.addAll(operateFunction.apply(operationContext));
这个方法四个case都有，可以拿出来

2020-09-30 04:47 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/pojo/InstanceOperationContext.java
> +    public void allEphemeralOperate() {
如果这个方法改的的参数只能改动一次，则最好放在构造函数里面去做，否则这个方法暴露出去太危险，

2020-09-30 04:47 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/pojo/InstanceOperationInfo.java
> +public class InstanceOperationInfo {
同理，这里面的参数是否有涉及是需要final的，如果是那么就不要暴露set方法了

2020-09-30 12:54 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +    public ObjectNode batchUpdateInstanceMatadata(HttpServletRequest request) throws Exception {
下一次单独新开一个pr，统一处理controller的返回数据结构

2020-09-30 14:42 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +            return JacksonUtils.toObj(instances, new TypeReference<List<Map>>() {
@zongtanghu @KomachiSion @KeRan213539 What do you think

2020-10-02 06:12 UTC, chuntaojun submitted a review, later dismissed

2020-10-02 06:19 UTC, paderlol commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +                .optional(request, CommonParams.NAMESPACE_ID, Constants.DEFAULT_NAMESPACE_ID);
Controller里面的逻辑是否应该下沉一下更好？虽然我们之前的Controller确实还有这个问题

2020-10-02 07:40 UTC, KeRan213539 commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +            return JacksonUtils.toObj(instances, new TypeReference<List<Map>>() {
@chuntaojun 我觉得还是定义个pojo好一些,这样既能明确有些什么属性不至于混乱, 也能对提交的数据做一些过滤和校验

2020-10-02 16:29 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +                .optional(request, CommonParams.NAMESPACE_ID, Constants.DEFAULT_NAMESPACE_ID);
单独提一个pr来做这个事情吧。

2020-10-04 08:36 UTC, jiangxch commented on naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
> +
为什么要把clusterName不同的给移除出去呢 @horizonzy 大神能否解答下

2020-10-05 15:51 UTC, chuntaojun commented
最后补一个集成测试吧，总体应该可以先merge

2020-10-12 03:26 UTC, KomachiSion submitted a review, later dismissed

2020-10-12 03:28 UTC, KomachiSion commented
@horizonzy Can you update documents in https://github.com/nacos-group/nacos-group.github.io?

2020-10-12 04:30 UTC, horizonzy commented
> https://github.com/nacos-group/nacos-group.github.io

yes

2020-10-15 01:25 UTC, KomachiSion requested changes

2020-10-15 01:25 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +     * @throws Exception any error during update
Please add `@since 1.4.0`

2020-10-15 01:25 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +     * @throws Exception any error during update
Please add `@since 1.4.0`

2020-10-15 01:35 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
> +     * @throws Exception any error during update
solve it

2020-10-15 09:21 UTC, KomachiSion approved these changes

2020-10-19 08:32 UTC, merged