Fix#3973
alibaba/nacos pull request #3974
Opened 2020-10-12 07:01 UTC by KeRan213539

Fix#3973

2020-10-12 08:30 UTC, KomachiSion requested changes

2020-10-12 08:30 UTC, KomachiSion commented on config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> +     * @author klw(213539@qq.com)
method do not need author

2020-10-12 08:30 UTC, KomachiSion commented on config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> +     * @return java.lang.String
return annotation should describe what content method return, only type is not useful

2020-10-12 08:49 UTC, KomachiSion approved these changes

2020-10-13 06:43 UTC, chuntaojun approved these changes

2020-10-13 07:36 UTC, chuntaojun approved these changes

2020-10-13 07:48 UTC, KomachiSion approved these changes

2020-10-13 07:48 UTC, merged