[ISSUE-#3855] Provided a feature to view version comparisons in the configDetails page
alibaba/nacos pull request #3988
Opened 2020-10-14 06:26 UTC by jzhishu

## What is the purpose of the change

#3855

## Brief changelog

- In the configDetails page, you can click the "Version Comparison" button to open the configuration content version comparison

2020-10-14 06:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=3988) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=3988) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: horizonzy<br/>:x: jzhishu<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=3988) it.</sub>

2020-10-14 07:09 UTC, KomachiSion approved these changes

2020-10-14 07:11 UTC, KomachiSion commented
@jzhishu Can you add some unit test or integration test for your changes?

2020-10-14 07:16 UTC, jzhishu commented
> @jzhishu Can you add some unit test or integration test for your changes?

Ok, I'll add the test case later

2020-10-15 01:24 UTC, KomachiSion requested changes

2020-10-15 01:24 UTC, KomachiSion commented on config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
> +     * Query previous config history information.
Please add `@since 1.4.0`

2020-10-15 09:18 UTC, KomachiSion submitted a review, later dismissed

2020-10-15 09:21 UTC, loadchange approved these changes

2020-10-15 12:26 UTC, chuntaojun commented
Can you add some pictures to show the final form

2020-10-16 04:22 UTC, jzhishu commented
![image](https://user-images.githubusercontent.com/39545185/96212702-08b70080-0faa-11eb-8a3d-5d94928b8720.png)
![image](https://user-images.githubusercontent.com/39545185/96212733-12d8ff00-0faa-11eb-8b9d-e2d50e67f51e.png)

2020-10-19 01:29 UTC, KomachiSion approved these changes

2020-10-19 01:30 UTC, merged