[ISSUE-#4134] check namespace is exist when request naming api or config api
alibaba/nacos pull request #4161
Opened 2020-11-06 15:58 UTC by horizonzy

## What is the purpose of the change
issue-#4134

2020-11-09 02:39 UTC, KomachiSion requested changes
We may replace all tenantId with namespaceId in future. So I think use namespaceId as method name is better.

2020-11-09 02:39 UTC, KomachiSion commented on console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java
> +        namespaceService.addTenantId(namespaceId);
replace method name by addNamespaceId?

2021-01-06 10:12 UTC, CaiJiHuzhuo commented
move console/NamespaceController.java to naming module, then config module adds two api(add,delete). when namespace change，use Http send namespaceId update data to config module.
The namespaceId is stored in both the name and config modules.
check namespaceId exists in memory.

2021-01-06 10:31 UTC, horizonzy commented
> move console/NamespaceController.java to naming module, then config module adds two api(add,delete). when namespace change，use Http send namespaceId update data to config module.
> The namespaceId is stored in both the name and config modules.
> check namespaceId exists in memory.

Why move NamespaceController to naming module and config module? Run one module alonely?

2021-03-03 09:22 UTC, horizonzy commented
This feature will be moved to 2.x, so close it.

2021-03-03 10:14 UTC, closed without merging