Fix issue 4187
alibaba/nacos pull request #4205
Opened 2020-11-11 12:18 UTC by chuntaojun

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fixed previous bad modification logic

## Brief changelog

fix issue #4187 

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2020-11-11 13:42 UTC, KomachiSion requested changes
The changes in JRaftServerTest.java has some trouble.

2020-11-11 14:15 UTC, KeRan213539 commented on core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftServerTest.java
> +=======
这个类好多冲突标记需要解决下

2020-11-14 02:18 UTC, Maijh97 approved these changes

2020-11-14 06:10 UTC, KomachiSion approved these changes

2020-11-14 06:12 UTC, merged