[ISSUE #4225]  Replace http client in HttpHealthCheckProcessor
alibaba/nacos pull request #4244
Opened 2020-11-17 07:12 UTC by Maijh97

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix: #4225 

## Brief changelog

Remove the `com.ning Async HTTP client` and replace it with a unified HTTP client.

## Verifying this change

1. Register a persistent service
2. Use HTTP health checks
3. Health check normal

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2020-11-17 07:35 UTC, KomachiSion requested changes

2020-11-17 07:35 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
> +                        .setDefaultIOReactorConfig(ioReactorConfig)
use getIoReactorConfig directly, no need to use attribute.

2020-11-17 12:41 UTC, KomachiSion submitted a review, later dismissed

2020-11-17 16:38 UTC, chuntaojun commented on naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClientManager.java
> +    private static class ProcessorHttpClientFactory extends AbstractHttpClientFactory {
这里的参数应当后面可以对外可配置化的，而不是写死的

2020-11-18 02:25 UTC, sanxun0325 submitted a review, later dismissed

2020-11-18 12:53 UTC, KomachiSion requested changes

2020-11-18 12:53 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClientManager.java
> +        private static final int CONNECTION_REQUEST_TIMEOUT = EnvUtil
Static final variable get from properties? Static final means that it's a constants. Should not be configed.

2020-11-18 12:53 UTC, KomachiSion commented on sys/src/main/java/com/alibaba/nacos/sys/env/Constants.java
> +    String NAMING_PERSISTENT = "nacos.naming.persistent";
Naming Constants should not be in parent module.

2020-11-19 01:20 UTC, KomachiSion approved these changes

2020-11-19 11:07 UTC, merged