[ISSUE #4136] Fix the bug that cann't correctlly instantiate ServiceInfo from cache file
alibaba/nacos pull request #4249
Opened 2020-11-17 18:42 UTC by shizhengxing

Please do not create a Pull Request without creating an issue first.
#4136 
#4183 

## What is the purpose of the change
按造#4183中讨论的要求重新修改提交

2020-11-18 01:29 UTC, KomachiSion requested changes

2020-11-18 01:29 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
> +
remove unused blank line. Thanks.

2020-11-18 01:29 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
> +				return key;
can return getKey() directly. do not define a variable if no use it.

2020-11-18 01:29 UTC, KomachiSion commented on api/src/test/java/com/alibaba/nacos/api/naming/pojo/ServiceInfoTest.java
> +
Please use nacos code style to reformat. 

you can see relative information in source code `style/codeStyle.md`

2020-11-18 01:31 UTC, KomachiSion commented
@shizhengxing The CI failed, error is check style can't pass, please take some time to solve it. detail see source code `style/codeStyle.md`. 
Thanks.

2020-11-18 12:42 UTC, KomachiSion requested changes
Please use load nacos code style to reformat your changes.

If the code style and check style can't pass, we will refuse this PR.

2020-11-18 12:48 UTC, shizhengxing commented
> Please use load nacos code style to reformat your changes.
> 
> If the code style and check style can't pass, we will refuse this PR.

progressing,gives me more time

2020-11-18 14:14 UTC, shizhengxing commented
@KomachiSion I only changed three files,bug after fetch from nacos repository,It turns as 7 changes!
Will I need close this PR,and open a new one ?I am unfamiliar with how two deal this situation!

2020-11-19 01:10 UTC, sanxun0325 commented on config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImpl.java
> +        List<String> params = new ArrayList<>();
Params might be better defined directly as arrays

2020-11-19 01:10 UTC, sanxun0325 commented on config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java
> +        List<String> params = new ArrayList<>();
Params might be better defined directly as arrays

2020-11-19 01:10 UTC, sanxun0325 commented on config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
> +        List<String> params = new ArrayList<>();
Params might be better defined directly as arrays

2020-11-19 01:10 UTC, sanxun0325 commented on config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java
> +        List<String> params = new ArrayList<>();
Params might be better defined directly as arrays

2020-11-19 01:18 UTC, KomachiSion commented
> @KomachiSion I only changed three files,but after fetch from nacos repository,It turns as 7 changes!
> Will I need to close this PR,and open a new one ?I am unfamiliar with how to deal with this situation
> I need your help!

I found that you merge other change to your PR, so the files increase, If you can use rebase to fix it , you do not need close PR. If you don't know how to use rebase to fix, the best way is checkout a new branch and re-submit PR.

At the next time, Please use nacos code style to reformat so that it can be merged quickly.

2020-11-19 04:10 UTC, shizhengxing commented
> > @KomachiSion I only changed three files,but after fetch from nacos repository,It turns as 7 changes!
> > Will I need to close this PR,and open a new one ?I am unfamiliar with how to deal with this situation
> > I need your help!
> 
> I found that you merge other change to your PR, so the files increase, If you can use rebase to fix it , you do not need close PR. If you don't know how to use rebase to fix, the best way is checkout a new branch and re-submit PR.
> 
> At the next time, Please use nacos code style to reformat so that it can be merged quickly.

OK thanks,I am learning how to use rebase,and I will solve this today.
What's more,I have already learned how to use checkstyle last night,and i was already used it to format this PR's submit.So the CI passed.Thanks!

2020-11-19 08:38 UTC, closed without merging