[ISSUE-#4258]  Fix wrong path when -Dspring.config.location not set
alibaba/nacos pull request #4259
Opened 2020-11-18 11:04 UTC by horizonzy

## What is the purpose of the change

Fix-#4258

2020-11-18 11:52 UTC, chuntaojun commented on sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
> +            InputStream inputStream = new FileInputStream(new File(path + "application.properties"));
new File(path + "application.properties") => Paths.get().toFile()

2020-11-18 12:06 UTC, horizonzy commented on sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
> +            InputStream inputStream = new FileInputStream(new File(path + "application.properties"));
ok

2020-11-19 03:24 UTC, chuntaojun approved these changes

2020-11-19 03:24 UTC, chuntaojun commented on sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
> +            path = EnvUtil.getNacosHome() + "/conf";
use Paths.get(...)

2020-11-19 08:20 UTC, chuntaojun submitted a review, later dismissed

2020-11-19 08:44 UTC, Maijh97 commented on sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
> +            return getRelativePathResource(Paths.get(EnvUtil.getNacosHome(), "conf"));
这个`if (customPath == null)`可以去掉，因为方法结束会`return getRelativePathResource(Paths.get(EnvUtil.getNacosHome(), "conf"));`

2020-11-19 13:30 UTC, Maijh97 approved these changes

2020-11-19 13:34 UTC, Maijh97 requested changes
Solve CI error.

2020-11-19 13:47 UTC, horizonzy commented
> Solve CI error.

I think it's CI mistake

2020-11-20 04:59 UTC, horizonzy commented on sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
> +        if (StringUtils.isNotBlank(path) && path.contains(FILE_PREFIX)) {
现在有个containsIgnoreCase. 可以用这个替换

2020-11-20 05:26 UTC, chuntaojun commented on sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
> +        if (StringUtils.isNotBlank(path) && path.contains(FILE_PREFIX)) {
路径不能IgnoreCase

2020-11-20 05:50 UTC, horizonzy commented on sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
> +        if (StringUtils.isNotBlank(path) && path.contains(FILE_PREFIX)) {
这个只是判断`file:`, 这个大小写忽略ok的

2020-11-20 22:55 UTC, chuntaojun submitted a review, later dismissed

2020-11-22 08:29 UTC, Maijh97 submitted a review, later dismissed

2020-11-23 02:01 UTC, KomachiSion requested changes

2020-11-23 02:01 UTC, KomachiSion commented on sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
> +        if (customResource == null) {
Simply to `null == customResource ? return getDefaultResource() : customResource`

2020-11-23 03:08 UTC, Maijh97 approved these changes

2020-11-23 05:45 UTC, chuntaojun approved these changes

2020-11-25 09:02 UTC, KomachiSion approved these changes

2020-11-25 09:02 UTC, merged