fix service list can not search by groupName only
alibaba/nacos pull request #4302
Opened 2020-11-21 16:17 UTC by mark4z

Fixes #4282

2020-11-22 12:33 UTC, sanxun0325 commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +    public static String getGroupedNameOptional(final String serviceName, final String groupName) {
You can add some comments

2020-11-22 15:00 UTC, mark4z commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +    public static String getGroupedNameOptional(final String serviceName, final String groupName) {
Ok,fine

2020-11-23 01:41 UTC, KomachiSion requested changes

2020-11-23 01:41 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +     * @return 'serviceName@@groupName'
serviceName@@groupName ? should groupName@@serviceName I think

2020-11-23 01:41 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +     *      serviceA    | groupA    | serviceA@@groupA
serviceA@@groupA --》 groupA@@serviceA

2020-11-23 01:41 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +     * @return 'serviceName@@groupName'
same problem with above

2020-11-23 01:55 UTC, mark4z commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +     *      serviceA    | groupA    | serviceA@@groupA
Sorry, i have fix it.

2020-11-23 11:01 UTC, KomachiSion commented
Execute me, Your commit log has error. I think you need to fix it By rebase or checkout a new branch to modify and submit PR again.

2020-11-23 11:01 UTC, KomachiSion commented
![image](https://user-images.githubusercontent.com/37170243/99954835-564f3600-2dbe-11eb-8711-7a51689b7bfc.png)

2020-11-23 11:59 UTC, closed without merging