Fix Nacos console Service list .Group search is not correct #4306
alibaba/nacos pull request #4319
Opened 2020-11-24 09:28 UTC by woxiangwoxiangxiang

Fix #4306

2020-11-24 09:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=4319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=4319) before we can accept your contribution.<br/><hr/>**wangchunhao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=4319) it.</sub>

2020-11-24 15:59 UTC, paderlol commented
Please append some unit test cases to prove your changes

2020-11-25 00:55 UTC, Maijh97 commented
@woxiangwoxiangxiang Please sign the Contributor License Agreement first.

2020-11-25 11:35 UTC, woxiangwoxiangxiang commented
> Please append some unit test cases to prove your changes

Where do I add unit tests? In ServiceManagerTest?

But ServiceManagerTest doesn't run correctly.
<img width="1440" alt="WeChat459ff5a1fea75c6664dd9c5adb9eb531" src="https://user-images.githubusercontent.com/29097594/100222631-56356e80-2f55-11eb-87ad-ed4146ac3975.png">

2020-11-25 12:08 UTC, paderlol commented
You need to verify the split is correct through unit tests

2020-11-26 10:40 UTC, KomachiSion requested changes

2020-11-26 10:40 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
> +
Please do not change the indentation. Maybe you do not use nacos code style. Can you read the style/codeStyle.md in source code directory?

2020-11-26 10:43 UTC, KomachiSion commented
> > Please append some unit test cases to prove your changes
> 
> Where do I add unit tests? In ServiceManagerTest?
> 
> But ServiceManagerTest doesn't run correctly.
> <img alt="WeChat459ff5a1fea75c6664dd9c5adb9eb531" width="1440" src="https://user-images.githubusercontent.com/29097594/100222631-56356e80-2f55-11eb-87ad-ed4146ac3975.png">
> This is the result of the original ServiceManagerTest run

Why you need spy to create ServiceManager?

2020-12-01 01:40 UTC, KomachiSion commented
@woxiangwoxiangxiang Please fix code style problem and sign CLA, otherwise we will close this PR.

2020-12-04 01:22 UTC, KomachiSion commented
@woxiangwoxiangxiang Sorry, your CLA still not right, I see the true commit user is `wangchunhao` not your github id.
So you should use `git config user.name` and `git config user.email` to re-commit your change and re-submit a PR to fix it.

BTW, we strongly recommend you use the nacos code style when you change nacos codes.

2020-12-04 01:22 UTC, closed without merging