[ISSUE-#4567] Refactor nacos-client Load Logging Configuration code.
alibaba/nacos pull request #4572
Opened 2020-12-25 07:01 UTC by Maijh97

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix: #4567 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2020-12-25 07:58 UTC, horizonzy requested changes

2020-12-25 07:58 UTC, horizonzy commented on client/src/main/java/com/alibaba/nacos/client/logging/NacosLoggingUtils.java
> +                logging.loadConfiguration();
这里要不要降级一下，自定义的失败了用默认的。

2020-12-25 08:01 UTC, Maijh97 commented on client/src/main/java/com/alibaba/nacos/client/logging/NacosLoggingUtils.java
> +                logging.loadConfiguration();
可行

2020-12-25 10:44 UTC, horizonzy commented on client/src/main/java/com/alibaba/nacos/client/logging/NacosLogging.java
> +            nacosLogging.loadConfiguration();
这个变量感觉好绕啊。

2020-12-26 05:17 UTC, KomachiSion approved these changes

2020-12-26 05:18 UTC, merged