console-ui config排序优化
alibaba/nacos pull request #4599
Opened 2020-12-29 14:23 UTC by wjm0729

console-ui 修改 config 列表支持排序

2020-12-29 14:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=4599) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=4599) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=4599) it.</sub>

2020-12-30 01:41 UTC, KomachiSion requested changes

2020-12-30 01:41 UTC, KomachiSion commented on .gitignore
> +distribution/logs
this three dir is your local generation, please remove by yourself, do not submit

2020-12-30 01:48 UTC, wjm0729 commented on .gitignore
> +distribution/logs
好吧

2020-12-30 01:55 UTC, wjm0729 commented on .gitignore
> +distribution/logs
本地 ignore 去掉了

2020-12-30 02:01 UTC, KeRan213539 approved these changes

2020-12-30 03:05 UTC, KomachiSion approved these changes

2020-12-30 03:08 UTC, KomachiSion commented
@wjm0729 Please sign your CLA.

2020-12-30 03:42 UTC, wjm0729 commented
Done

2020-12-31 03:34 UTC, merged