#4602  针对第一点修改
alibaba/nacos pull request #4630
Opened 2021-01-05 12:16 UTC by wjm0729

1. 目前导入功能检查如果格式不完全符合要求(部分符合)就终止导入. 改为不符合的部分忽略,符合的部分处理
格式标准:
根目录只包含文件夹和 .meta.yml 文件,其他不处理
.meta.yml 文件不是必须,有就处理.
.meta.yml 文件中只包含 所属APP 信息,不包含其他信息
文件夹名称作为group ID
文件夹中的文件夹不处理,只处理文件夹中的文件
文件夹中的文件名作为 dataid, 文件内容作为配制内容
根据dataid名称后缀简单判断文件类型,如果无后缀或者后缀无法识别默认为 text

2021-01-06 03:56 UTC, KeRan213539 requested changes

2021-01-06 03:56 UTC, KeRan213539 commented on config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> +                        continue;
可以不用输出日志,或者日志级别调低
统计跳过的项并返回给前端,参考  com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl#batchInsertOrUpdate
```java
Map<String, String> skipitem = new HashMap<>(2);
skipitem.put("dataId", skipConfigInfo.getDataId());
skipitem.put("group", skipConfigInfo.getGroup());
skipData.add(skipitem);
```

2021-01-06 04:58 UTC, KeRan213539 commented on config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> +                        continue;
讨论了下,不统计到 skipitem 里了,增加一个不克识别跳过的统计项并返回给前端,前端加上对应展示

2021-01-08 02:01 UTC, KomachiSion commented
Which issue does the PR refer?

What's the first item or point of modification ?

I think you should refer issue and make the discussion visible.

BTW, you need modify you PR title first to describe what's you actually changes.

2021-01-13 03:26 UTC, KeRan213539 requested changes

2021-01-13 03:26 UTC, KeRan213539 commented on config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> +        }
这里不要合并到这个跳过项里,这个跳过统计的是已存在的配制不覆盖的跳过
新增一个无法识别的跳过,并加到返回给前端的数据里.前端的结果显示中增加一个无法识别跳过的.

2021-01-13 05:50 UTC, wjm0729 commented on config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> +        }
done

2021-01-15 05:38 UTC, wjm0729 commented on config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> +        }
@KeRan213539  好了

2021-01-15 06:31 UTC, KeRan213539 requested changes

2021-01-15 06:31 UTC, KeRan213539 commented on config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> +                        skipitem.put("group", "");
未识别的,应该区分不出 dataId 和 group 吧? 这里换个叫法?(未识项/无法识别项目/其他叫法) ,没必要 group 给个空值

2021-01-15 06:31 UTC, KeRan213539 commented on console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
> +                  <Table.Column title="Group" dataIndex="group" />
同上

2021-01-15 06:31 UTC, KeRan213539 commented on console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
> +                  <Table.Column title="Group" dataIndex="group" />
同上

2021-01-21 09:53 UTC, closed without merging