[ISSUE #4717] Fix web console alert static file can't be found
alibaba/nacos pull request #4719
Opened 2021-01-15 14:26 UTC by ttttangzhen

## What is the purpose of the change
For-#4717

2021-01-15 14:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=4719) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=4719) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=4719) it.</sub>

2021-01-16 07:39 UTC, KeRan213539 commented
这个文件是编译产生的,修改这个文件没用的...

2021-01-16 07:40 UTC, KeRan213539 requested changes
这个文件是编译产生的,修改这个文件没用的...

2021-01-18 01:17 UTC, KomachiSion commented
是否应该去查看console-ui里相关源码？ 然后做一下修改， 改main.css的话 下次编译很可能又回加上

2021-01-18 01:33 UTC, ttttangzhen commented
> 是否应该去查看console-ui里相关源码？ 然后做一下修改， 改main.css的话 下次编译很可能又回加上

是的，我再跟一下

2021-01-26 11:33 UTC, KomachiSion commented
@ttttangzhen I think we can close this PR first, after you find out the solution, submit PR again. Thanks for your contribution.

2021-01-26 11:33 UTC, closed without merging