[ISSUE #5096] Add unit tests to package com.alibaba.nacos.naming.healthcheck in nacos 2.0
alibaba/nacos pull request #5170
Opened 2021-03-24 02:24 UTC by xiaoshuanglee

a part of fixing ISSUE #5096 
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2021-03-24 02:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=5170) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=5170) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=5170) it.</sub>

2021-03-24 05:57 UTC, KomachiSion commented
Please sign your CLA first

2021-03-25 01:42 UTC, KomachiSion requested changes

2021-03-25 01:42 UTC, KomachiSion commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2Test.java
> +    public void initHealthCheckTaskV2() {
Before method name should be setUp

2021-03-25 01:42 UTC, KomachiSion commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2Test.java
> +    private List<Service> returnService() {
Can replace with Collections.singleList

2021-03-25 01:42 UTC, KomachiSion commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2Test.java
> +    public void init() {
Before method name should be setUp

2021-03-25 01:42 UTC, KomachiSion commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2Test.java
> +    public void reEvaluateCheckRT() {
test method should start with `test`

2021-03-25 01:42 UTC, KomachiSion commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2DelegateTest.java
> +    public void initBean() {
Before method name should be setUp

2021-03-25 01:42 UTC, KomachiSion commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2DelegateTest.java
> +            e.printStackTrace();
Why ignore exception? if throw exception is expected behavior, should add it in @Test(expected=xxx)

2021-03-25 01:42 UTC, KomachiSion commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java
> +    public void initBean() {
Before method name should be setUp

2021-03-25 01:42 UTC, KomachiSion commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java
> +            e.printStackTrace();
Same problem as last exception handle

2021-03-25 02:46 UTC, li-xiao-shuang commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java
> +    public void initBean() {
> Before method name should be setUp

fix

2021-03-25 02:46 UTC, li-xiao-shuang commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2Test.java
> +    public void init() {
> Before method name should be setUp

fix

2021-03-25 02:47 UTC, li-xiao-shuang commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2Test.java
> +    private List<Service> returnService() {
> Can replace with Collections.singleList

fix

2021-03-25 02:47 UTC, li-xiao-shuang commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2Test.java
> +    public void reEvaluateCheckRT() {
> test method should start with `test`

fix

2021-03-25 02:47 UTC, li-xiao-shuang commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2DelegateTest.java
> +    public void initBean() {
> Before method name should be setUp

fix

2021-03-25 02:47 UTC, li-xiao-shuang commented on naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java
> +            e.printStackTrace();
> Same problem as last exception handle

fix

2021-03-26 02:00 UTC, KomachiSion approved these changes

2021-03-26 02:01 UTC, merged