[ISSUE #5078] set default pageSize to 10000 for getting all the  subscribers in other server node.
alibaba/nacos pull request #5424
Opened 2021-04-20 12:57 UTC by brothelul

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fixes #5078 

由于每台机器的subscribers的数量都可能超过pageSize，所以暂时没有使用查本地再去查远程服务的方式。因为在做翻页的时候，必须要告诉后端已经查询了哪些机器，这样才能确认这一次查询需要查询那些机器，这样复杂度会很高，改动范围会比较大。所以暂时考虑用这种方式修复此问题。

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2021-04-20 17:49 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
> +        int pageSize = NumberUtils.toInt(WebUtils.optional(request, "pageSize", "10000"));
感觉在这里用缺省值开头太大了，这个是open api，用户可以直接使用，建议还是通过在请求时设置参数。

2021-04-21 01:35 UTC, brothelul commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
> +        int pageSize = NumberUtils.toInt(WebUtils.optional(request, "pageSize", "10000"));
可以，我待会换种方式，但是暂时还是建议通过大数值这种方式修复这个问题。

2021-04-21 01:48 UTC, KomachiSion requested changes

2021-04-21 01:48 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
> +        int pageSize = NumberUtils.toInt(WebUtils.optional(request, "pageSize", "10000"));
前端传递的代码是有pageSize和pageNo的，我觉得可以暂时先透传到其他server端。

之后再修改和优化查询逻辑。

2021-04-21 12:55 UTC, brothelul commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
> +        int pageSize = NumberUtils.toInt(WebUtils.optional(request, "pageSize", "10000"));
那我暂时把缺省值将为1000，这个基本就是查所有了。

2021-04-22 02:10 UTC, KomachiSion requested changes
不传递pageNo和Size吗？ 光靠默认值肯定是不行的。

2021-04-22 03:12 UTC, brothelul commented
好的，我待会调整一下，疏忽了这个问题。

2021-04-23 01:51 UTC, KomachiSion approved these changes

2021-04-23 01:52 UTC, merged