Nacos client within docker container could not receive service change…
alibaba/nacos pull request #5439
Opened 2021-04-21 12:21 UTC by goodjava

nacos+dubbo 以consumer端部署的时候如果部署在容器内(docker内).就会发现provider list 的更新频率变成自动跑的任务的更新频率,而且永远收不到udp的push信息,这是因为docker内部安装的应用需要提前通知他们使用什么端口,不然其实是隔离的(比如桥接模式).
简单描述就是:查询list列表的时候会上报udp端口,但nacos server 获取到变更后并不能通知到容器中 dubbo 的 consumer端
<img width="1036" alt="n1" src="https://user-images.githubusercontent.com/869986/115551283-67ed2900-a2dd-11eb-87f7-539f27bd99c1.png">
<img width="993" alt="nv" src="https://user-images.githubusercontent.com/869986/115551804-26a94900-a2de-11eb-83a1-9bc911e46292.png">
<img width="1254" alt="fffff" src="https://user-images.githubusercontent.com/869986/115552557-0cbc3600-a2df-11eb-8086-d07d1d3fe3a3.png">

2021-04-22 02:06 UTC, KomachiSion requested changes
Please use nacos code style to reformat code.

2021-04-22 02:54 UTC, goodjava commented
> Please use nacos code style to reformat code.

代码格式修正了

2021-04-22 07:08 UTC, KomachiSion approved these changes

2021-04-22 07:10 UTC, merged

2021-09-09 12:58 UTC, hujiang75277381 commented
请问，在一个机器上 存在多个nacos client 怎么办？？？？大佬跪舔 。希望快速回复，等着上线。

2022-10-09 09:15 UTC, jefferson-chern commented
> nacos+dubbo 以consumer端部署的时候如果部署在容器内(docker内).就会发现provider list 的更新频率变成自动跑的任务的更新频率,而且永远收不到udp的push信息,这是因为docker内部安装的应用需要提前通知他们使用什么端口,不然其实是隔离的(比如桥接模式). 简单描述就是:查询list列表的时候会上报udp端口,但nacos server 获取到变更后并不能通知到容器中 dubbo 的 consumer端 <img alt="gggg" width="1117" src="https://user-images.githubusercontent.com/869986/115553377-ee0a6f00-a2df-11eb-897d-7a3c9f846990.png"> <img alt="nv" width="993" src="https://user-images.githubusercontent.com/869986/115551804-26a94900-a2de-11eb-83a1-9bc911e46292.png"> <img alt="fffff" width="1254" src="https://user-images.githubusercontent.com/869986/115552557-0cbc3600-a2df-11eb-8086-d07d1d3fe3a3.png">

大佬，请问一下您那边怎么指定的push.receiver.udp.port，这个读取的是系统环境变量，但是我使用export设置push.receiver.udp.port不成功，因为变量名不支持含有.的特殊字符。请教一下怎么设置的

2022-10-09 09:17 UTC, jefferson-chern commented
> 请问，在一个机器上 存在多个nacos client 怎么办？？？？大佬跪舔 。希望快速回复，等着上线。

您那边怎么设置的push.receiver.udp.port

2023-02-09 00:57 UTC, hujiang75277381 commented
> > 请问，在一个机器上 存在多个nacos client 怎么办？？？？大佬跪舔 。希望快速回复，等着上线。
> 
> 您那边怎么设置的push.receiver.udp.port

设置在jvm中， -Dpush.receiver.udp.port=10086

2023-02-24 01:28 UTC, jefferson-chern commented
> > > 请问，在一个机器上 存在多个nacos client 怎么办？？？？大佬跪舔 。希望快速回复，等着上线。
> > 
> > 
> > 您那边怎么设置的push.receiver.udp.port
> 
> 设置在jvm中， -Dpush.receiver.udp.port=10086

您好，我们开始也想着在jvm中设置 `-Dpush.receiver.udp.port`，但是发现设置不生效，因为 push.receiver.udp.port 是linux系统的环境变量，后来我们使用 设置环境变量的方式设置好了， 使用如下方式：
`env push.receiver.udp.port=10086 java -jar xxx.jar `

这种方式还支持一个机器上存在多个nacos client ，因为env设置的环境变量，仅仅在 `env push.receiver.udp.port=10086 java -jar xxx.jar ` 这一行shell执行时生效，不同的xxx.jar使用不同的 `push.receiver.udp.port `即可，如下：
```
nacos client1 对应：env push.receiver.udp.port=10086 java -jar 1.jar
nacos client2 对应：env push.receiver.udp.port=10087 java -jar 2.jar
```