[ISSUE #5437]: change dump-task taskKey
alibaba/nacos pull request #5440
Opened 2021-04-21 12:49 UTC by CherishCai

fix #5437

2021-04-21 12:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=5440) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=5440) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=5440) it.</sub>

2021-04-22 02:05 UTC, KomachiSion requested changes
There are CI problem, please fix it first

2021-04-22 02:19 UTC, shiyiyue1102 reviewed
check pass.

2021-04-22 02:20 UTC, shiyiyue1102 submitted a review, later dismissed
check ok

2021-04-22 03:27 UTC, KomachiSion approved these changes

2021-04-22 03:27 UTC, merged