Optimize code
alibaba/nacos pull request #5511
Opened 2021-04-27 08:51 UTC by yidadi

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2021-04-27 08:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=5511) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=5511) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=5511) it.</sub>

2021-04-28 01:34 UTC, KomachiSion requested changes
Please sign your CLA and use nacos' code style to reformat codes.

2021-04-28 13:15 UTC, yidadi commented
fix

2021-04-29 02:22 UTC, horizonzy commented on client/src/main/java/com/alibaba/nacos/client/config/utils/ContentUtils.java
> +        if (StringUtils.isBlank(content)) {
This logic is different from origin.

2021-04-29 02:22 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/push/ClientInfo.java
> +        C("Nacos-C-Client"),
`vip-client4cpp` also be define C

2021-04-29 02:22 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/push/ClientInfo.java
>  import org.apache.commons.lang3.StringUtils;
It can be replace by self StringUtils

2021-04-29 02:22 UTC, horizonzy commented on naming/src/main/java/com/alibaba/nacos/naming/push/ClientInfo.java
> +        version = VersionUtil.parseVersion(versionStr);
To unify code, use `this.version` and `this.type`

2021-04-29 10:02 UTC, KomachiSion requested changes

2021-04-29 10:02 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/push/ClientInfo.java
> +        if (com.alibaba.nacos.common.utils.StringUtils.isBlank(versionStr)) {
If there use `com.alibaba.nacos.common.utils.StringUtils`, why not replace the import ?

2021-04-30 10:03 UTC, KomachiSion commented
CI seems has problem. Please Fix it .

And Can you add some Unit test for your changes?

2021-05-05 07:36 UTC, yidadi commented
done all

2021-05-10 02:48 UTC, KomachiSion commented
CI still can't pass

2021-05-10 06:27 UTC, yidadi commented
Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project nacos-naming: Too many files with unapproved license: 1 See RAT report in: /home/travis/build/alibaba/nacos/naming/target/rat.txt -




Compilation error caused by non code submission



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 上午10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] Optimize code (#5511)





 
CI still can't pass
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-11 01:57 UTC, KomachiSion requested changes

2021-05-11 01:57 UTC, KomachiSion commented on naming/src/test/java/com/alibaba/nacos/naming/push/ClientInfoTest.java
> +package com.alibaba.nacos.naming.push;
This file has no copyright

2021-05-19 01:19 UTC, KomachiSion commented
@yidadi Sorry, the copyright and CI are still not fixed. And no response for a long time. We need close PR first. If you want to change these. Please fix problem and resubmit again. Thanks.

2021-05-19 01:19 UTC, closed without merging