在容器环境中IPV6的校验逻辑会影响集群部署，建议同ipv4的校验逻辑一样暂时去掉
alibaba/nacos pull request #5514
Opened 2021-04-27 09:56 UTC by pig-stdv

The IPv6 judgment logic in this method will obtain IP address according to the host. In the container environment, K8S has not allocated IP to this pod, and then the judgment will report an error. After finding this problem, I gave feedback to remove the IPv4 judgment, but this problem still exists in IPv6. Suggested to remove the verification logic can be in other ways to optimize.

2021-04-27 11:57 UTC, pig-stdv commented
@KomachiSion

2021-04-28 01:36 UTC, KomachiSion commented
@KeRan213539 Please have some review and discuss.

Preparing release 1.4.2 and pending PR temparately.

2021-04-28 10:12 UTC, pig-stdv commented
IPv4 and IPv6 validation rule optimization (using regular), in order to prevent container deployment in the case of domain name resolution to add domain name rule validation, IPv6 rule validation before adding remove the slogan logic.

2021-04-29 02:16 UTC, KeRan213539 requested changes
com.alibaba.nacos.sys.utils.InetUtils 中有个 isDomain 方法, 建议把那个方法里的实现也修改为不解析域名的(IPUtil不要去调用InetUtils#isDomain  ,因为两个类不在同一个模块, 仅修改 isDomain  的实现)
另外 IPUtil 中有个 isIP 方法, 这个方法也改为不解析域名的方式

2021-04-29 07:27 UTC, pig-stdv commented
>  IPUtil 中的 isIP 方法已经底层都是采用一套正则校验
> com.alibaba.nacos.sys.utils.InetUtils 中的 isDomain 方法已优化
>  NOTICE 添加许可

2021-04-29 10:56 UTC, KomachiSion approved these changes

2021-04-30 01:13 UTC, KeRan213539 approved these changes

2021-04-30 01:14 UTC, merged