Fixes logical judgment expression #5683
alibaba/nacos pull request #5685
Opened 2021-05-12 07:55 UTC by bird-man04

**What is the purpose of the change？**

> Fixes logical judgment expression for #5683

2021-05-12 07:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=5685) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=5685) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=5685) it.</sub>

2021-05-12 09:09 UTC, KomachiSion requested changes
Please sign CLA and fix CI

2021-05-12 09:37 UTC, bird-man04 commented
> Please sign CLA and fix CI

I finished it.

2021-05-12 09:55 UTC, bird-man04 commented
> Please sign CLA and fix CI

About CI,I have a question
![image](https://user-images.githubusercontent.com/39239059/117955663-da847e00-b34a-11eb-88c0-967cd96633c5.png)
i already do this,but i checked the received mail ,it dose not work,i don't konw why

2021-05-14 01:39 UTC, KomachiSion approved these changes

2021-05-14 01:39 UTC, merged