Format 'ServiceController' code
alibaba/nacos pull request #5796
Opened 2021-05-20 06:37 UTC by 985391294

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Format the ServiceController code under the 'nacos-naming' module.

2021-05-20 06:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=5796) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=5796) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=5796) it.</sub>

2021-05-21 03:04 UTC, KomachiSion requested changes

2021-05-21 03:04 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
> +
Format what?

please use nacos code style to reformat

2021-05-21 04:07 UTC, 985391294 commented
Sorry, I didn't set the Nacos code style before

2021-05-21 04:07 UTC, closed without merging