[ISSUE #5765] fix localhost not match ip
alibaba/nacos pull request #5852
Opened 2021-05-25 12:32 UTC by SunJiFengPlus

## What is the purpose of the change
For #5765 
fix ```localhost``` in cluster.conf not available

## Brief changelog

- rename IPUitl to InternetAddressUtil
- move isDomain to InternetAddressUtil
- fix localhost not match ip

## Verifying this change

[unit test case](https://github.com/alibaba/nacos/commit/ad541f664c99c8dde3ec76e7b0dc4a9e87132a68#diff-e3feb653a6109bcc8e7bbc7974c2d6fa93b17cc25783e9a26f31d86f36f2d471R103) pass

2021-05-26 02:16 UTC, KomachiSion requested changes

2021-05-26 02:16 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/InternetAddressUtil.java
> +     * juege str is right domain.（Check only rule）
juede -- > judge

2021-05-26 02:53 UTC, SunJiFengPlus commented on common/src/main/java/com/alibaba/nacos/common/utils/InternetAddressUtil.java
> +     * juege str is right domain.（Check only rule）
I've fix it

2021-05-27 11:01 UTC, KomachiSion approved these changes

2021-05-27 11:01 UTC, merged