[code quality][nacos-address]improve the code of ServiceManager.java
alibaba/nacos pull request #5919
Opened 2021-06-01 07:54 UTC by zhongxiongzeng

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2021-06-01 07:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=5919) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=5919) before we can accept your contribution.<br/><hr/>**zhongxiong.zeng** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=5919) it.</sub>

2021-06-03 01:54 UTC, KomachiSion commented
Please fix the cla problem first

2021-06-03 02:55 UTC, zhongxiongzeng commented
> Please fix the cla problem first

done

2021-06-07 06:22 UTC, KomachiSion commented
Can you describe why you do refactor like this?  I think this change need to be discuss.

2021-06-07 06:42 UTC, zhongxiongzeng commented
> Can you describe why you do refactor like this? I think this change need to be discuss.

主要是优化了两个锁，使逻辑简单清晰一点。
1.优化putService线程安全的逻辑：serviceMap是ConcurrentHashMap，本身就是一个线程安全类，加锁-get-put-解锁，用putIfAbsent替代就行了。
2.addUpdatedServiceToQueue这个方法也是一样的，若只要保证这个方法是线程安全的，用synchronized就够了，额外用一个对象来加锁反而让代码显得臃肿复杂

2021-06-09 01:46 UTC, KomachiSion requested changes

2021-06-09 03:04 UTC, zhongxiongzeng commented on naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
> +        serviceMap.putIfAbsent(service.getNamespaceId(), new ConcurrentSkipListMap<>())
yes, i wil fix it later

2021-06-16 02:24 UTC, KomachiSion approved these changes

2021-06-16 02:24 UTC, merged