[#5983] Fix unit tests in nacos-config
alibaba/nacos pull request #5995
Opened 2021-06-08 01:58 UTC by realJackSun

fix #5983 

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2021-06-15 12:10 UTC, realJackSun commented on config/src/test/java/com/alibaba/nacos/config/server/controller/HealthControllerUnitTest.java
> +        ReflectionTestUtils.setField(healthController, "memberManager", memberManager);
healthController中的memberManager没有被注入，所以这里mock一个注入。

2021-06-15 12:10 UTC, realJackSun commented on config/src/test/java/com/alibaba/nacos/config/server/service/ConfigChangePublisherTest.java
> +        PropertyUtil.setEmbeddedStorage(true);
这个修改的动机是，这个单测会通过EnvUtil.setIsStandalone(false);破坏原来的EnvUtil的字段值。
这里两行代码，将EnvUtil重置为原先的值。

2021-06-15 12:10 UTC, realJackSun commented on config/src/test/resources/application.properties
> +#
加上这个配置文件的意义在于，没有这个配置文件，DumpServiceTest的前置@SpringBootTest就启动不了。

2021-06-16 02:20 UTC, KomachiSion requested changes

2021-06-16 02:20 UTC, KomachiSion commented on config/src/test/java/com/alibaba/nacos/config/server/service/ConfigChangePublisherTest.java
> +        PropertyUtil.setEmbeddedStorage(true);
在Before方法和After方法中去还原。否则异常情况下仍然会导致不会重制。

2021-06-16 02:20 UTC, KomachiSion commented on config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpServiceTest.java
> +@SpringBootApplication(scanBasePackages = "com.alibaba.nacos")
无法mock？

2021-06-16 09:46 UTC, realJackSun commented on auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
>   */
这个不需要，可以研究一下

2021-06-17 07:23 UTC, KomachiSion commented
Please pull newest codes, which fix ci problem.

2021-06-17 12:24 UTC, KomachiSion approved these changes

2021-06-17 12:34 UTC, KomachiSion approved these changes

2021-06-17 12:34 UTC, KomachiSion approved these changes

2021-06-17 12:34 UTC, merged