[ISSUE#3102] nacos-common module
alibaba/nacos pull request #6211
Opened 2021-06-30 04:54 UTC by zzq1314zll

add ArrayUtils and TestClass
for #3102

2021-06-30 05:55 UTC, KomachiSion commented
Please pull new develop branch. There are some changes to improve the IT stability.

2021-07-01 03:29 UTC, KomachiSion requested changes

2021-07-01 03:29 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
> + * @author zzq
Please do not change author, you can add an new author for youself.

2021-07-01 03:29 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
> +            if (Character.isWhitespace(cs.charAt(i)) == false) {
` == false`? why not directly use `!`

2021-07-01 03:29 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
> -    public static boolean isAllBlank(String... strs) {
Why remove this method. No use it?

2021-07-01 04:14 UTC, zzq1314zll commented on common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
> -    public static boolean isAllBlank(String... strs) {
Yes.

2021-07-01 06:09 UTC, realJackSun approved these changes

2021-07-01 06:28 UTC, KomachiSion approved these changes

2021-07-01 06:28 UTC, merged