[ISSUE alibaba#6160] Optimization of IP address acquisition method
alibaba/nacos pull request #6320
Opened 2021-07-09 06:47 UTC by bdqfork

For #6160 

## What is the purpose of the change

Optimization of IP address acquisition method

## Brief changelog

`com.alibaba.nacos.client.naming.local.ip` parameter be changed to `com.alibaba.nacos.client.local.ip` and `com.alibaba.nacos.client.local.preferHostname` parameter be provided to specify that IP is preferred to be replaced by hostname for config publishing.

2021-07-09 06:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=6320) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=6320) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=6320) it.</sub>

2021-07-12 01:30 UTC, KomachiSion requested changes
Can you add some unit test for your changes?

2021-07-12 05:53 UTC, KomachiSion requested changes

2021-07-12 05:53 UTC, KomachiSion commented on api/src/test/java/com/alibaba/nacos/api/utils/NetUtilsTest.java
> +        System.clearProperty("com.alibaba.nacos.client.local.ip");
The clear operation should be run in After method.

If the case like this, when assert error in line 42. the clear operation in line 43 will not do.

2021-07-13 01:31 UTC, KomachiSion approved these changes

2021-07-13 23:33 UTC, csees420 commented
@CLAassistant

2021-07-13 23:33 UTC, csees420 commented
#6320

2021-07-14 01:54 UTC, KomachiSion approved these changes

2021-07-14 01:54 UTC, merged