improvement currentTimeMillis calc, using System.nanoTime() to measur…
alibaba/nacos pull request #6366
Opened 2021-07-15 08:57 UTC by wuwen5

improvement currentTimeMillis calc, using System.nanoTime() to measure elapsed time.

2021-07-16 03:32 UTC, KomachiSion requested changes

2021-07-16 03:32 UTC, KomachiSion commented on core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java
> +
Do not change indent , please use nacos code style to reformat codes.

2021-07-19 02:35 UTC, KomachiSion reviewed
Have you tested how much performance this modification can improve?

2021-07-19 05:52 UTC, wuwen5 commented
It mainly not affected by  clock moving backwards, Using ```System.currentTimeMillis()``` to measure elapsed time can give incorrect results, ```currentTimeMillis()``` is wall time, backwards is possible, ```nanoTime()``` is monotonic time It's impossible to go backwards.

2021-07-20 02:36 UTC, KomachiSion commented
But I see there is much cal for time, have you test the performance effect?

2021-07-21 06:11 UTC, wuwen5 commented
```
# Mac OS X: 10.15.7
# JMH version: 1.32
# VM version: JDK 1.8.0_181, Java HotSpot(TM) 64-Bit Server VM, 25.181-b13
Benchmark                     Mode  Cnt       Score        Error  Units
Test.newImplUseNanoTimeCalc  thrpt    5  610940.234 ±  54002.164  ops/s
Test.originally              thrpt    5  535988.141 ± 105961.666  ops/s


# Linux Red Hat 4.8.5-28:3.10.0-862.el7.x86_64
# JMH version: 1.32
# VM version: JDK 1.8.0_291, Java HotSpot(TM) 64-Bit Server VM, 25.291-b10
Benchmark                     Mode  Cnt       Score        Error  Units
Test.newImplUseNanoTimeCalc  thrpt    5  557613.023 ± 184723.957  ops/s
Test.originally              thrpt    5  515881.617 ± 195077.400  ops/s
```

2021-07-21 06:51 UTC, wuwen5 commented
BTW:if adding log judgment
```java
if (logger.isDebugEnabled()) {
    logger.debug("{}-{}-{}", (new SimpleDateFormat(DATETIME_PATTERN)).format(new Date(this.lastTime)),
            workerId, this.sequence);
}
```


```
Benchmark                     Mode  Cnt        Score        Error  Units
Test.newImplUseNanoTimeCalc  thrpt    5  4070147.689 ± 102391.074  ops/s
Test.originally              thrpt    5  3903584.317 ± 590721.088  ops/s
```

2021-07-22 02:19 UTC, KomachiSion commented
It seems no much improve. So just to fix the possible clock backward？

2021-07-22 02:20 UTC, KomachiSion reviewed
I think this logic should exist.

Or use wait to next mills to replace

2021-07-22 02:22 UTC, wuwen5 commented
> It seems no much improve. So just to fix the possible clock backward？

Yes

2021-07-22 02:33 UTC, wuwen5 commented on core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java
> -        Preconditions.checkState(this.lastTime <= currentMillis,
the clock backward has been fixed, so this logic will never false

2021-07-22 03:06 UTC, KomachiSion commented
OK, Can you add some unit test to test your change?

2021-07-22 07:27 UTC, wuwen5 commented
@KomachiSion   the source file ```SnowFlowerIdGenerator_ITCase.java``` wrong uses tabs, so changed indent

2021-07-23 02:42 UTC, KomachiSion commented
> @KomachiSion the source file `SnowFlowerIdGenerator_ITCase.java` wrong uses tabs, so changed indent

Please do not change any ITCase, Please add the unit test not IT.

2021-07-26 01:38 UTC, KomachiSion approved these changes

2021-07-26 01:38 UTC, merged