[Reduce dependence]>[Lists] Replace "google.common.collect.*" API wit…
alibaba/nacos pull request #6404
Opened 2021-07-21 06:12 UTC by zzq1314zll

Replace "google.common.collect.*"

2021-07-22 02:14 UTC, KomachiSion requested changes

2021-07-22 02:14 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
> +            throw new NullPointerException();
Whether `IllegalArgumentException` is better?

2021-07-22 02:14 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
> +        ArrayList<T> list = new ArrayList<>();
use elements.size to init the array size?

2021-07-26 01:37 UTC, KomachiSion submitted a review, later dismissed

2021-07-26 01:37 UTC, KomachiSion commented
There are some conflict, please solve them.

2021-07-26 15:23 UTC, zzq1314zll commented
@KomachiSion Already solved

2021-07-27 05:47 UTC, KomachiSion approved these changes

2021-07-27 05:47 UTC, merged