replace "google.common.base.Preconditions" API with jdk API
alibaba/nacos pull request #6502
Opened 2021-07-29 01:49 UTC by zzq1314zll

replace "google.common.base.Preconditions" API with jdk API,
for #6498

2021-07-29 02:59 UTC, KomachiSion requested changes
It seems that full copy from guava's Preconditions?

2021-07-29 02:59 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/Preconditions.java
> +import static com.google.common.base.Strings.lenientFormat;
still depend guava?

2021-07-29 03:00 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/Preconditions.java
> +import static com.google.common.base.Strings.lenientFormat;
I think the Nullable is no need, we can judge in method.

And the guava depend can be refactor.

2021-07-29 10:47 UTC, zzq1314zll commented
No, 

> It seems that full copy from guava's Preconditions?

NO! 我仅仅是借鉴，没有有copy

2021-07-30 08:35 UTC, KomachiSion approved these changes

2021-07-30 08:35 UTC, merged