Fix npe when connection is not established.
alibaba/nacos pull request #6534
Opened 2021-08-03 05:39 UTC by horizonzy

```
Caused by: java.lang.NullPointerException
	at com.alibaba.nacos.common.remote.client.RpcClient.shutdown(RpcClient.java:466)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.shutdown(GrpcClient.java:81)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.shutdown(NamingGrpcClientProxy.java:234)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.shutdown(NamingClientProxyDelegate.java:180)
	at com.alibaba.nacos.client.naming.NacosNamingService.shutDown(NacosNamingService.java:456)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.shutdown(NacosNamingServiceWrapper.java:78)
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.doDestroy(NacosServiceDiscovery.java:70)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.destroy(AbstractServiceDiscovery.java:81)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.lambda$destroy$1(ServiceDiscoveryRegistry.java:291)
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
	... 10 more
```

The connection is not established, and the client shutdown.

2021-08-04 06:01 UTC, KomachiSion requested changes
I think remove logs is not good way. We should print logs but content is different when connection is null.

2021-08-06 02:21 UTC, horizonzy commented on common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
> +            LOGGER.info("Close current connection " + connection.getConnectionId());
This is why I move log here. 😂

2021-08-10 01:29 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
> +            LOGGER.info("Close current connection " + connection.getConnectionId());
I can't get the reason, the log print connection is closing info with connection id. Why remove this log?

2021-08-10 01:31 UTC, KomachiSion approved these changes

2021-08-10 01:31 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
> +            LOGGER.info("Close current connection " + connection.getConnectionId());
ok

2021-08-10 01:31 UTC, merged