chore: 提交ExternalStoragePersistServiceImpl单元测试
alibaba/nacos pull request #6772
Opened 2021-08-30 11:22 UTC by kangzemin

提交类ExternalStoragePersistServiceImpl的单元测试

2021-08-30 11:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=6772) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=6772) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=6772) it.</sub>

2021-08-30 15:49 UTC, brotherlu-xcq commented
Hi, @kangzemin you must assign the CLA first.

2021-08-31 02:37 UTC, KomachiSion requested changes

2021-08-31 02:37 UTC, KomachiSion commented on config/pom.xml
> +
Please do not change the indent. Please use nacosCodeStyle to reformat codes.

2021-09-07 03:27 UTC, KomachiSion commented
Please fix the IT, thanks.

2021-09-15 02:15 UTC, KomachiSion commented
CI can't pass and author has no more response and mofidied. Close PR.

2021-09-15 02:15 UTC, closed without merging