[ISSUE #6846] Fix the bug that the registered persistent instance will become an ephemeral instance under some operations of the console / open-api
alibaba/nacos pull request #6861
Opened 2021-09-10 12:08 UTC by joyeekk

## What is the purpose of the change
support issue #6846: Fix the bug that the registered persistent instance will become an ephemeral instance under some operations of the console / open-api.

## Brief changelog
support issue #6846 

## Description
- 产生此bug的原因：
1. 服务端在构造ApiInstance列表返回给客户端时，其中Instance的ephemeral属性直接使用了对应Service的ephemeral属性；
2. 而服务端在获取Service实例时，有时候会从本地内存中获取(ephemeral为fasle)，有时候会直接调用构造函数实例化一个Service对象(ephemeral为true，如下图所示)。这样会导致所有实例的ephemeral变为true，在客户端看来就全部变成了临时实例。
![image](https://user-images.githubusercontent.com/28078593/132844923-7b40225f-2024-4f30-8015-23e94fb637d1.png)

- 解决方案：
服务端在构造ApiInstance列表返回给客户端时，其中Instance的ephemeral使用Client的ephemeral属性，这样才是准确的。

## Preview
1. Register three persistent instances:
![image](https://user-images.githubusercontent.com/28078593/132842684-d6d2f3e6-5dec-48eb-9246-37ea8eb2cc6b.png)

2. modify the weight of instance(127.0.0.1:8080) , the ephemeral of instance has not changed:
![image](https://user-images.githubusercontent.com/28078593/132843007-06597c2b-d6f5-4887-a441-32fb54a1d968.png)

## Verifying this change
XXXX

2021-09-13 02:06 UTC, KomachiSion commented
The service should only contain one type persistence. 
The right fix way should use the service singleton in ServiceManager not use the temp create service to set instance ephemeral.

2021-09-13 02:07 UTC, KomachiSion requested changes
The service should only contain one type persistence.
The right fix way should use the service singleton in ServiceManager not use the temp create service to set instance ephemeral.

2021-09-16 07:14 UTC, DaveWang-CN commented
> The service should only contain one type persistence.
> The right fix way should use the service singleton in ServiceManager not use the temp create service to set instance ephemeral.

服务(Service)包含是否是临时的属性、实例(Instance)也包含是否是临时的属性。服务是一组实例的上层组织，那么服务是否应当可以包含临时实例和非临时实例。或者换一种说法，是否是临时的属性是不是应该只在服务(Service)上，如果这么做深层次的原因是什么呢？这是我想了解的。

2021-09-16 07:25 UTC, joyeekk commented
> > The service should only contain one type persistence.
> > The right fix way should use the service singleton in ServiceManager not use the temp create service to set instance ephemeral.
> 
> 服务(Service)包含是否是临时的属性、实例(Instance)也包含是否是临时的属性。服务是一组实例的上层组织，那么服务是否应当可以包含临时实例和非临时实例。或者换一种说法，是否是临时的属性是不是应该只在服务(Service)上，如果这么做深层次的原因是什么呢？这是我想了解的。

而且nacos服务端并没有限制一个服务下只能注册一种类型(永久或者临时)的实例，如果一个服务下所有的实例都使用服务的ephemeral属性，那不就会出现用户注册上去的和返回的ephemeral属性不一致的情况吗？

2021-09-17 11:40 UTC, KomachiSion commented
> > The service should only contain one type persistence.
> > The right fix way should use the service singleton in ServiceManager not use the temp create service to set instance ephemeral.
> 
> 服务(Service)包含是否是临时的属性、实例(Instance)也包含是否是临时的属性。服务是一组实例的上层组织，那么服务是否应当可以包含临时实例和非临时实例。或者换一种说法，是否是临时的属性是不是应该只在服务(Service)上，如果这么做深层次的原因是什么呢？这是我想了解的。

由于最初nacos只有持久化服务和实例，所以没有这个问题，后来增加了非持久化的情况，通过挂载在实例属性上来区别，可以看一下旧版本代码， 在一个服务下有2个set，一个存持久化 一个存非持久化。

这个会导致一个问题，同时存在持久化非持久化会让服务变得复杂，在同步，去重等问题上会有不少问题。

同时我们发现针对99.9%场景，只会有一种类型的服务（如DNS都是持久化，微服务都是非持久化）。因此新版本设计将这个属性上升到服务层面。

然后为了兼容旧版本api，暂时就只能通过instance中的属性来反推service的属性了，这才出现了service里有，instance也有的情况。

2021-09-17 11:40 UTC, KomachiSion commented
> > > The service should only contain one type persistence.
> > > The right fix way should use the service singleton in ServiceManager not use the temp create service to set instance ephemeral.
> > 
> > 
> > 服务(Service)包含是否是临时的属性、实例(Instance)也包含是否是临时的属性。服务是一组实例的上层组织，那么服务是否应当可以包含临时实例和非临时实例。或者换一种说法，是否是临时的属性是不是应该只在服务(Service)上，如果这么做深层次的原因是什么呢？这是我想了解的。
> 
> 而且nacos服务端并没有限制一个服务下只能注册一种类型(永久或者临时)的实例，如果一个服务下所有的实例都使用服务的ephemeral属性，那不就会出现用户注册上去的和返回的ephemeral属性不一致的情况吗？

当然要限制，目前考虑到兼容性，暂时没有补充这个逻辑。后续版本肯定不会再允许一个服务下同时存在两种类型的实例了。

2021-09-17 11:41 UTC, KomachiSion commented
后续问题请到issue中提问， 在PR中不在回答。

2021-11-16 07:15 UTC, KomachiSion commented
Fixed by #7239.

2021-11-16 07:15 UTC, closed without merging