Deleted unecessaries imports optimize logic in if and for
alibaba/nacos pull request #7289
Opened 2021-11-25 03:06 UTC by Barbacraft

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2021-11-25 03:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=7289) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=7289) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=7289) it.</sub>

2021-11-29 01:51 UTC, KomachiSion commented
Please sign CLA first.

2021-11-29 01:52 UTC, KomachiSion requested changes

2021-11-29 01:52 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/common/GroupKey.java
> +import com.alibaba.nacos.common.main.java.utils.StringUtils;
Why use this?

2022-04-13 08:12 UTC, Deweywilliams approved these changes
Unauthorized user need real name and address to log in this phone without any links involved

2022-05-09 05:15 UTC, KomachiSion commented
CLA not sign for a long time.

2022-05-09 05:15 UTC, closed without merging