[ISSUE #3046] Unify the treatment of constant variables and reduce the usage of "magic numbers"
alibaba/nacos pull request #7294
Opened 2021-11-25 15:27 UTC by ArthurMograbi

## What is the purpose of the change
To resolve issue #3046, unify the treatment of constant variables and reduce the usage of "magic numbers"

## Brief changelog
Replacement of some of the usage of "magic numbers" for a cleaner and more maintainable approach and unify some discordand usages of the same variables

## Verifying this change
eclipse-pmd was used to verify the changes

2021-11-29 01:49 UTC, KomachiSion requested changes
I think your jdk version is too old. Please upgrade jdk version to at lease 1.8.

2021-11-29 01:49 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
> +    private final AtomicReference<Map<String, CacheData>> cacheMap = new AtomicReference<Map<String, CacheData>>(
Why add type?

2021-12-16 23:49 UTC, ArthurMograbi commented
> I think your jdk version is too old. Please upgrade jdk version to at lease 1.8.

Thank you for the heads up! There was something wrong with my workspace that caused java to default to an earlier version

2022-01-09 14:35 UTC, realJackSun commented
1 Do not use magic number
2 Remove the types as sion says

2022-05-09 05:16 UTC, KomachiSion commented
CLA not sign for a long time.

2022-05-09 05:16 UTC, closed without merging