[ISSUE#7344] subscruber ITCase runs failed when use httpClientProxy only
alibaba/nacos pull request #7352
Opened 2021-12-03 11:53 UTC by lpaz010

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fixes #7344 

## Brief changelog

Modify `NamingUtils#getGroupedName(final String serviceName, final String groupName)`,  if `serviceName` has combined like '_groupName_A@@serviceName_A_' and `groupName` is nil, then return serviceName directly.

## Verifying this change

run `Subscribe_ITCase` and `SubscribeCluster_ITCase` with `HttpClientProxy` only.

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2021-12-05 04:17 UTC, lpaz010 commented
可以升级JUnit版本高于4.12嘛

2022-01-07 10:17 UTC, realJackSun requested changes

2022-01-07 10:17 UTC, realJackSun commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +            // fix #7344
集成测试不过最好还是直接修改测试类吧，不要直接修改代码

2022-01-07 12:10 UTC, MajorHe1 commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +            // fix #7344
这个我觉得不是集成测试的问题，就是1.x版本和2.x版本推送的逻辑实现不一样，一个把group跟name拼接起来了，一个没有拼接。虽然正常使用没有出现问题，因为2.x的客户端都是长连接推送，但毕竟问题还是存在的，在客户端多用一个判断来兼容感觉无伤大雅。

2022-01-26 02:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=7352) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=7352) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=7352) it.</sub>

2022-05-09 05:13 UTC, KomachiSion commented
CLA not sign for a long time.

2022-05-09 05:13 UTC, closed without merging