feat: add version data compare in the history list
alibaba/nacos pull request #7428
Opened 2021-12-15 08:54 UTC by MisterChangRay

## What is the purpose of the change
fix #7424 

in the history list; add compare opration
在历史版本中添加比较选项， 比较版本和历史版本的差异。 方便了解历史配置变动

if  user want push configration to the product environment, the fuction can be used
这种需求可能会在用户上线时被使用， 通常来说 用户测试环境 需要迁移到线上环境时， 可以通过此功能分析配置变动

## Brief changelog

## Verifying this change
![image](https://user-images.githubusercontent.com/16421384/146154549-b1bc6e64-a925-4eea-888e-0f0d982783cd.png)
![image](https://user-images.githubusercontent.com/16421384/146154578-d9bb62cf-848c-4beb-9a67-c65e5d286262.png)

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-01-26 02:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=7428) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=7428) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=7428) it.</sub>

2022-02-09 02:40 UTC, realJackSun commented
Looks Good.

2022-06-28 06:01 UTC, merged

2022-06-28 06:13 UTC, ZebulonFeng requested changes
spell advice

2022-06-28 06:13 UTC, ZebulonFeng commented on console-ui/src/locales/en-US.js
> +    historyCompareLastVersion: 'Lasted Release Version',
Maybe replace with these words are better?

historyCompareLastVersion -> historyCompareLatestVersion
Lasted  -> Latest

2022-06-28 06:13 UTC, ZebulonFeng commented on console-ui/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
> +    this.getConfig(-1, tenant, serverId, this.dataId, this.group).then(lasted => {
lasted  -> latest

2022-06-28 06:13 UTC, ZebulonFeng commented on console-ui/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
> +        this.diffEditorDialog.current.getInstance().openDialog(selected.content, lasted.content);
lasted  -> latest

2022-06-28 06:13 UTC, ZebulonFeng commented on console-ui/src/locales/zh-CN.js
> +    historyCompareLastVersion: '最新版本',
historyCompareLastVersion -> historyCompareLatestVersion

2022-06-28 06:13 UTC, ZebulonFeng commented on console-ui/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
> +            originalArea={locale.historyCompareLastVersion}
historyCompareLastVersion -> historyCompareLatestVersion