[ISSUE #7575] Support hostname resolve
alibaba/nacos pull request #7610
Opened 2022-01-10 08:48 UTC by onewe

Close #7575

Use `InetAddress.getAllByName` to resolve the domain if `DOMAIN_PATTERN` doesn't match it 

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-01-11 08:26 UTC, li-xiao-shuang approved these changes

2022-01-12 03:23 UTC, KomachiSion commented
The problem cause 1.4.1 client has big bug, So please submit the strong reason to parse host by system.

2022-01-12 03:23 UTC, KomachiSion requested changes
The problem cause 1.4.1 client has big bug, So please submit the strong reason to parse host by system.

2022-01-12 03:43 UTC, KomachiSion commented
Close Pr reason submit in issue.

2022-01-12 03:43 UTC, closed without merging