[ISSUE #7621] Add hasChange judgement in ServerMemberManager to avoid useless nacos-cluster log output
alibaba/nacos pull request #7622
Opened 2022-01-11 11:03 UTC by MajorHe1

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #7621 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-01-11 11:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=7622) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=7622) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=7622) it.</sub>

2022-01-12 03:20 UTC, KomachiSion requested changes

2022-01-12 03:20 UTC, KomachiSion commented on core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
> +            Loggers.CLUSTER.debug("[serverlist] not updated, is still : {}", finalMembers);
Judge logger.isDebugEnabled

2022-01-12 04:18 UTC, MajorHe1 commented on core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
> +            Loggers.CLUSTER.debug("[serverlist] not updated, is still : {}", finalMembers);
already added.

2022-02-21 08:07 UTC, KomachiSion approved these changes

2022-02-21 08:08 UTC, merged