update log4j and protobuf-java version
alibaba/nacos pull request #7630
Opened 2022-01-11 14:30 UTC by hujun-w-2

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

update log4j and protobuf-java version

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-01-12 03:11 UTC, KomachiSion requested changes
log4j的版本可以直接合并，但是protobuf需要测试一下编译和运行是否会有问题。

是否有测试过protobuf升级后的影响？

2022-01-12 04:54 UTC, hujun-w-2 commented
> log4j的版本可以直接合并，但是protobuf需要测试一下编译和运行是否会有问题。
> 
> 是否有测试过protobuf升级后的影响？
修改后 mvn clean install正常，启动也正常

2022-01-12 06:08 UTC, realJackSun commented
> > log4j的版本可以直接合并，但是protobuf需要测试一下编译和运行是否会有问题。
> > 是否有测试过protobuf升级后的影响？
> > 修改后 mvn clean install正常，启动也正常

protobuf文件都能编译出来对吧？用长连接的客户端链接一下试试，看配置和服务是否都能发布上。

2022-01-14 07:44 UTC, realJackSun approved these changes

2022-01-14 07:46 UTC, KomachiSion approved these changes

2022-01-14 07:46 UTC, merged