[ISSUE#6999]add Feature for logback auto refresh
alibaba/nacos pull request #7631
Opened 2022-01-11 14:45 UTC by hujun-w-2

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change
from #6999
Supports Nacos managed logback XML configuration file. After the console is modified, the service will take effect dynamically.
支持nacos托管logback.xml配置文件，控制台修改后，服务动态生效。

## Brief changelog

XX

## Verifying this change
The test has been completed locally. Users only need to reference the SDK to have this feature
已经本地完成测试，用户只需要引用sdk即可拥有该特性

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-01-12 03:09 UTC, KomachiSion requested changes
1. 配置中心不应该感知配置的具体内容
2. nacos客户端自己的logback配置是否不需要在配置中心中管理？

2022-01-12 04:56 UTC, hujun-w-2 commented
> 1. 配置中心不应该感知配置的具体内容
> 2. nacos客户端自己的logback配置是否不需要在配置中心中管理？

我认为配置中心应该支持托管logback，对于用户来说，需要在运行中动态修改的配置文件都放在了nacos，那为什么logback不能放到nacos呢，我觉得这是生态的一种支持呀

2022-01-12 09:05 UTC, KomachiSion commented
> > 1. 配置中心不应该感知配置的具体内容
> > 2. nacos客户端自己的logback配置是否不需要在配置中心中管理？
> 
> 我认为配置中心应该支持托管logback，对于用户来说，需要在运行中动态修改的配置文件都放在了nacos，那为什么logback不能放到nacos呢，我觉得这是生态的一种支持呀

能放，当时不应该有nacos-client来加载。应该由客户自己加载，nacos只通知他logback的配置变了

2022-01-12 09:06 UTC, KomachiSion commented
> > > 1. 配置中心不应该感知配置的具体内容
> > > 2. nacos客户端自己的logback配置是否不需要在配置中心中管理？
> > 
> > 
> > 我认为配置中心应该支持托管logback，对于用户来说，需要在运行中动态修改的配置文件都放在了nacos，那为什么logback不能放到nacos呢，我觉得这是生态的一种支持呀
> 
> 能放，但是不应该有nacos-client来加载。应该由客户自己加载，nacos只通知他logback的配置变了

如果需要做成功能，应该做一个插件或者其他工程，依赖nacos-client的配置发现机制来做。

2022-01-15 03:56 UTC, hujun-w-2 commented
> > > > 1. 配置中心不应该感知配置的具体内容
> > > > 2. nacos客户端自己的logback配置是否不需要在配置中心中管理？
> > > 
> > > 
> > > 我认为配置中心应该支持托管logback，对于用户来说，需要在运行中动态修改的配置文件都放在了nacos，那为什么logback不能放到nacos呢，我觉得这是生态的一种支持呀
> > 
> > 
> > 能放，但是不应该有nacos-client来加载。应该由客户自己加载，nacos只通知他logback的配置变了
> 
> 如果需要做成功能，应该做一个插件或者其他工程，依赖nacos-client的配置发现机制来做。

1.托管logback不需要每次配置变更都帮用户加载，只需要帮用户加载一次就够了，变更logback扫描的是nacos本地缓存文件。
2.做成插件，可以贡献到社区吗？
3.如果改成在springboot的sdk里面启动加载配置的时候做来适配一次logback，看是否可行，不影响配置变更的逻辑，配置变更的时候logback是读的本地缓存文件。

2022-02-09 06:04 UTC, closed without merging