[1.x] Patch v1.x set default connection lease request timeout
alibaba/nacos pull request #7801
Opened 2022-02-21 12:35 UTC by zrlw

## What is the purpose of the change
1. set default connection lease request timeout to avoid OOM under continuously huge beat requestions.
2. merge default connection configurations to each http client request.
3. add IOReactorExceptionHandler and log ioreactor shutdown reason.

2022-03-08 01:26 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            if (defaultConfig.getConnectionRequestTimeout() <= 0) {
httpClientConfig == null， CloseableHttpClient已经包含了默认RequestConfig，所以这里不需要重新设置

2022-03-08 01:26 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                                ? defaultConfig.getConnectionRequestTimeout() : DEFAULT_CONNECTION_REQUEST_TIMEOUT))
ConnectionRequestTimeout的默认值可以放在HttpClientConfigBuilder里

2022-03-08 01:28 UTC, Maijh97 approved these changes

2022-03-08 01:28 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            if (defaultConfig.getConnectionRequestTimeout() <= 0) {
httpClientConfig == null， CloseableHttpClient已经包含了默认RequestConfig，所以这里不需要重新设置

2022-03-08 01:28 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +        requestBase.setConfig(RequestConfig.copy(defaultConfig)
connectionRequestTimeout 默认值可以放到HttpClientConfigBuilder里面

2022-03-08 01:29 UTC, Maijh97 requested changes

2022-03-08 01:29 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                requestBase.setConfig(RequestConfig.copy(defaultConfig)
httpClientConfig == null， CloseableHttpClient已经包含了默认RequestConfig，所以这里不需要重新设置

2022-03-08 01:29 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() > 0
ConnectionRequestTimeout 默认值可以放到HttpClientConfigBuilder里面

2022-03-08 03:25 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() > 0
如果requestBase设置了参数，执行到InternalHttpClient#doExecute时只有requestBase的参数有效：
```
localcontext.setRequestConfig(config);
```
HttpClientConfigBuilder配置的默认参数都会被舍弃。

2022-03-08 03:43 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() > 0
我知道，我的意思是connectionRequestTimeout默认值放到HttpClientConfigBuilder里面，而defaultConfig是由HttpClientConfigBuilder构建出来的，这里的代码就不需要那么复杂了。而ConnectionRequestTimeout通常是在构建clinet实例的时候就已经指定了，而这里针对单个请求更新的配置，目前只会存在conTimeOutMillis和readTimeOutMillis

2022-03-08 04:11 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() > 0
我不确定是否所有的httpclient（包括以后的版本）一定会通过HttpClientConfigBuilder的build方法创建，所以只是简单加了个兜底机制，没有配置这个参数就补一个缺省配置。

2022-03-08 05:34 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() > 0
目前nacos所有的httpclient使用，都会通过NacosRestTemplate和NacosAsyncRestTemplate来使用了

2022-03-08 06:35 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() > 0
AbstractHttpClientFactory#createNacosAsyncRestTemplate方法没有传这个参数吧，apache的HttpAsyncClientBuilder没有设置租借超时的方法，异步httpclient通过HttpClientConfigBuilder搞不定。

2022-03-08 06:47 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() > 0
参考代码https://github.com/alibaba/nacos/blob/adebab9b74b359d8c95eb33f6cc60140a1176347/common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java#L88-L95
不管是createNacosAsyncRestTemplate还是createNacosRestTemplate都会使用通过com.alibaba.nacos.common.http.HttpClientConfig.HttpClientConfigBuilder构造RequestConfig

2022-03-08 07:10 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() > 0
ok，我改一下

2022-03-08 08:06 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() > 0
顺便提了一个pr到develop分支: #7906

2022-03-08 13:50 UTC, Maijh97 requested changes

2022-03-08 13:50 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
当前请求，还是只保留设置connectTimeout和socketTimeout就好。connectionRequestTimeout更适合是在构建NacosAsyncRestTemplate或NacosAsyncRestTemplate的时候去指定。

2022-03-08 14:10 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
补充一下，就算在构建NacosAsyncRestTemplate或NacosAsyncRestTemplate的时候没有设置connectionRequestTimeout，HttpClientConfigBuilder的connectionRequestTimeout默认值也会作用。

2022-03-08 15:49 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
merge的处理是参照apache的HttpComponentsClientHttpRequestFactory#mergeRequestConfig和HttpComponentsHttpInvokerRequestExecutor#mergeRequestConfig代码，当然是否要和apache的处理方式保持一致还是你们最终确定吧。

2022-03-09 01:11 UTC, Maijh97 requested changes

2022-03-09 01:11 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
apache的httpClient实现是会更灵活些，但是NacosAsyncRestTemplate和NacosAsyncRestTemplate的实现，目的是为了统一框架内的httpClient使用，而作为使用方，我更倾向在构建NacosAsyncRestTemplate和NacosAsyncRestTemplate的时候去设置connectionRequestTimeout

2022-03-09 01:13 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
apache的httpClient实现确实更灵活些，但是NacosAsyncRestTemplate和NacosAsyncRestTemplate的实现，目的是为了统一框架内的httpClient使用，而作为使用方，我更倾向在构建NacosAsyncRestTemplate和NacosAsyncRestTemplate的时候去设置connectionRequestTimeout

2022-03-09 01:21 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
而且现在要指定connectionRequestTimeout的默认值，如果需要针对单次请求去设置connectionRequestTimeout，就不能把默认值放到HttpClientConfig.HttpClientConfigBuilder，而是在AbstractHttpClientFactory#getRequestConfig去设置默认值，要不然 httpClientConfig.getConnectionRequestTimeout() > 0 这个条件永远都为true

2022-03-09 01:54 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
的确，应该没有单次请求将ConnectionRequestTimeout设成<=0的情况，那么只在NacosAsyncRestTemplate和NacosAsyncRestTemplate创建requestConfig时设置吧。

2022-03-09 02:08 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
merge方法如果不设置setConnectionRequestTimeout，那么HttpClient#httpPost这个代码里的setConnectionRequestTimeout(5000)是不是可以删掉了？因为设置了merge方法也不会合并它。

2022-03-09 02:12 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
要么merge不做判断了，直接重设这个三个参数？
```
    private static void mergeDefaultConfig(HttpRequestBase requestBase, HttpClientConfig httpClientConfig, RequestConfig defaultConfig) {
        if (httpClientConfig == null) {
            return;
        }
        requestBase.setConfig(RequestConfig.copy(defaultConfig)
                .setConnectTimeout(httpClientConfig.getConTimeOutMillis())
                .setSocketTimeout(httpClientConfig.getReadTimeOutMillis())
                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout()).build());
    }
  ```

2022-03-09 02:18 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
ServerHttpAgent和HttpClient为单次请求都重设了ReadTimeOutMillis，ConTimeOutMillis，这些参数貌似是用户可以控制的的入参？有没有用户自定义ConnectionRequestTimeout的需求呢？

2022-03-09 02:39 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
> ServerHttpAgent

目前使用只有设置ReadTimeOutMillis，ConTimeOutMillis，而ConnectionRequestTimeout都是在构建NacosAsyncRestTemplate和NacosAsyncRestTemplate时候去设置的，所以我想着单次请求就还是保留设置ReadTimeOutMillis，ConTimeOutMillis就好了

2022-03-09 02:48 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
> HttpClient#httpPost这个代码里

要不就在AbstractHttpClientFactory#getRequestConfig去设置默认值吧，之前调用哪里就不改了。

2022-03-09 03:05 UTC, zrlw commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
> AbstractHttpClientFactory

如果修改AbstractHttpClientFactory#getRequestConfig，需要加判断处理吧，当ConnectionRequestTimeout<0时才设为默认的5s：
```
protected RequestConfig getRequestConfig() {
        HttpClientConfig httpClientConfig = buildHttpClientConfig();
        return RequestConfig.custom().setConnectTimeout(httpClientConfig.getConTimeOutMillis())
                .setSocketTimeout(httpClientConfig.getReadTimeOutMillis())
                .setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout() < 0 ? 5000 : httpClientConfig.getConnectionRequestTimeout())
                .setContentCompressionEnabled(httpClientConfig.getContentCompressionEnabled())
                .setMaxRedirects(httpClientConfig.getMaxRedirects()).build();
    }
```
相比之下，直接修改HttpClientConfigBuilder的connectionRequestTimeout初值，把-1改为5s是不是更简单一点。

2022-03-09 03:30 UTC, Maijh97 commented on common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
> +            builder.setConnectionRequestTimeout(httpClientConfig.getConnectionRequestTimeout());
方便加个钉钉？这里沟通有点不太方便，我的钉钉号：maijh97

2022-03-09 07:46 UTC, Maijh97 approved these changes

2022-03-09 08:02 UTC, merged