[1.x] Patch v1.x service synchronzied process
alibaba/nacos pull request #7812
Opened 2022-02-21 16:08 UTC by zrlw

## What is the purpose of the change
add synchronized control to avoid concurrent issue.

2022-02-23 08:43 UTC, realJackSun commented
@zrlw 老兄，方便加个钉钉交流一下吗？我钉钉 sunli139139

2022-02-23 08:47 UTC, realJackSun requested changes

2022-02-23 08:47 UTC, realJackSun commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/ClusterController.java
> +        synchronized (service) {
这个接口使用上还是比较频繁的，直接加一个大锁会导致性能急剧降低。如果有线程安全风险可以考虑在客户端侧通过多次更新补齐。
如果一定要这么搞的话，建议做一下压力测试。

2022-02-23 10:35 UTC, zrlw commented
我在nacos社区群2，钉钉搜不到你啊-------- 原始邮件 --------发件人： realJackSun ***@***.***>日期： 2022年2月23日周三 下午4:43收件人： alibaba/nacos ***@***.***>抄送： zrlw ***@***.***>, Mention ***@***.***>主    题： Re: [alibaba/nacos] [1.x] Patch v1.x service synchronized process (PR #7812)

@zrlw 老兄，方便加个钉钉交流一下吗？我钉钉 sunli139139



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-02-23 11:03 UTC, zrlw commented on naming/src/main/java/com/alibaba/nacos/naming/controllers/ClusterController.java
> +        synchronized (service) {
这个问题是压测发现的，cluster.init方法创建了多个HealthCheckTask，加了同步锁也解决不了，后来确定是update方法对同一个service（有几百个instance）创建了多个cluster，所以cluster.init方法即使加了互斥，也没有用。
我们压测的结果显示加锁后的性能没有损失，加锁的代码本身没有复杂操作，平均执行耗时几个ms。

2022-03-03 07:28 UTC, li-xiao-shuang commented
> 我在nacos社区群2，钉钉搜不到你啊

在群里找 涌月

2022-10-01 06:25 UTC, closed without merging