[develop] add request type field at the head of task data, exchange parse order between Log and GetRequest
alibaba/nacos pull request #7871
Opened 2022-03-02 03:22 UTC by zrlw

## What is the purpose of the change
see #7757

2022-03-03 05:31 UTC, KomachiSion requested changes
这会导致升级不兼容。

2022-03-03 05:39 UTC, KomachiSion commented
我同意两次try catch非常不优雅，但是目前这样运行起来无问题，

关于issue中提出的关于先Write的异议，目前没有WriteRequest只设置了2个字段，我查看至少都有设置3个以上，比如data，operation和group。

因此在找到合理的替代方式之前建议保持原样。

2022-03-03 05:41 UTC, KomachiSion requested changes

2022-03-03 05:41 UTC, KomachiSion commented on consistency/src/main/java/com/alibaba/nacos/consistency/ProtoMessageUtil.java
> +                    result = ReadRequest.parseFrom(bytes);
bytes中添加了2个标示位， parse之前应该移除掉这两个标示位，才能正确解析吧？

2022-03-03 08:48 UTC, zrlw commented on consistency/src/main/java/com/alibaba/nacos/consistency/ProtoMessageUtil.java
> +                    result = ReadRequest.parseFrom(bytes);
不用删除，只是解析的结果多了个unknown fields，field的名称为编号7，grpc服务端和客户端可以通过unknown fields配置自己特有的字段，目的就是为了相互兼容老版本

2022-03-03 08:49 UTC, zrlw commented
> 这会导致升级不兼容。

兼容的，利用的是unknown fields机制

2022-03-08 03:29 UTC, zrlw commented
> 有搭建集群进行一下测试吗？

1.x一直在用集群压测试，2.0只测了单元功能。

2022-03-10 01:54 UTC, KomachiSion approved these changes

2022-03-10 01:54 UTC, merged