[ISSUE #7971] fix ClusterVersionJudgement#ClusterVersionJudge Task never stop
alibaba/nacos pull request #7972
Opened 2022-03-22 03:21 UTC by ye213

## What is the purpose of the change
fix bug #7971 

## Brief changelog
ClusterVersionJudgement在执行runVersionListener的时候增加判断，如果所有成员已经是新版本，且通知成功，则不再执行后续的runVersionListener

## Verifying this change
已经通知过后，就不会再次提交runVersionListener任务

2022-03-22 03:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=7972) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=7972) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=7972) it.</sub>

2022-03-23 01:40 UTC, KomachiSion approved these changes

2022-03-23 01:53 UTC, KomachiSion commented
CI can't pass. Please fix them.

2022-03-23 01:53 UTC, KomachiSion requested changes
CI can't pass. Please fix them.

2022-03-23 02:23 UTC, ye213 commented
> CI can't pass. Please fix them.

Already fix and pass the CI

2022-03-28 02:21 UTC, KomachiSion approved these changes

2022-03-28 02:21 UTC, merged