change ldapLogin method
alibaba/nacos pull request #8032
Opened 2022-03-29 09:16 UTC by StandardStudent

更改了ldap登录方式为指定ldap结构下进行搜索，相关配置项可在application中配置

2022-03-29 09:22 UTC, StandardStudent commented
@onewe 已完成CLA,并且当前未看到develop分支冲突

2022-03-29 09:54 UTC, onewe commented
也要考虑 支持不同的 `authentication` 和 复杂的 `filter`

2022-03-30 02:14 UTC, KomachiSion requested changes

2022-03-30 02:14 UTC, KomachiSion commented on plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProvider.java
> +
Please do not change indents. Please use nacos codestyle to reformat codes.

2022-03-30 02:14 UTC, KomachiSion commented on plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProvider.java
> +import javax.naming.directory.*;
import * can't pass the checkstyle I think.

2022-03-30 02:14 UTC, KomachiSion commented on plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProvider.java
> +import jdk.jpackage.internal.Log;
Why import this log?

2022-04-11 02:31 UTC, KomachiSion commented
https://github.com/alibaba/nacos/pull/8062

2022-04-11 02:31 UTC, closed without merging