Fix AutoExpireCache NPE
alibaba/nacos pull request #8162
Opened 2022-04-15 01:52 UTC by Oliverwqcwrw

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fix #8153 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-05-13 04:20 UTC, Oliverwqcwrw commented
@onewe 如果有时间的话帮忙check一下

2022-05-15 04:35 UTC, onewe commented on common/src/main/java/com/alibaba/nacos/common/cache/decorators/AutoExpireCache.java
> +    public synchronized V get(K key) {
我认为加锁并不能解决问题,NPE是发生在`isExpire`方法里面,加了锁任然会有这个问题

2022-05-15 08:28 UTC, onewe approved these changes

2022-05-16 02:32 UTC, KomachiSion requested changes
should `itemProperties==null` return true? which mean the item is expired

2022-05-16 03:09 UTC, KomachiSion commented
Is there has unit test?

2022-05-16 03:12 UTC, Oliverwqcwrw commented
> Is there unit test?

This problem is a low probability event under multi-threading, and the feeling plus UT may not be able to hit this problem

2022-05-18 02:59 UTC, KomachiSion submitted a review, later dismissed

2022-05-18 03:09 UTC, KomachiSion commented
> > Is there unit test?
> 
> This problem is a low probability event under multi-threading, and the feeling plus UT may not be able to hit this problem

Add unit test is mean your changes is expected, and can check others' change

2022-05-18 04:37 UTC, Oliverwqcwrw commented
> > > Is there unit test?
> 
> > 
> 
> > This problem is a low probability event under multi-threading, and the feeling plus UT may not be able to hit this problem
> 
> 
> 
> Add unit test is mean your changes is expected, and can check others' change 

done

2022-05-20 06:52 UTC, KomachiSion approved these changes

2022-05-20 06:52 UTC, merged