[ISSUE #8186] Fix `receive empty entity!` error
alibaba/nacos pull request #8192
Opened 2022-04-17 10:06 UTC by liqipeng

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-04-18 03:16 UTC, KomachiSion requested changes
建议尽量避免面向null编程

2022-04-18 03:49 UTC, KomachiSion commented
是否可以在接收端判断？ 如果在发送端判断直接丢弃发送，担心会导致事件丢失。

2022-04-18 03:49 UTC, KomachiSion commented
是否可以在接收端判断？ 如果在发送端判断直接丢弃发送，担心会导致事件丢失。

2022-04-18 05:32 UTC, liqipeng commented
> 是否可以在接收端判断？ 如果在发送端判断直接丢弃发送，担心会导致事件丢失。

1. 目前的变更方式是没有产生新的消息丢失的，同时增加了相关日志，便于问题的定位（至于是否由消息丢失还是正常删除导致的，需要进一步全流程去梳理）；
2. 在接收端判断会比较尴尬：接收端丢弃的话如果返回失败会导致发送端的重试，如果返回成功似乎也是比较牵强；
3. 退一步说，如果按你的方案在接收端去忽略消息并输出日志，当真的出现消息丢失的时候会由于**异常信息已经不在源节点**、**消息处理的上下文变了**而**更难**定位问题 ——相比于是否是面向null编程的思考，在源节点定位问题应该会更方便；

综上，我认为我的这个改进在当前无法确定是正常删除导致问题还是消息丢失导致问题的情况下，至少是可以帮助日志分析、以及暴露问题的。不论怎样的原因造成的数据未找到，这里是有必要留下记录的。

（同时我也在从整体上分析是否可能有其他原因造成消息丢失，如定位到新的原因会会以新的 issue 反馈）

2022-04-18 08:53 UTC, liqipeng commented
@KomachiSion

2022-04-20 02:11 UTC, KomachiSion commented
> > 是否可以在接收端判断？ 如果在发送端判断直接丢弃发送，担心会导致事件丢失。
> 
> 1. 目前的变更方式是没有产生新的消息丢失的，同时增加了相关日志，便于问题的定位（至于是否由消息丢失还是正常删除导致的，需要进一步全流程去梳理）；
> 2. 在接收端判断会比较尴尬：接收端丢弃的话如果返回失败会导致发送端的重试，如果返回成功似乎也是比较牵强；
> 3. 退一步说，如果按你的方案在接收端去忽略消息并输出日志，当真的出现消息丢失的时候会由于**异常信息已经不在源节点**、**消息处理的上下文变了**而**更难**定位问题 ——相比于是否是面向null编程的思考，在源节点定位问题应该会更方便；
> 
> 综上，我认为我的这个改进在当前无法确定是正常删除导致问题还是消息丢失导致问题的情况下，至少是可以帮助日志分析、以及暴露问题的。不论怎样的原因造成的数据未找到，这里是有必要留下记录的。
> 
> （同时我也在从整体上分析是否可能有其他原因造成消息丢失，如定位到新的原因会会以新的 issue 反馈）

前两点可以再讨论， 消息丢弃确实有风险，需要梳理清楚风险影响。
不要面向null编程的意思是不要通过null来传递信息，比如保留直接返回空list或者空datum，在外部去判断空list或者空datum丢弃，而不是内部判断完了返回null，null的时候丢弃。

2022-04-20 05:52 UTC, liqipeng commented
> 



> > > 是否可以在接收端判断？ 如果在发送端判断直接丢弃发送，担心会导致事件丢失。
> > 
> > 
> > 
> > 1. 目前的变更方式是没有产生新的消息丢失的，同时增加了相关日志，便于问题的定位（至于是否由消息丢失还是正常删除导致的，需要进一步全流程去梳理）；
> > 2. 在接收端判断会比较尴尬：接收端丢弃的话如果返回失败会导致发送端的重试，如果返回成功似乎也是比较牵强；
> > 3. 退一步说，如果按你的方案在接收端去忽略消息并输出日志，当真的出现消息丢失的时候会由于**异常信息已经不在源节点**、**消息处理的上下文变了**而**更难**定位问题 ——相比于是否是面向null编程的思考，在源节点定位问题应该会更方便；
> > 
> > 综上，我认为我的这个改进在当前无法确定是正常删除导致问题还是消息丢失导致问题的情况下，至少是可以帮助日志分析、以及暴露问题的。不论怎样的原因造成的数据未找到，这里是有必要留下记录的。
> > （同时我也在从整体上分析是否可能有其他原因造成消息丢失，如定位到新的原因会会以新的 issue 反馈）
> 
> 前两点可以再讨论， 消息丢弃确实有风险，需要梳理清楚风险影响。 不要面向null编程的意思是不要通过null来传递信息，比如保留直接返回空list或者空datum，在外部去判断空list或者空datum丢弃，而不是内部判断完了返回null，null的时候丢弃。

1. 关于null的明白了，我的改法是考虑了些原来可能返回null，我本来的想法是逻辑上兼容原有的调用所以这么改的，没有去评估更长的调用链路是否适合直接去除null，这个我再详细评估一下；
2. 这个报错确实是可能是消息丢失导致的，但是由于原来的报错在接收端且是空的，前面没有具体信息不好定位。这个我调整一下，暂时先不改变原有逻辑（也就是那个```return;```逻辑先不加），只增加日志来辅助定位是什么问题导致了推送了null。后续有具体定位了再看怎改。

2022-04-22 08:09 UTC, KomachiSion commented
好，先按照这个方式改一下看看

2022-05-11 03:43 UTC, KomachiSion commented
Any process?

2022-05-13 02:25 UTC, liqipeng commented
基于添加的日志已有大概线索，触发原因大概是反注册清空了实例集合或者service被删除。最近会看看怎么修复。

2022-05-16 02:25 UTC, KomachiSion commented
> 基于添加的日志已有大概线索，触发原因大概是反注册清空了实例集合或者service被删除。最近会看看怎么修复。

OK, I will close this PR and you can submit a new PR which linked this PR.

2022-05-16 02:25 UTC, closed without merging