remove redundant code
alibaba/nacos pull request #8200
Opened 2022-04-18 13:38 UTC by qiugongzi

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fix https://github.com/alibaba/nacos/issues/8193
## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-04-18 13:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=8200) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=8200) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=8200) it.</sub>

2022-04-19 14:35 UTC, li-xiao-shuang approved these changes

2022-04-20 02:44 UTC, KomachiSion requested changes

2022-04-20 02:44 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DefaultInstanceUpgradeHelper.java
> +        Instance v1 = new Instance();
constructor should not remove

2022-04-22 08:07 UTC, KomachiSion requested changes

2022-04-22 08:07 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DefaultInstanceUpgradeHelper.java
> +        Instance v1 = new Instance();
就是因为构造方法中有trim才需要用构造方法来构造，如果都是简单的set，反而可以直接用copy。

需要转换成v1的instance，就要按照v1的instance逻辑进行，而不是按照v2的逻辑。

因此这个trim很很可能是v1用于保证后续稳定运行而加的，不能去除。

2022-04-26 02:22 UTC, KomachiSion approved these changes
PR will merged after CI pass

2022-04-27 05:50 UTC, KomachiSion approved these changes

2022-04-27 05:50 UTC, merged