Client logback bug bak
alibaba/nacos pull request #8229
Opened 2022-04-21 10:57 UTC by hujun-w-2

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-04-22 16:32 UTC, shalk commented
i found #7596  make some bug, i did not figure it out .
In my case , when you change log level dynamic for nacos , it will not take effect with new context . so you should take good are of  either logger in the same context.  maybe the pr will fix my bug.

I do not know what the bug is for this pr , 

Is NacosContextInitializer and  NacosJorndan neccesarry ?  more ut or more  description  could make it clear

2022-04-23 03:08 UTC, hujun-w-2 commented
> i found #7596 make some bug, i did not figure it out . In my case , when you change log level dynamic for nacos , it will not take effect with new context . so you should take good are of either logger in the same context. maybe the pr will fix my bug.
> 
> I do not know what the bug is for this pr ,
> 
> Is NacosContextInitializer and NacosJorndan neccesarry ? more ut or more description could make it clear



> i found #7596 make some bug, i did not figure it out . In my case , when you change log level dynamic for nacos , it will not take effect with new context . so you should take good are of either logger in the same context. maybe the pr will fix my bug.
> 
> I do not know what the bug is for this pr ,
> 
> Is NacosContextInitializer and NacosJorndan neccesarry ? more ut or more description could make it clear

2022-04-23 03:08 UTC, hujun-w-2 commented
> i found #7596 make some bug, i did not figure it out . In my case , when you change log level dynamic for nacos , it will not take effect with new context . so you should take good are of either logger in the same context. maybe the pr will fix my bug.
> 
> I do not know what the bug is for this pr ,
> 
> Is NacosContextInitializer and NacosJorndan neccesarry ? more ut or more description could make it clear

The role of these two classes
1. Rewrite the method of registration savepoint to ensure that the loading of Nacos configuration does not affect the application configuration savepoint
2. Rewrite the configuration method without affecting the configuration path of logback automatic scanning

2022-04-25 10:08 UTC, KomachiSion requested changes
Why not rewrite `registerSafeConfiguration` and `informContextOfURLUsedForConfiguration` in  `NacosJoranConfigurator.java`?

2022-04-25 10:08 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java
> + * @author <a href="mailto:huangxiaoyu1018@gmail.com">hxy1991</a><a href="mailto:hujun3@xiaomi.com">hujun</a>
one author one line.

2022-04-26 02:12 UTC, hujun-w-2 commented
> Why not rewrite `registerSafeConfiguration` and `informContextOfURLUsedForConfiguration` in `NacosJoranConfigurator.java`?

1. Informcontextofurlusedforconfiguration is static and cannot be rewritten.
2. The nacoscontextinitializer has been removed.

2022-04-27 05:49 UTC, KomachiSion approved these changes

2022-04-27 05:50 UTC, merged