add nacos service register more instance of service
alibaba/nacos pull request #8263
Opened 2022-04-26 14:56 UTC by Chaos-coder

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change
Nacos Server：提供批量注册服务实例的方法
Nacos Client：使用grpc请求服务端注册多实际
Nacos SDK当前支持一个Client连接只支持一个服务注册一个服务实例，支持同一个Client注册多个服务实例
测试：测试了集群模式下和单机模式的SDK多服务实例注册，测试通过
---
Nacos server: a method of providing batch registration service instances
Nacos client: use grpc to request the server to register multiple instances
Currently, the Nacos SDK supports one client connection, and only one service instance can be registered for one service. the same client can register multiple service instances
Test: tested the SDK multi service instance registration in cluster mode and stand-alone mode, and the test passed

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-04-27 08:30 UTC, hujun-w-2 commented on naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
> +        return CollectionUtils.isEqualCollection(instancePublishInfos, publishInfos);
这里可以优化

2022-04-27 08:30 UTC, hujun-w-2 commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> +    //TODO PersistentClientOperationServiceImpl Nacos batchRegister
注释规范

2022-04-27 08:30 UTC, hujun-w-2 commented on naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/BatchInstanceRequestHandler.java
> +    //@Deprecated
废弃代码删除

2022-04-27 13:53 UTC, Chaos-coder commented on naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
> +        return CollectionUtils.isEqualCollection(instancePublishInfos, publishInfos);
> 这里可以优化

已优化

2022-04-27 13:53 UTC, Chaos-coder commented on naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/BatchInstanceRequestHandler.java
> +    //@Deprecated
> 废弃代码删除

已删除

2022-04-29 03:42 UTC, KomachiSion commented
The PR is really large, can you split it to multiple PRs?

2022-04-29 04:37 UTC, chenhao26-nineteen commented
> The PR is really large, can you split it to multiple PRs?

OK, I'll disassemble this pr

2022-05-11 03:43 UTC, KomachiSion requested changes
Your title is add `sdk`, but there are many classes in server.

2022-05-11 03:43 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java
> +     */
Add `@since $version` comment

2022-05-11 03:43 UTC, KomachiSion commented on api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
> +    public static void batchCheckInstanceIsLegal(List<Instance> instances) throws NacosException {
need check whether all instance is same `ephemeral`

2022-05-11 03:43 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
> +        getExecuteClientProxy(instances.get(0)).batchRegisterInstance(serviceName, groupName, instances);
Maybe should print logs

2022-05-11 03:43 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/RedoScheduledTask.java
> +                if (redoData instanceof BatchInstanceRedoData) {
abstract the different redo logics to one method such as `redoRegister`.
And move from line 79 to 86 to new method.

2022-05-11 03:43 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/InstanceRedoData.java
> +    protected InstanceRedoData() {
Why add this constructor?

2022-05-11 03:43 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/RedoData.java
> +    private  String serviceName;
why remove final?

2022-05-11 03:43 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
> +        //TODO http Batch Register Instance
throw an Unsupported exception.

2022-05-11 03:43 UTC, KomachiSion commented on config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPayloadPackageProvider.java
> + * @author hujun3
why change others author name?

2022-05-11 03:43 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
> +            InstancePublishInfo clientInstancePublishInfo = client.getInstancePublishInfo(singleton);
This class seems not sdk class.

2022-05-27 07:34 UTC, closed without merging