[ISSUE #8186] Fix ClassCastException: io.grpc.ClientInterceptors$InterceptorChannel cannot be cast to io.grpc.ManagedChannel
alibaba/nacos pull request #8276
Opened 2022-04-28 08:19 UTC by ZhengBing520

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

https://github.com/alibaba/nacos/issues/8275

## Brief changelog

Get the created channel directly

## Verifying this change

no output error log

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-04-28 08:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=8276) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=8276) before we can accept your contribution.<br/><hr/>**ZhengBing520** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=8276) it.</sub>

2022-04-28 08:33 UTC, ZhengBing520 reviewed
Adjust the channel acquisition method

2022-04-28 09:31 UTC, ZhengBing520 commented
![image](https://user-images.githubusercontent.com/32810704/165723140-578fcd4d-bd39-4d91-bd47-0ce1be794def.png)

2022-04-29 03:27 UTC, KomachiSion commented
1. your commit user is not your github user, you need change it.
2. Waiting CLA page load finished, and roll down the end and sign agree.

![image](https://user-images.githubusercontent.com/37170243/165881119-01e71f20-1376-4581-a0db-d5b5404f1510.png)
![image](https://user-images.githubusercontent.com/37170243/165881132-c98091a4-e5b9-4c83-8e02-751cc237031a.png)

2022-04-29 04:52 UTC, ZhengBing520 commented
> 1. your commit user is not your github user, you need change it.
> 2. Waiting CLA page load finished, and roll down the end and sign agree.
> 
> ![image](https://user-images.githubusercontent.com/37170243/165881119-01e71f20-1376-4581-a0db-d5b5404f1510.png) ![image](https://user-images.githubusercontent.com/37170243/165881132-c98091a4-e5b9-4c83-8e02-751cc237031a.png)

Thank you, it's taken care of

2022-05-11 03:24 UTC, KomachiSion commented
@shiyiyue1102 Please help review this PR.

2022-05-11 03:24 UTC, KomachiSion commented
@shiyiyue1102 Please help review this PR.

2022-05-11 06:33 UTC, Oliverwqcwrw requested changes

2022-05-11 06:33 UTC, Oliverwqcwrw commented on common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
> +        ManagedChannelBuilder<?> o = ManagedChannelBuilder.forAddress(serverIp, serverPort).executor(grpcExecutor)
```suggestion
        ManagedChannelBuilder<?> managedChannelBuilder = ManagedChannelBuilder.forAddress(serverIp, serverPort).executor(grpcExecutor)
```

2022-05-11 06:33 UTC, Oliverwqcwrw commented on common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
> +        return o.build();
```suggestion
        return managedChannelBuilder.build();
```

2022-05-11 06:48 UTC, ZhengBing520 commented on common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
> +        ManagedChannelBuilder<?> o = ManagedChannelBuilder.forAddress(serverIp, serverPort).executor(grpcExecutor)
hi，Whether line 141 needs to be deleted

2022-05-11 06:53 UTC, Oliverwqcwrw commented on common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
> +        ManagedChannelBuilder<?> o = ManagedChannelBuilder.forAddress(serverIp, serverPort).executor(grpcExecutor)
I think line 142 needs to be deleted

2022-05-11 06:54 UTC, ZhengBing520 commented on common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
> +        ManagedChannelBuilder<?> o = ManagedChannelBuilder.forAddress(serverIp, serverPort).executor(grpcExecutor)
Ok, submit it now

2022-05-11 07:01 UTC, ZhengBing520 commented
hello @Oliverwqcwrw  Submitted, please check

2022-05-11 07:14 UTC, shiyiyue1102 approved these changes

2022-05-11 08:24 UTC, KomachiSion requested changes
Can you add some unit test for your changes？

2022-05-11 09:01 UTC, ZhengBing520 commented
> Can you add some unit test for your changes？

After adjusting the code, local startup is normal.  How to add unit test?    Can you give me an example
thanks for you

2022-05-12 10:10 UTC, KomachiSion commented
There are many unit test in project, you can see any `src/test` in modules.

2022-05-12 10:13 UTC, ZhengBing520 commented
> There are many unit test in project, you can see any `src/test` in modules.

Do I only need to provide the two methods I add？

2022-05-13 01:46 UTC, KomachiSion commented
> > There are many unit test in project, you can see any `src/test` in modules.
> 
> Do I only need to provide the two methods I add？

We hope you can add the cases to cover your changes, which can test the class has same behavior after your changes.

2022-05-13 01:57 UTC, KomachiSion commented
CI can't pass after your changes.

2022-05-13 02:12 UTC, ZhengBing520 commented
> CI can't pass after your changes.

Let me check that I removed a referenceless method on my second commit ([GrpcClient.java] line 141)

2022-05-13 02:43 UTC, ZhengBing520 commented
> CI can't pass after your changes.

I have successfully executed the second time locally, shall we execute it again  ->  Continuous Integration / unix (ubuntu-latest, 8) (pull_request) 
![image](https://user-images.githubusercontent.com/32810704/168201007-eafd1a00-c2d8-4e88-9605-29163edf84c2.png)

2022-05-13 04:42 UTC, Oliverwqcwrw commented
https://github.com/alibaba/nacos/runs/6416290642?check_suite_focus=true
There may have some problem,You should check it and solve it

2022-05-13 06:26 UTC, ZhengBing520 commented
> https://github.com/alibaba/nacos/runs/6416290642?check_suite_focus=true There may have some problem,You should check it and solve it

I try to pull the latest code

2022-05-13 07:01 UTC, ZhengBing520 commented
> > https://github.com/alibaba/nacos/runs/6416290642?check_suite_focus=true There may have some problem,You should check it and solve it
> 
> I try to pull the latest code

hello @KomachiSion @Oliverwqcwrw Is it all right now, do you need me to rebase it？

2022-05-13 09:08 UTC, ZhengBing520 commented
![image](https://user-images.githubusercontent.com/32810704/168250967-ced541a2-b4e8-4dfc-bae4-be5048e66e5a.png)

2022-05-13 10:41 UTC, ZhengBing520 commented
hello @KomachiSion I resubmitted a PR：https://github.com/alibaba/nacos/pull/8374

2022-05-16 02:15 UTC, KomachiSion commented
> hello @KomachiSion I resubmitted a PR：#8374

OK, I will close this PR and move to new PR discuss and review.

2022-05-16 02:15 UTC, closed without merging

2022-10-11 08:04 UTC, ZhengBing520 commented
Thanks for the guidance. I've taken care of step two




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月29日(星期五) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] [ISSUE #8275] Fix ClassCastException: io.grpc.ClientInterceptors$InterceptorChannel cannot be cast to io.grpc.ManagedChannel (PR #8276)





  
your commit user is not your github user, you need change it.
 
Waiting CLA page load finished, and roll down the end and sign agree.
  

 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;