[ISSUE #8345] nacos2.0.4没有对clusterName进行校验，会出现实例成功注册，但实例列表查不出来的bug
alibaba/nacos pull request #8371
Opened 2022-05-13 04:17 UTC by bangbang2333

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

(https://github.com/alibaba/nacos/issues/8345)

添加clusterName校验，同时解决grpc吞异常问题。如果校验不通过，错误信息将返回到客户端，使用者可以看到错误原因

2022-05-15 09:47 UTC, Oliverwqcwrw approved these changes

2022-05-16 02:17 UTC, KomachiSion requested changes
Can you add some unit test for your changes?

2022-05-16 03:01 UTC, bangbang2333 commented
> Can you add some unit test for your changes?

i do not know how to 

> Can you add some unit test for your changes?

I don't know how to write unit tests, can someone(大佬) help me write it

2022-05-18 02:56 UTC, KomachiSion approved these changes

2022-05-18 02:57 UTC, merged

2022-06-20 06:37 UTC, liqipeng commented on api/src/main/java/com/alibaba/nacos/api/naming/pojo/Instance.java
>      }
@KomachiSion @bangbang2333  压测表明在这里进行正则校验增加了一定的性能损耗，特别是在RPC场景下的服务订阅方订阅的服务的实例数较多的场景。我觉得这里的校验应该放在注册地方的，而不是这个pojo里。