[ISSUE #8472]: Dependency Governance, Remove useless dependencies. (#8472)
alibaba/nacos pull request #8473
Opened 2022-05-28 05:56 UTC by CherishCai

issue #8472

## What is the purpose of the change

Dependency Governance, Remove useless dependencies.

## Brief changelog

XX

## Verifying this change
`mvn clean install -Dmaven.test.skip=true -P release-nacos`
Make sure there are no compile errors.
务必已保障没有编译错误。

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-05-28 05:57 UTC, CherishCai commented on console/pom.xml
> -            <artifactId>tomcat-embed-jasper</artifactId>
no jsp, all rest api

2022-05-28 05:58 UTC, CherishCai commented on pom.xml
> -                <groupId>commons-dbcp</groupId>
no use apache common dependencies

2022-05-30 02:20 UTC, KomachiSion requested changes

2022-05-30 02:20 UTC, KomachiSion commented on config/pom.xml
> -        <dependency>
In config module, nacos use aspect, remove it may cause usage problem.

2022-05-30 03:02 UTC, CherishCai commented on config/pom.xml
> -        <dependency>
spring-boot-starter-aop is enough, nested dependency aspectjweaver include aspectjrt
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
```

![image](https://user-images.githubusercontent.com/16837364/170909444-3b25b7e7-e450-49a4-b9c6-3baa44f31fc2.png)

2022-05-30 09:38 UTC, CherishCai commented on config/pom.xml
> -        <dependency>
我已经把依赖清理的改动，在线下环境部署了，Aop 也没有问题

2022-06-07 07:37 UTC, KomachiSion approved these changes

2022-06-07 07:38 UTC, KomachiSion commented
There are some conflicts with others commit.

2022-06-10 03:28 UTC, CherishCai commented
> There are some conflicts with others commit.

@KomachiSion pom.xm conflict resolved three times 😭😂

2022-06-13 02:31 UTC, KomachiSion approved these changes

2022-06-13 02:31 UTC, merged