Add log level judgment for some log outputs with performance cost
alibaba/nacos pull request #8599
Opened 2022-06-19 15:49 UTC by liqipeng

When size of ```newHosts``` is huge, it cost some performance even if the log level setted to ERROR.
```
        if (newHosts.size() > 0) {
            changed = true;
            NAMING_LOGGER.info("new ips({}) service: {} -> {}", newHosts.size(), newService.getKey(),
                    JacksonUtils.toJson(newHosts));
        }
```
It is better to add log level judgment like this :
```
        if (newHosts.size() > 0) {
            changed = true;
            if (NAMING_LOGGER.isInfoEnabled()) {
                NAMING_LOGGER.info("new ips({}) service: {} -> {}", newHosts.size(), newService.getKey(),
                        JacksonUtils.toJson(newHosts));
            }
        }
```

So I search some other places and do some changes.

2022-06-20 02:02 UTC, KomachiSion requested changes
I don't think we should do this for `info`, `error` and `warn` level.

1. most of users default level is higher than `info`, `error` and `warn`.
2. these logs not print frequantly, if so, there must be some other more important things, like the providers online and offline frequantly, which should be solve first not reduce logs.

2022-06-20 03:00 UTC, liqipeng commented
> I don't think we should do this for `info`, `error` and `warn` level.
> 
> 1. most of users default level is higher than `info`, `error` and `warn`.
> 2. these logs not print frequantly, if so, there must be some other more important things, like the providers online and offline frequantly, which should be solve first not reduce logs.

@KomachiSion We should give user a choice to choose whether pay some cost to output log. And these code is not the best pratice to output log.

2022-06-24 09:36 UTC, liqipeng commented
> > I don't think we should do this for `info`, `error` and `warn` level.
> > 
> > 1. most of users default level is higher than `info`, `error` and `warn`.
> > 2. these logs not print frequantly, if so, there must be some other more important things, like the providers online and offline frequantly, which should be solve first not reduce logs.
> 
> 一般业务当然不会有影响。但我遇到一些并发非常高、对性能敏感的业务通常会将日志调至ERROR级别，而且这类业务普遍实例数较多，而当服务提供方的滚动发版时会持续一定的时间产生变更通知，而且Dubbo框架的注册信息也是比较大的，所以我觉得很有必要处理好这里的日志。

@KomachiSion 有一些业务会把普通INFO日志也关闭的，日志会调至ERROR级别，这样在INFO日志代码进行无效的序列化是浪费啊。
```
        if (null == oldService) {
            NAMING_LOGGER.info("init new ips({}) service: {} -> {}", newService.ipCount(), newService.getKey(),
                    JacksonUtils.toJson(newService.getHosts())); // 即使日志级别调整到了ERROR，但是这行代码依然会执行序列化的
            return true;
        }
```
我想这主要是一个关于日志输出的最佳实践的问题吧，引用一下log4j文档(https://logging.apache.org/log4j/1.2/manual.html)：
```
Logging performance when logging is turned off.
When logging is turned off entirely or just for a [set of levels](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Hierarchy.html#setThresholdjava.lang.String), the cost of a log request consists of a method invocation plus an integer comparison. On a 233 MHz Pentium II machine this cost is typically in the 5 to 50 nanosecond range.

However, The method invocation involves the "hidden" cost of parameter construction.

For example, for some logger cat, writing,

     logger.debug("Entry number: " + i + " is " + String.valueOf(entry[i]));
    
incurs the cost of constructing the message parameter, i.e. converting both integer i and entry[i] to a String, and concatenating intermediate strings, regardless of whether the message will be logged or not. This cost of parameter construction can be quite high and it depends on the size of the parameters involved.
To avoid the parameter construction cost write:

      if(logger.isDebugEnabled() {
        logger.debug("Entry number: " + i + " is " + String.valueOf(entry[i]));
      }
   
This will not incur the cost of parameter construction if debugging is disabled. On the other hand, if the logger is debug-enabled, it will incur twice the cost of evaluating whether the logger is enabled or not: once in debugEnabled and once in debug. This is an insignificant overhead because evaluating a logger takes about 1% of the time it takes to actually log.

In log4j, logging requests are made to instances of the Logger class. Logger is a class and not an interface. This measurably reduces the cost of method invocation at the cost of some flexibility.

Certain users resort to preprocessing or compile-time techniques to compile out all log statements. This leads to perfect performance efficiency with respect to logging. However, since the resulting application binary does not contain any log statements, logging cannot be turned on for that binary. In my opinion this is a disproportionate price to pay in exchange for a small performance gain.
```

2022-06-24 09:39 UTC, liqipeng commented
> 我认为不会因为这个造成主要瓶颈，业务高并发的时候不会打这些日志，这些日志只有启动和变更的时候才会有。而且总日志量相对于业务日志本身也不高，没必要加高级别判断。
> 
> debug级别的同意增加判断。

而且作为sdk类的组件是要嵌入到业务系统的，业务提供可能会嵌入很多种类的sdk，各个sdk应该尽量减少对业务系统的损耗吧

2022-06-28 03:27 UTC, KomachiSion commented
你说的几个点都同意，我们的观点认为对于info,warn,error这几个级别没必要去判断是否可用， debug需要判断。仅此而已。

2022-06-28 03:36 UTC, KomachiSion commented
就算你打算增加client的日志打印和生产的效率，那error是不是不需要判断， cmdb是不是不需要判断（这个是运行在nacos服务端的）

如果cmdb增加，那整个nacos-server是不是都需要添加？

2022-06-28 03:38 UTC, KomachiSion commented
另外，nacos-client的info日志十分重要，如果不打印，对于排查问题时的困扰极大，而且本身日志量就很小，性能损耗很小，没必要为了极少量场景增加分支复杂度。

2022-06-28 04:31 UTC, liqipeng commented
> 另外，nacos-client的info日志十分重要，如果不打印，对于排查问题时的困扰极大，而且本身日志量就很小，性能损耗很小，没必要为了极少量场景增加分支复杂度。

加判断并不是正常情况不打印日志，而是让日志输出产生的消耗与日志级别的设定相匹配。
当日志级别为INFO时，是否加判断没有差异；当日志级别为ERROR时，哪些有资源消耗的日志输出代码是会白白浪费资源但是不输出INFO日志的。

2022-06-28 04:33 UTC, liqipeng commented
可能以上讨论暂时无法达成一致，我另起一个PR先修改debug相关吧，这个先关闭了。

2022-06-28 04:33 UTC, closed without merging

2022-06-28 05:19 UTC, liqipeng commented
看了下，排除掉INFO、ERORR的日志级别判断，没有必要另提PR了。