[ISSUE #8784] fix some bugs for Console UI
alibaba/nacos pull request #8787
Opened 2022-07-22 08:52 UTC by onewe

- add server.error.include-message property
- add no permission tip when push config
- use addAllowedOriginPattern instead of addAllowedOrigin
- remove RAM logic in the lib.js
- fix button type error and mode value error in NewConfig.js
- fix the password reset dialog can't show

Close #8784

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-07-22 09:14 UTC, pixystone requested changes

2022-07-22 09:14 UTC, pixystone commented on console-ui/src/locales/en-US.js
> +    publishFailed403: 'Publish failed. Without permission to create Configuration',
`No permission` is better.

2022-07-22 09:14 UTC, pixystone commented on console/src/main/resources/application.properties
> +server.error.include-message=ALWAYS
Need performance discussion.

2022-07-22 09:19 UTC, onewe commented on console-ui/src/locales/en-US.js
> +    publishFailed403: 'Publish failed. Without permission to create Configuration',
Ok

2022-07-25 01:55 UTC, KomachiSion approved these changes

2022-07-25 01:56 UTC, KomachiSion approved these changes

2022-07-25 01:56 UTC, merged