For #8310, add nacos-address-plugin module
alibaba/nacos pull request #8847
Opened 2022-08-01 13:51 UTC by MRGUOKING

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

For #8310 , add nacos-address-plugin module

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-08-01 15:13 UTC, The-Gamer-01 commented
Verifying this change需要通过和勾选下面的多选框

2022-08-09 09:33 UTC, brotherlu-xcq requested changes

2022-08-09 09:33 UTC, brotherlu-xcq commented on plugin/address/src/main/java/com/alibaba/nacos/plugin/address/spi/AddressPlugin.java
> +    void registerListener(Consumer<List<String>> addressListener);
The return value maked as AddressPlugin is better. The we can do register then start as a chain.

2022-08-09 09:33 UTC, brotherlu-xcq commented on plugin/address/src/main/java/com/alibaba/nacos/plugin/address/spi/AbstractAddressPlugin.java
> +        this.addressListener = addressListener;
We need to check the if the addressListener is empty.

2022-08-09 09:33 UTC, brotherlu-xcq commented on common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
> +    public static boolean isEqualCollection(final Collection a, final Collection b) {
If you want the collection not null, I think check it before you use it is better.

2022-08-09 09:33 UTC, brotherlu-xcq commented on common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
> +        } else {
The unnecessary usage of else.

2022-08-18 03:59 UTC, KomachiSion approved these changes

2022-08-19 14:29 UTC, merged