fix: [ISSUE#8699] Fix the problem that the client saves local files w…
alibaba/nacos pull request #8852
Opened 2022-08-02 05:35 UTC by hh13516117509

…ithout partitions

客户端在保存配置和服务实例信息到本地的时候,单纯的放在
user.home/nacos文件夹下,没有考虑如果本地有两类服务.连的是不同的nacos服务端,会导致读取到脏数据的问题.

Please do not create a Pull Request without creating an issue first.

What is the purpose of the change
For https://github.com/alibaba/nacos/issues/8699 nacos-client ServiceInfoHolder cache serviceInfo bug

Brief changelog
Added some formatting class and initialization paths methods

Verifying this change
Added some formatting class and initialization paths methods

Follow this checklist to help us incorporate your contribution quickly and easily:

[√ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
[√ ] Format the pull request title like [ISSUE https://github.com/alibaba/nacos/issues/123] Fix UnknownException when host config not exist. Each commit in the pull request should have a meaningful subject line and body.
[√ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[√ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
[√ ] Run mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true to make sure basic checks pass. Run mvn clean install -DskipITs to make sure unit-test pass. Run mvn clean test-compile failsafe:integration-test to make sure integration-test pass.

2022-08-04 01:59 UTC, KomachiSion requested changes

2022-08-04 01:59 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/constant/ServerAddressConstant.java
> +public class ServerAddressConstant {
Can't use static singleton, If config client and naming client connect different server will cause problem.

2022-08-04 02:12 UTC, hh13516117509 commented on client/src/main/java/com/alibaba/nacos/client/constant/ServerAddressConstant.java
> +public class ServerAddressConstant {
这个静态单例只是给配置客户端使用的,在NacosConfigService中设置,LocalConfigInfoProcessor中的静态代码块中使用,因为LocalConfigInfoProcessor的baseDir的初始化是在静态代码块中,本着小改动的原则, 所以才会在初始化LocalConfigInfoProcessor之前,NacosConfigService中提前暴露配置中心的服务地址.  命名客户端的服务地址是从命名配置中取的.两者应该没有交叉.

2022-08-09 06:33 UTC, hh13516117509 commented on client/src/main/java/com/alibaba/nacos/client/constant/ServerAddressConstant.java
> +public class ServerAddressConstant {
> 不能使用静态单例，如果配置客户端和命名客户端连接不同的服务器会导致问题。

这个静态单例只是给配置客户端使用的，在NacosConfigService中设置，LocalConfigInfoProcessor中的静态代码块中使用，因为LocalConfigInfoProcessor的baseDir的初始化是在静态代码块中，本着小改动的原则， 所以才会在初始化LocalConfigInfoProcessor之前，NacosConfigService中提前暴露配置中心的服务地址.命名客户端的服务地址是从命名配置中取的.两者应该没有交叉.

2022-08-10 03:11 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/constant/ServerAddressConstant.java
> +public class ServerAddressConstant {
那我就没看懂为什么要去改NacosConfigService中的内容了，如果不是打算共用，只修复naming模块的缓存冲突问题，为什么要改动到config的东西，最小改动不是应该只改naming的部分吗

2022-08-10 03:13 UTC, hh13516117509 commented on client/src/main/java/com/alibaba/nacos/client/constant/ServerAddressConstant.java
> +public class ServerAddressConstant {
> 那我就没看懂为什么要去改NacosConfigService中的内容了，如果不是打算共用，只修复naming模块的缓存冲突问题，为什么要改动到config的东西，最小改动不是应该只改naming的部分吗

因为在改动的过程中我发现config部分也存在这样的问题. 而且可能会读取到错误的本地文件.所以修复naming模块的同时对config模块也进行了修改.

2022-08-11 06:38 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/constant/ServerAddressConstant.java
> +public class ServerAddressConstant {
那我觉得你可能需要再想想了， 你现在的实现可能会导致config有重复的目录信息， 我记得配置中心是不同的服务地址本来就是在里层分离的。

另外静态单例在多配置中心的时候同样有干扰问题。

2022-08-11 07:06 UTC, hh13516117509 commented on client/src/main/java/com/alibaba/nacos/client/constant/ServerAddressConstant.java
> +public class ServerAddressConstant {
> 那我觉得你可能需要再想想了， 你现在的实现可能会导致config有重复的目录信息， 我记得配置中心是不同的服务地址本来就是在里层分离的。
> 
> 另外静态单例在多配置中心的时候同样有干扰问题。

额...不好意思哈哈,我用的客户端是2.0.3的,当时配置中心加载的时候会传入一个agentName, 实际上传入的是 "config_rpc_client" ,然后在后面拼上_nacos . 最终保存和读取的路径是 ${userhome}\nacos\config\config_rpc_client_nacos\***  我觉得这样是没办法做到分离的,所以进行了调整. 我看了最新的代码, #8202里面已经修复了. okok. 这块代码我进行一个剔除.

2022-08-12 08:55 UTC, KomachiSion requested changes

2022-08-12 08:55 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
> -
Why remove lines?

2022-08-12 08:55 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +            Map<String, ServiceInfo> map = serviceInfoHolder.readCache();
readCache. 不合理， 这个地方应该是把内存写入磁盘， 如果readCache不是从磁盘读进来再写磁盘？

2022-08-12 10:12 UTC, hh13516117509 commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +            Map<String, ServiceInfo> map = serviceInfoHolder.readCache();
> 

这块主要是考虑到内存中可能存在脏数据,因为在读取数据的时候,为了兼容性,会先从新的位置读取,没读取到再读取老的位置的数据.所以内存中可能会存在脏数据. 使用readCache是为了从新的位置读取最新的数据写入故障转移新的位置. 性能不佳是问题,但是应该能规避脏数据的问题.

2022-08-12 10:14 UTC, hh13516117509 commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +            Map<String, ServiceInfo> map = serviceInfoHolder.readCache();
> readCache. 不合理， 这个地方应该是把内存写入磁盘， 如果readCache不是从磁盘读进来再写磁盘？

这块主要是考虑到内存中可能存在脏数据,因为在读取数据的时候,为了兼容性,会先从新的位置读取,没读取到再读取老的位置的数据.所以内存中可能会存在脏数据. 使用readCache是为了从新的位置读取最新的数据写入故障转移新的位置. 性能不佳是问题,但是应该能规避脏数据的问题.

2022-08-15 02:13 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
> +            Map<String, ServiceInfo> map = serviceInfoHolder.readCache();
读磁盘只能启动的时候读一次，向内存中读， 后续不应该再读取磁盘了，否则改动就太大了。

2022-09-15 02:50 UTC, KomachiSion commented
There is no more response and changes in this PR, and this changes has some problem. If someone want to fix this problem, Please submit other PR.

2022-09-15 02:50 UTC, closed without merging