[ISSUE#8936]rpc client add system properties class
alibaba/nacos pull request #8937
Opened 2022-08-10 15:43 UTC by stone-98

## What is the purpose of the change

close #8936

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-08-10 15:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=8937) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=8937) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=8937) it.</sub>

2022-08-11 02:37 UTC, stone-98 commented
There is some code that has not yet been committed and will be committed later

2022-08-11 06:13 UTC, KomachiSion requested changes
请现在相关issue中讨论清楚方案。pr中的方案我认为不是很合适

2022-08-11 06:47 UTC, closed without merging

2022-08-11 06:56 UTC, stone-98 commented
好的，我再去了解一下相关功能。

> 请现在相关issue中讨论清楚方案。pr中的方案我认为不是很合适

好的，我再去了解一下相关功能。