[ISSUE #8931] Fix bug :BatchInstanceData cannot Serializable question
alibaba/nacos pull request #8940
Opened 2022-08-11 02:41 UTC by wuchubuzai2018

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change
For ISSUE #8931 
Fix BatchInstanceData cannot Serializable question。
append implement implements Serializable

## Brief changelog

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-08-11 06:01 UTC, KomachiSion requested changes

2022-08-11 06:01 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/BatchInstanceData.java
> +    private static final long serialVersionUID = 1L;
use auto generator serialVersionUID.

2022-08-11 07:46 UTC, wuchubuzai2018 commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/BatchInstanceData.java
> +    private static final long serialVersionUID = 1L;
> use auto generator serialVersionUID.

感谢大佬的指正，已更改为自动生成

2022-08-12 08:43 UTC, KomachiSion approved these changes

2022-08-12 08:44 UTC, merged