[ISSUE #8310] complete server addressing  in plugin way
alibaba/nacos pull request #9009
Opened 2022-08-22 12:56 UTC by MRGUOKING

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

for #8310, complete server addrssing in plugin way

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-08-31 10:46 UTC, brotherlu-xcq requested changes

2022-08-31 10:46 UTC, brotherlu-xcq commented on core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
> -/**
why remove this javadoc? If it's outdated, please give the latest.

2022-08-31 10:46 UTC, brotherlu-xcq commented on core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
> -    private static final int DEFAULT_MEMBER_CHANGE_EVENT_QUEUE_SIZE = 128;
why change the queue size?

2022-08-31 10:46 UTC, brotherlu-xcq commented on core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
> -            // fix#issue https://github.com/alibaba/nacos/issues/7230
why change the comment?

2022-09-05 01:32 UTC, T6252M approved these changes

2022-09-09 02:19 UTC, brotherlu-xcq approved these changes
LGTM

2022-09-13 07:42 UTC, merged