[ISSUE #9013] Enhance Rpc config related to one RpcClientConfig
alibaba/nacos pull request #9093
Opened 2022-09-05 05:49 UTC by karsonto

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-09-05 09:31 UTC, KomachiSion requested changes

2022-09-05 09:31 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientConfig.java
> +    ServerListFactory serverListFactory();
ServerlistManager不属于配置

2022-09-05 09:31 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
> +    private int sendRetryTimes;
为什么不从config中取， 而是又缓存一份？

2022-09-06 09:17 UTC, karsonto commented on common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
> +    private int sendRetryTimes;
已修改，请Review

2022-09-07 01:43 UTC, KomachiSion approved these changes

2022-09-07 01:43 UTC, merged