[ISSUE #9282]remove redundant judgment
alibaba/nacos pull request #9284
Opened 2022-10-09 11:25 UTC by RapperCL

[issue](https://github.com/alibaba/nacos/issues/9282)

2022-10-09 11:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=9284) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=9284) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=9284) it.</sub>

2022-10-10 01:52 UTC, KomachiSion requested changes
How about `cacheMap.get()` is null or `configChangeBatchListenResponse` is null?

2022-10-10 03:22 UTC, RapperCL commented
> How about `cacheMap.get()` is null or `configChangeBatchListenResponse` is null?

1  As a global variable, cacheMap is initialized when it is created.
` private final AtomicReference<Map<String, CacheData>> cacheMap = new AtomicReference<>(new HashMap<>());`

2022-10-10 03:28 UTC, RapperCL commented
2 requestProxy()-->rpcClientInner.request
![image](https://user-images.githubusercontent.com/44110731/194795347-d28397b3-9cad-4fed-a5cc-bb781be8c818.png)
If it is null, a null exception will be thrown in advance, so it will not return null

You can also see that there is no null judgment in other places where this method is called.
for example
![image](https://user-images.githubusercontent.com/44110731/194795454-7fa7adf8-9267-426d-8b9f-c87a91a9eb1e.png)

2022-10-10 03:46 UTC, KomachiSion approved these changes

2022-10-10 06:54 UTC, merged