[ISSUE #8684] Support prometheus http service discovery
alibaba/nacos pull request #9333
Opened 2022-10-16 11:37 UTC by karsonto

Fix Issue #8684
add enable to support prometheus service discovery config in application.properties
add prometheus service discovery uri config in application.properties

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-10-19 01:33 UTC, KomachiSion requested changes

2022-10-19 01:33 UTC, KomachiSion commented on console/src/main/resources/application.properties
> +server.servlet.encoding.force-response=true
Is this config will affect other api response?

2022-10-19 02:22 UTC, karsonto commented on console/src/main/resources/application.properties
> +server.servlet.encoding.force-response=true
根据官网的解析是强制在response content-type上加上字符集，不会对现有api造成影响
<img width="740" alt="image" src="https://user-images.githubusercontent.com/31433550/196581961-c6868149-13b7-43c1-9cdf-a5925652a9f1.png">

2022-10-21 01:43 UTC, KomachiSion commented
强制指定字符集可能会对配置中心有影响吧 @realJackSun @shiyiyue1102 看下

2022-10-21 13:19 UTC, karsonto commented
> 强制指定字符集可能会对配置中心有影响吧 @realJackSun @shiyiyue1102 看下

如果不加这个更加的奇怪，字符集是iso8859-1 ，加上这个才受控制

2022-10-24 01:52 UTC, KomachiSion commented
> > 强制指定字符集可能会对配置中心有影响吧 @realJackSun @shiyiyue1102 看下
> 
> 如果不加这个更加的奇怪，字符集是iso8859-1 ，加上这个才受控制

现在好像配置中心默认的返回编码都是utf-8，但是某些环境下会使用gbk， 如果这里强制使用utf-8， 返回的配置中文可能乱码，导致程序会有错误。

2022-10-24 01:57 UTC, karsonto commented
er....那我先用其他方法代替，还是等待 @realJackSun @shiyiyue1102 评估一下？

2022-10-24 02:25 UTC, realJackSun approved these changes

2022-10-31 04:04 UTC, KomachiSion commented
> er....那我先用其他方法代替，还是等待 @realJackSun @shiyiyue1102 评估一下？

先尝试找下其他办法吧。

2022-11-17 03:13 UTC, KomachiSion commented
Closed due to #9518

2022-11-17 03:13 UTC, closed without merging