Chooser use optimization
alibaba/nacos pull request #9392
Opened 2022-10-25 08:41 UTC by RapperCL

2022-10-26 07:10 UTC, KomachiSion requested changes

2022-10-26 07:10 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/naming/utils/Chooser.java
> -            weights = new double[items.size()];
I read this codes, I think this array size might be `index` no items.size()

2022-11-02 06:47 UTC, KomachiSion commented
I'm contacting the author for this part codes. After making sure the codes meaning, I will response this PR and determine whether change or how to change this codes. Before making sure, The PR will be pending, Sorry.

2022-11-02 20:30 UTC, PRANRAVEE approved these changes

2022-11-03 05:42 UTC, KomachiSion requested changes
Can you add some Unit test to ensure your changes has no effect for this method?

2022-11-03 06:16 UTC, RapperCL commented
> Can you add some Unit test to ensure your changes has no effect for this method?

OK, I'll add it later

2022-11-04 06:10 UTC, KomachiSion commented
> I'm contacting the author for this part codes. After making sure the codes meaning, I will response this PR and determine whether change or how to change this codes. Before making sure, The PR will be pending, Sorry.

I talk about this problem with author, he think the length of weight also should be `index`. So I think after your unit test finished, the PR can be merged.

2022-11-06 03:21 UTC, RapperCL commented
> > I'm contacting the author for this part codes. After making sure the codes meaning, I will response this PR and determine whether change or how to change this codes. Before making sure, The PR will be pending, Sorry.
> 
> I talk about this problem with author, he think the length of weight also should be `index`. So I think after your unit test finished, the PR can be merged.

Well, thank you. Interestingly, when I was writing the test case, I found that the chooser would have an exception in a special scenario. In order to prevent confusion, I raised an issue again [issue 9478](https://github.com/alibaba/nacos/issues/9478) and the corresponding pr submitted the solution and test case.

2022-11-09 01:49 UTC, KomachiSion approved these changes

2022-11-09 01:49 UTC, merged