[ISSUE #9393] 设置线程为守护线程，保证在main线程推出时应用程序能过正常关闭。
alibaba/nacos pull request #9396
Opened 2022-10-25 14:34 UTC by YunWZ

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change
To fix #9393 

将下面四种后台线程设置为守护线程，保证在main线程关闭时，nacos服务端进程能够正常关闭。例如：服务端创建bean失败或者通过 `/actuator/shutdown`接口关闭服务端时，进程能够正常关闭：

- "I/O dispatcher xx" / ""pool-xx-thread-xx" ： 在 `NacosAsyncRestTemplate` 中使用，用于处理异步请求;
- "/Users/xx/nacos/data/tps" : 在 `WatchFileCenter` 中使用，用于监视文件；
- "DistroExecuteTaskExecuteEngine" ： 在 `DistroExecuteTaskExecuteEngine` 中使用，用于处理Distro协议相关任务；
- "handle events" ： 在 `nacos-istio` 模块中使用，用于同步数据给Istio。

## Brief changelog

将上述四种后台线程设置为守护线程

## Verifying this change

配置错误的配置项，则nacos服务端启动失败，进程退出。例如下面的配置：
    ```propteries
    server.port=foo
    ```

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-10-27 20:53 UTC, hayya33 submitted a review, later dismissed

2022-10-31 04:00 UTC, KomachiSion requested changes

2022-11-02 06:27 UTC, KomachiSion requested changes

2022-11-02 06:27 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/misc/NamingExecuteTaskDispatcher.java
> +@Component
Not change it as spring bean, I means the old implementation `getExecuteEngine` change to `destory` and called in the code which calls `getExecuteEngine`

2022-11-03 05:43 UTC, KomachiSion approved these changes

2022-11-03 05:44 UTC, merged