[ISSUE #9643] Fixed Possible JSON Ordering Permutations Problem in Tests
alibaba/nacos pull request #9505
Opened 2022-11-08 06:09 UTC by bmk15897

Related to issue https://github.com/alibaba/nacos/issues/9463

## What is the purpose of the change
To fix the flaky test caused by possible JSON ordering permutations as explained in the issue https://github.com/alibaba/nacos/issues/9463.

## Brief changelog
1. Use a LinkedHashMap instead of HashMap to preserve the order of insertion.
2. Use the [@JsonPropertyOrder(alphabetic = true)](https://fasterxml.github.io/jackson-annotations/javadoc/2.8/com/fasterxml/jackson/annotation/JsonPropertyOrder.html#alphabetic()) to set order at the top of the ResultSet class.

## Verifying this change
This test avoids nested or different orders of JSON bytes that cause flaky errors.
There is 1 change in the source code - Annotation of the class ResultSet with [@JsonPropertyOrder(alphabetic = true)](https://fasterxml.github.io/jackson-annotations/javadoc/2.8/com/fasterxml/jackson/annotation/JsonPropertyOrder.html#alphabetic()) to ensure the order of properties while converting the object into a JSON string. The other change is in the test code, which changes HashMap to LinkedHashMap.
The changes passed the local tests that the guidelines mentioned.

Follow this checklist to help us incorporate your contribution quickly and easily:

 * [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2022-11-08 06:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=9505) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=9505) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=9505) it.</sub>

2022-11-08 06:21 UTC, li-xiao-shuang approved these changes

2022-11-09 01:27 UTC, KomachiSion requested changes
No reasonable fix.

The way should change the test case , not change original code.

2022-11-09 05:10 UTC, bmk15897 commented
I understand. I will attempt to fix the flaky test without changing the original code.

2022-11-10 01:48 UTC, KomachiSion commented
I think we can use contain to replace equals, for example, we can assertTrue `actual.contains("\"code\":0")` to replace assertEquals with expected and actual.

It will not depend order again.

2022-11-17 03:15 UTC, KomachiSion approved these changes

2022-11-17 03:40 UTC, merged