InstanceMetadata Latest effective add
alibaba/nacos pull request #9520
Opened 2022-11-10 02:27 UTC by godhth

#6358 
InstanceMetadata Latest effective add

2022-11-17 03:12 UTC, KomachiSion requested changes

2022-11-17 03:12 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
> +            instancePublishInfo.setLastUpdateTime(batchInstancePublishInfo.getLastUpdateTime());
Why set time in here？

2022-11-17 03:12 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
> +            if (switchDomain.isLatestEffective()
实现应该有问题，如果打开了这个开关且实例的更新时间大于元数据更新时间，不应该再调用updateInstanceMetadata

而是直接返回由instanceInfo生成的result，只有Metadata的更新时间更新或关闭开关时，才用metadata更新

2022-11-17 08:08 UTC, godhth commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
> +            instancePublishInfo.setLastUpdateTime(batchInstancePublishInfo.getLastUpdateTime());
批量注册的时候，只有batchInstancePublishInfo设置过更新时间，而其内部的批量实例没有更新时间。

2022-11-17 08:13 UTC, godhth commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
> +            instancePublishInfo.setLastUpdateTime(batchInstancePublishInfo.getLastUpdateTime());
https://github.com/alibaba/nacos/blob/1c08ac63bd879dde1bea5494c7b1265cec64f4a2/naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java#L73

2022-11-17 08:19 UTC, godhth commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
> +            if (switchDomain.isLatestEffective()
你说的这种情况是元数据的key少于由instanceInfo生成的result的key的情况，
但是可能元数据的key比instanceInfo要多，所以要调用updateInstanceMetadataIfAbsent补充进去。
不然用户拿到的数据就有缺失了。

2022-11-17 08:20 UTC, godhth commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
> +            if (switchDomain.isLatestEffective()
https://github.com/alibaba/nacos/blob/1c08ac63bd879dde1bea5494c7b1265cec64f4a2/naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java#L165

2022-11-22 01:49 UTC, KomachiSion commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
> +            if (switchDomain.isLatestEffective()
无关，因为instanceInfo的更新时间更大应该是有重新注册，策略既然是谁先用谁的，就不应该再带有上次更新旧实例中的metadata，应该直接覆盖旧的。

2022-11-22 06:14 UTC, godhth commented on naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
> +            if (switchDomain.isLatestEffective()
明白了，懂你意思了。

2022-12-14 07:45 UTC, closed without merging