支持自定义默认 tenant/namespaceId，避免 2.2 版本后新增 oracle 等其他数据源时使用空 ID导致的问题
alibaba/nacos pull request #9768
Opened 2022-12-30 01:33 UTC by xzxiaoshan

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

为空的 tenant/namespaceId 会导致 oracle 数据库无法正常开发多数据源，因为在 Oracle 数据库中 where tenant = ? （? 实际值为 ""） ，无法正常获取数据，oracle 数据库 "" 值实际上为 null。

## Brief changelog

1、现有 nacos 源码中对 NamespaceUtil.processNamespaceParameter(tenantId); 的处理，部分处理了部分没处理，本次统一集中筛选全部进行了处理，为可以统一处理默认 ID 做了基础。

2、新增可以自定义 tenant/namespaceId 配置，默认不配置照旧为 ""，但是用户可以按需配置，比如需要用到 Oracle 等其他数据库 "" 和 null 不分时，可以通过配置 默认 ID 来解决问题。

本次修改向前兼容，不产生其他影响。

2022-12-30 01:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=9768) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=9768) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=9768) it.</sub>

2022-12-30 07:08 UTC, xzxiaoshan commented
```
### The default tenant/namespace ID is empty, you can select to fill in as "public". Especially useful in Oracle database, oracle database fields do not distinguish between "" and null.
nacos.core.namespace.fill-public-id=true
```

![image](https://user-images.githubusercontent.com/16459864/210043864-518973c8-8e21-4abe-8642-c2fdc9e54798.png)

![image](https://user-images.githubusercontent.com/16459864/210043883-35fe39a6-cd66-44f8-88ab-6a31ad9c2be8.png)

2022-12-30 08:46 UTC, xzxiaoshan commented
同步解决 ISSUE  https://github.com/alibaba/nacos/issues/8774

2023-01-03 03:30 UTC, KomachiSion requested changes
Please discuss in issue first, I see the current changes maybe cause incompatible

2023-01-03 03:30 UTC, KomachiSion commented
What's more, please submit pr to `develop`

2023-01-03 04:05 UTC, xzxiaoshan commented
> 

好的，我删除这2个PR，合并到一起，统一提交到 develop 中，用一个新的PR 包含。3Q。

2023-01-03 04:26 UTC, closed without merging

2023-01-03 04:39 UTC, xzxiaoshan commented
详见：https://github.com/alibaba/nacos/pull/9784