[ISSUE#8774, ISSUE#9730] 支持通过配置开关填充public的ID、以及对多数据源插件代码进行调整（向前兼容）
alibaba/nacos pull request #9784
Opened 2023-01-03 04:38 UTC by xzxiaoshan

实现 ISSUE#8774，ISSUE#9730

https://github.com/alibaba/nacos/issues/8774
https://github.com/alibaba/nacos/issues/9730

## What is the purpose of the change

### 一、统一补充处理默认ID代码（ https://github.com/alibaba/nacos/issues/8774 ）

1、现有 nacos 源码中对 NamespaceUtil.processNamespaceParameter(tenantId); 的处理，部分处理了部分没处理，本次统一集中筛选全部进行了处理，为可以统一处理默认 ID 做了基础。

2、新增可以填充默认id 为public，配置文件中使用开关方式配置 `nacos.core.namespace.fill-public-id=true` ，默认不配置照旧默认id是 ""，但是用户可以按需打开，比如需要用到 Oracle 等其他数据库 "" 和 null 不分时，可以通过打开配置为 true 来解决问题。

![image](https://user-images.githubusercontent.com/16459864/210300531-bedd4019-b3d7-481d-afe2-3b95e3398452.png)

本次修改向前兼容，不产生其他影响。

### 二、对通用的SQL调整到接口默认实现中，更大程度的降低代码的重复度、使其他数据源插件的实现更容易（ https://github.com/alibaba/nacos/issues/9730 ）

多数据源插件，可以考虑为Mapper接口添加 default 方法，原因有下：

1、大部分的SQL都是标准的SQL，也就是可以在多种数据库中通用的。

2、对这些预判比较通用的SQL，写在Mapper接口中使用 default 方法来提供默认实现。

3、将类似分页这种肯定需要特定数据库实现的SQL定义为必须实现的方法，不使用 default。

这样以来，在为新的数据源写插件时，只需要重写需要重写的接口方法，而不再需要将所有SQL都拷贝一遍。这样更有利于避免或降低主版本需要修改SQL这种升级导致的插件不可用问题。

2023-01-03 04:45 UTC, xzxiaoshan commented
@KomachiSion 请审阅或提供意见，有社区QQ或微信交流吗？

2023-01-04 01:47 UTC, KomachiSion commented
> @KomachiSion 请审阅或提供意见，有社区QQ或微信交流吗？

提供钉钉号

2023-01-05 07:28 UTC, The-Gamer-01 submitted a review, later dismissed

2023-01-09 07:38 UTC, xzxiaoshan commented
暂时关闭，讨论新的方案后再做处理。插件实现方式会做调整。

2023-01-09 13:15 UTC, xzxiaoshan commented
重新打开，去除return public后提交，默认返回public交给以后充分考虑再决定。

2023-01-10 01:46 UTC, KomachiSion requested changes
改动仍旧不正确， 关于命名空间的改动应该彻底移除，如果需要改动应该单独提交PR。

这里PR应该至改动数据源插件部分。

2023-01-11 02:04 UTC, KomachiSion requested changes

2023-01-11 02:04 UTC, KomachiSion commented on common/src/main/java/com/alibaba/nacos/common/utils/NamespaceUtil.java
> +
Please use nacos code style to reformat code

2023-01-11 02:46 UTC, xzxiaoshan commented on common/src/main/java/com/alibaba/nacos/common/utils/NamespaceUtil.java
> +
已经理

2023-01-13 02:44 UTC, KomachiSion submitted a review, later dismissed

2023-01-13 05:43 UTC, xzxiaoshan reviewed
按照 nacos check style 标准做了处理

2023-01-16 08:14 UTC, merged