Extract the cluster of AbstractClusterRequest as a constant
alibaba/nacos pull request #9813
Opened 2023-01-07 14:19 UTC by sixsixsix516

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

To unify the code style.

Because I see that the implementation of the subclasses of com. alibaba. nacos. api. remote. request. Request # getModule uses the constants defined in the Constants, and only AbstractClusterRequest is a constant directly defined in the current class, which is inconsistent with the system code style.

因为我看见 com.alibaba.nacos.api.remote.request.Request#getModule 的子类的实现都是使用的 Constants 中定义的常量，而只有AbstractClusterRequest 是直接在当前类定义的一个常量，这与系统现代码风格不符

## Brief changelog
com.alibaba.nacos.naming.cluster.remote.request.AbstractClusterRequest#getModule 的返回值定义到了 

com.alibaba.nacos.api.common.Constants.Cluster#CLUSTER_MODULE

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-01-07 14:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=9813) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=9813) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=9813) it.</sub>

2023-01-08 07:56 UTC, The-Gamer-01 approved these changes

2023-01-09 05:13 UTC, KomachiSion requested changes
I can't get the change reason, the constants only one place used, I think should be local constants not common constants.

2023-01-11 01:45 UTC, KomachiSion commented
Other module like `naming` and `config`, the constants will be used by sub module with a large of number. So use `Constants`, but `cluster` is only for this sub-request, so no need to use `Constants`.

The `Constants` should contain constants which may be used by many different classes. For some of local constants, they should be defined in class itself.

2023-01-11 01:45 UTC, closed without merging