fix 配置管理历史版本分页
alibaba/nacos pull request #9822
Opened 2023-01-09 08:43 UTC by redscarfz

一、修复目的
基于Nacos2.2.0版本，实现配置管理历史版本分页
二、修复步骤
1、HistoryConfigInfoMapper接口新增String findConfigHistory4PageFetchRows(int pageNo, int pageSize);
2、HistoryConfigInfoMapperByDerby.java、HistoryConfigInfoMapperByMySql.java中分别实现 findConfigHistory4PageFetchRows
3、修改findConfigHistory调用方法：String sqlFetchRows = historyConfigInfoMapper.findConfigHistory4PageFetchRows(pageNo, pageSize);

2023-01-09 08:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=9822) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=9822) before we can accept your contribution.<br/><hr/>**zhao jingru** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=9822) it.</sub>

2023-01-10 02:14 UTC, KomachiSion commented
Can you submit issue first

2023-01-10 02:29 UTC, redscarfz commented
#9825

作者您好。nacos2.1.0之后版本并未更新derby-schema.sql，缺失ENCRYPTED_DATA_KEY，导致多页面接口错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2023年1月10日(星期二) 上午10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] fix 配置管理历史版本分页 (PR #9822)






你能先提交问题吗？

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

2023-01-11 01:35 UTC, KomachiSion requested changes

2023-01-11 01:35 UTC, KomachiSion commented on config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedHistoryConfigInfoPersistServiceImpl.java
> +
Please use nacos code style to reformat codes

2023-01-19 09:26 UTC, redscarfz reviewed
review

2023-01-28 02:41 UTC, KomachiSion commented
The CI can't pass, please fix the CI problem.

2023-02-03 07:42 UTC, KomachiSion commented
Fixed by #9828

2023-02-03 07:42 UTC, closed without merging