fix(修复配置历史分页异常): 配置历史分页异常，所有页都是全部记录
alibaba/nacos pull request #9828
Opened 2023-01-10 06:25 UTC by liu-xg

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

修改配置历史记录分页异常 #9825 

## Brief changelog

HistoryConfigInfoMapper新增page sql构造方法

## Verifying this change

1、默认连接derby数据库，配置新增超过10条记录，查看分页
2、连接mysql数据库，配置新增配置新增超过10条记录，查看分页

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-01-10 06:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=9828) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=9828) before we can accept your contribution.<br/><hr/>**liuxiong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=9828) it.</sub>

2023-01-10 09:14 UTC, 985492783 commented
it looked like conflict with the #9822.

2023-01-10 15:44 UTC, The-Gamer-01 submitted a review, later dismissed

2023-01-16 02:01 UTC, KomachiSion requested changes

2023-01-16 02:01 UTC, KomachiSion commented on plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java
> +
please use nacos code style to reformat codes

2023-01-16 13:39 UTC, liu-xg commented
收到发自我的 iPhone在 2023年1月16日，10:01，杨翊 SionYang ***@***.***> 写道：﻿
@KomachiSion requested changes on this pull request.



In plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java:
>      @Override
     public String detailPreviousConfigHistory() {
         return "SELECT nid,data_id,group_id,tenant_id,app_name,content,md5,src_user,src_ip,op_type,gmt_create,gmt_modified "
                 + "FROM his_config_info WHERE nid = (SELECT max(nid) FROM his_config_info WHERE id = ?)";
     }
-    
+

please use nacos code style to reformat codes

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-16 13:42 UTC, liu-xg commented
receive



At 2023-01-16 10:01:32, "杨翊 SionYang" ***@***.***> wrote:

@KomachiSion requested changes on this pull request.

In plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java:

>      @Override
     public String detailPreviousConfigHistory() {
         return "SELECT nid,data_id,group_id,tenant_id,app_name,content,md5,src_user,src_ip,op_type,gmt_create,gmt_modified "
                 + "FROM his_config_info WHERE nid = (SELECT max(nid) FROM his_config_info WHERE id = ?)";
     }
-    
+


please use nacos code style to reformat codes

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-28 02:40 UTC, KomachiSion commented
conflict with others PR, please rebase new codes and fix the conflicts.

2023-02-02 02:54 UTC, KomachiSion commented
@liu-xg Please sign your cla.

2023-02-02 06:03 UTC, liu-xg commented
已签署cla

2023-02-02 06:05 UTC, liu-xg commented
> @liu-xg Please sign your cla.

completed

2023-02-03 07:41 UTC, KomachiSion approved these changes

2023-02-03 07:41 UTC, merged