✨ fix LDAP login failed
alibaba/nacos pull request #9932
Opened 2023-02-10 13:21 UTC by tonycody

✨ fix LDAP AD login Ignore partial result exception

#9862 

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-02-10 13:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=9932) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=9932) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=9932) it.</sub>

2023-02-13 01:45 UTC, KomachiSion requested changes

2023-02-13 01:45 UTC, KomachiSion commented on plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java
> +
Please use nacos code style to reformat codes

2023-02-13 02:59 UTC, tonycody commented on plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java
> +
构建过的，风格校验没问题。

2023-02-13 03:04 UTC, tonycody commented on plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java
> +
关于风格的问题，咱是不是可以通过：spotless 或 Spring Java Format 直接规整下？而不是检查。

2023-02-13 06:56 UTC, KomachiSion commented on plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java
> +
自动规整的问题可以研究下， 不过这个PR肯定没有用nacos code style进行reformat， 因为缩进被去掉了。

2023-02-20 02:09 UTC, KomachiSion requested changes
缩进问题依旧没有修改

2023-02-21 02:24 UTC, KomachiSion approved these changes

2023-02-22 03:18 UTC, KomachiSion approved these changes

2023-02-22 03:18 UTC, merged