[ISSUE#9860]logback support 1.4.5
alibaba/nacos pull request #9934
Opened 2023-02-11 10:44 UTC by hujun-w-2

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

for #9860

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

2023-02-21 02:23 UTC, KomachiSion requested changes

2023-02-21 02:23 UTC, KomachiSion commented on client/src/main/java/com/alibaba/nacos/client/logging/logback/NacosClientLogbackProperties.java
> +public class NacosClientLogbackProperties implements NacosLogbackProperties {
What's the usage of NacosLogbackProperties?

2023-02-21 02:47 UTC, hujun-w-2 commented on client/src/main/java/com/alibaba/nacos/client/logging/logback/NacosClientLogbackProperties.java
> +public class NacosClientLogbackProperties implements NacosLogbackProperties {
当前的版本有个nacos的NacosClientProperties xml标签适配了logback，但是NacosClientProperties在nacos-client包.
这样的目的是为了方便适配logback的组件（logback-adapter）可以在不依赖nacos-client包的情况下调用到NacosClientProperties，从而也能调用到NacosClientProperties

2023-02-22 03:20 UTC, KomachiSion approved these changes

2023-02-22 03:20 UTC, merged