Optimize the `pom.xml` of the `nacos-client` for exclude `/META-INF/native-image/*`
alibaba/nacos pull request #9982
Opened 2023-02-21 03:31 UTC by wangliang181230

Optimize the `pom.xml` of the `nacos-client` for exclude `/META-INF/native-image/*`
优化 `nacos-client`的 `pom.xml`，用于排除掉 `/META-INF/native-image/*`。

See：
![图片](https://user-images.githubusercontent.com/1527893/220240491-81881061-1e3f-4771-95da-c4014f70231d.png)

2023-02-21 03:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/nacos?pullRequest=9982) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/nacos?pullRequest=9982) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/nacos?pullRequest=9982) it.</sub>

2023-02-21 03:37 UTC, wangliang181230 commented on client/pom.xml
> +                                                META-INF/native-image/**
此PR主要添加了此配置。

2023-02-21 04:30 UTC, wangliang181230 commented on client/pom.xml
> +                                                google/**/*.proto
此PR两处主要变更之一

2023-02-22 00:49 UTC, Tonibrown20 submitted a review, later dismissed
Great future ahead

2023-02-22 02:53 UTC, KomachiSion requested changes
Please use nacos code style to reformat code

the indent in this pr has problem

2023-02-22 02:54 UTC, KomachiSion commented
顺便问一下 native-image也移除掉会不会影响 java native（graalVM）的功能？

2023-02-22 02:57 UTC, wangliang181230 commented
> 顺便问一下 native-image也移除掉会不会影响 java native（graalVM）的功能？

需要时，应该去oracle仓库里加。之前和SCA那边沟通过，是说阿里以后都统一去oracle仓库里提PR，而不是写在jar里。

2023-02-22 03:00 UTC, wangliang181230 commented
> 顺便问一下 native-image也移除掉会不会影响 java native（graalVM）的功能？

另外，我本地排除掉后，也在native-image里试过，可以正常使用。

2023-02-22 03:27 UTC, wangliang181230 commented
> Please use nacos code style to reformat code
> 
> the indent in this pr has problem

done

2023-02-22 11:37 UTC, wangliang181230 commented
> 顺便问一下 native-image也移除掉会不会影响 java native（graalVM）的功能？

另外，我仔细看了一下从 `io.grpc:grpc-netty-shaded` shade 到 `nacos-client` 的这些 `native-image` 文件，其实又是从 `io.netty:*` 的各模块里 shade 进 `io.grpc:grpc-netty-shaded` 的。
也就是说，这些配置文件并不属于 `io.grpc:grpc-netty-shaded`。

而 `nacos-client` 并没有 shade `io.netty:*`，所以，这部分配置文件是不需要的。

但是，我的PR里，还是得修改一下。排除掉 `io.grpc:grpc-netty-shaded` 的 `/META-INF/native-image/io.netty/**`，而不是 `/META-INF/native-image/**`。因为万一以后`io.grpc:grpc-netty-shaded`拥有自己的native-image时，估计得shade进来。

2023-02-22 11:38 UTC, wangliang181230 commented
![图片](https://user-images.githubusercontent.com/1527893/220609402-81c6500e-03b4-45d6-9f82-2d30859fab99.png)

2023-02-23 08:23 UTC, wangliang181230 commented
@KomachiSion
我对比了一下 `nacos-client` 和 `io.grpc:grpc-netty-shaded` 两个jar中shade进去的 `/META-INF/native-image`，发现 `nacos-client` 里的，没有在包名前面添加上 `com.alibaba.nacos.shaded.` 的前缀，而 `io.grpc:grpc-netty-shaded` 在 `io.netty` 包名的基础上拼接了 `io.grpc.shaded.` 作为前缀，因为shade进来的所有类，包名都变了。

目前，可能是 shade 插件有问题。

2023-02-24 01:52 UTC, KomachiSion commented
native-image是不是需要自己生成，直接shard应该不行？

2023-02-24 01:53 UTC, KomachiSion commented
我觉得可以提个issue来讨论， PR先不提交。 讨论并测试清楚之后再提交。

我觉得这个natvie-image应该是jdk17的 graalVM所用到的， 不shard进去不影响普通的使用，但在graalVM中可能有影响。

2023-02-24 01:54 UTC, wangliang181230 commented
> native-image是不是需要自己生成，直接shard应该不行？

我看了下grpc那边的源码，由于是gradle，不是maven，很多我看的不是很懂，但是应该是使用了shade插件的功能，自动补充了前缀。

2023-02-24 01:54 UTC, wangliang181230 commented
> 我觉得可以提个issue来讨论， PR先不提交。 讨论并测试清楚之后再提交。
> 
> 我觉得这个natvie-image应该是jdk17的 graalVM所用到的， 不shard进去不影响普通的使用，但在graalVM中可能有影响。

嗯，可以的，那我这个PR先暂时只移除proto文件吧。

2023-02-24 01:54 UTC, wangliang181230 commented
我另外提个issue

2023-02-24 02:02 UTC, wangliang181230 commented
> 我觉得可以提个issue来讨论， PR先不提交。 讨论并测试清楚之后再提交。
> 
> 我觉得这个natvie-image应该是jdk17的 graalVM所用到的， 不shard进去不影响普通的使用，但在graalVM中可能有影响。

我测试过，不影响，因为shade进来的配置本来就是错的，包名和shaded进来的类名对不上。

2023-02-24 02:59 UTC, wangliang181230 commented
这个PR已经好了，排除native-image的代码撤回了。
@KomachiSion PTAL

2023-02-27 02:57 UTC, KomachiSion approved these changes

2023-03-01 01:42 UTC, merged